### DISCUSSION TITLE
Agent to Collector with HTTP (k8s ingress)

### DISCUSSION THREAD

**Discussion by ebuildy** [jaegertracing/jaeger#2755] [General]
We are using Jaeger "official" Helm chart to run jaeger on kubernetes.

Now we have a collector with HTTP API open with an ingress.

I would like to use this collector from an agent running on my laptop (for dev purposes), is it possible?

**Comment by ebuildy** [comment]
I was able to add an ingress for GRPC:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/common-name: jaeger-collector-grpc.dev-steam.XXXXX
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: djobi-metrics-jaeger-collector-grpc
  namespace: dev-steam
spec:
  rules:
  - host: jaeger-collector-grpc.dev-steam.XXXX
    http:
      paths:
      - backend:
          serviceName: djobi-metrics-jaeger-collector
          servicePort: grpc
  tls:
  - secretName: djobi-metrics-jaeger-collector-grpc-ssl
    hosts:
      - jaeger-collector-grpc.dev-steam.XXXX
```

maybe we should add this ingress to the Helm as well?
