### DISCUSSION TITLE
How-To Jaeger & Prometheus ?

### DISCUSSION THREAD

**Discussion by mikeumus** [jaegertracing/jaeger#2834] [Q&A] [answered]
When you run `jaeger/all-in-one`, do you still need to run Prometheus separately? 

I see `--metrics-backend  prometheus` in https://www.jaegertracing.io/docs/1.21/cli/#jaeger-all-in-one but does this mean Prometheus is already running? 

How do you Jaeger + Prometheus?

**Comment by yurishkuro** [comment, marked as answer]
Jaeger does not run Prometheus. `--metrics-backend prometheus` simply means the Prometheus metrics format is being used.

**Reply by huahuayu** [reply]
Is there a `prometheus.yml` example for jaeger. I use below compose file for prometheus & jaeger all-in-one, but I don't know how to config `prometheus.yml` to make `http://jaeger-host/monitor` work.

```
  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ${PROMETHEUS_CONF}:/etc/prometheus/
      - ${PROMETHEUS_DATA}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411" 
      COLLECTOR_OTLP_ENABLED: true
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: prometheus:9090
```
