### DISCUSSION TITLE
How to start collector's Zipkin server via operator deployment?

### DISCUSSION THREAD

**Discussion by gsagula** [jaegertracing/jaeger#2959] [Q&A]
How do I start Zipkin server using the operator?

{"level":"info","ts":1619421380.7131286,"caller":"server/zipkin.go:48","msg":"Not listening for Zipkin HTTP traffic, port not configured"} 

It seems to be off by default: https://github.com/jaegertracing/jaeger/blob/312f83bdda8f4ded6037f37a554f2fbd213ac0ac/cmd/collector/app/builder_flags.go#L70

Thank you.

**Comment by jpkrohling** [comment]
You are talking about a Jaeger provisioned by the Jaeger Operator for Kubernetes, right? If so, the operator actually enables it by default:

https://github.com/jaegertracing/jaeger-operator/blob/65490e8fdc240b3bf9a25297dfc1627372134791/pkg/deployment/collector.go#L131-L132

Could you please share your Jaeger CR? If the operator isn't opening the Zipkin port by default, we might have a bug somewhere.

**Reply by gsagula** [reply]
@jpkrohling Thank you for the quick response.
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: mon-jaeger
  namespace: observability
spec:
  log-level: debug
  strategy: streaming
  collector:
    options:
      kafka: 
        producer:
          topic: jaeger-spans
          brokers: knative-kafka-cluster.knative-kafka:9092
  ingester:
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: knative-kafka-cluster.knative-kafka:9092
      ingester:
        deadlockInterval: 0s
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic-es-http:9200
        index-prefix: jaeger-tracing
        tls:
          ca: /es/certificates/ca.crt
    secretName: jaeger-secret
  volumeMounts:
    - name: certificates
      mountPath: /es/certificates/
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elastic-es-http-certs-public
```

I did't have a chance to go throw the code yet but I can tell that the problem started on the latest release `jaegertracing/jaeger-operator:1.22.1`. 

I opened this [issue](https://github.com/jaegertracing/jaeger/issues/2960).
