### DISCUSSION TITLE
Help? Having trouble under Docker Compose getting trace information from my app into jaeger

### DISCUSSION THREAD

**Discussion by brunojus** [jaegertracing/jaeger#2973] [General]
I have 4 microservices, where three are web applications that running inside a docker container, and I use docker-compose to expose these services. I have the app-controller that runs outside this container, and the function is to call the other services. When I put to run these three web services without docker-compose, I created the spans correctly and sent them to the Jaeger collector, but when I running these services with docker-compose, only the span of the app controller is created. 

Docker-compose.yml

```
    version: '3.7'
    
    services:
    
          gather_hr:
              container_name: gather_hr-app
              build:
                  context: gather_hr/.
              depends_on:
                - jaeger
              volumes:
                  - ./gather_hr/gather_hr/input:/input
              ports:
                  - "5001:5001"
              environment:
                  - WEB_PORT=5001
                  - INPUT_DIR=/input
              networks:
                  - labnetwork
          process_payroll:
              container_name: process_payroll-app
              build:
                  context: process_payroll/.
              depends_on:
                - jaeger
              ports:
                  - "5002:5002"
              environment:
                  - WEB_PORT=5002
              networks:
                - labnetwork
        
          generate_payslip:
              container_name: generate_payslip-app
              build:
                  context: generate_payslip/.
              depends_on:
                - jaeger
              volumes:
                  - ./generate_payslip/generate_payslip/output:/output
              ports:
                  - "5003:5003"
              environment:
                  - WEB_PORT=5003
                  - OUTPUT_DIR=/output/
              networks:
                - labnetwork
        
          jaeger:
            image: "jaegertracing/all-in-one:1.22.0"
            ports:
              - "6831:6831/udp"
              - "16686:16686"
              - "16687:16687"
            environment:
              SPAN_STORAGE_TYPE: "elasticsearch"
              ES_SERVER_URLS: "http://elasticsearch:9200"
              ES_TAGS_AS_FIELDS: "true"
            depends_on:
              - elasticsearch
            healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:16687/"]
              interval: 30s
              timeout: 10s
              retries: 5
              start_period: 30s
            restart: on-failure
            networks:
                - labnetwork
        
        networks:
            labnetwork:
```

settings.py

```
    import logging
    import os
    
    from opentelemetry import trace
    from opentelemetry.exporter.jaeger.thrift import JaegerExporter
    from opentelemetry.sdk.resources import SERVICE_NAME, Resource
    from opentelemetry.sdk.trace import TracerProvider
    from opentelemetry.sdk.trace.export import BatchSpanProcessor
    
    
    def server_configuration():
        config = {}
        # microservices
        config["url_api_hr_data"] = os.environ.get("URL_API_HR_DATA", 'http://localhost:5001/api/employee/') 
        config["url_api_process"] = os.environ.get("URL_API_PROCESS", 'http://localhost:5002/api/payroll/')
        config["url_api_payslip"] = os.environ.get("URL_API_PAYSLIP", 'http://localhost:5003/api/payslip/')
        # payslips output
        config["output_dir"] = os.environ.get("OUTPUT_DIR", "./output/")
        # connection handle
        config["no_cache"] = False
        config["max_retries"] = os.environ.get("MAX_RETRIES", 10)
        # config["retry_delay"] = os.environ.get("RETRY_DELAY", 1)
        return config
    system_config = server_configuration()
    
    trace.set_tracer_provider(
        TracerProvider(
            resource=Resource.create({SERVICE_NAME: "appcoordinator"})
        )
    )
    
    jaeger_exporter = JaegerExporter(agent_host_name="localhost", agent_port=6831,)
    
    trace.get_tracer_provider().add_span_processor(
        BatchSpanProcessor(jaeger_exporter)
    )
    
    
    logging.basicConfig(
        format=("%(asctime)s,%(msecs)-3d - %(levelname)-8s => %(message)s"), # - %(name)-12s
        datefmt="%Y-%m-%d %H:%M:%S",
        level=logging.DEBUG
    )
    logger = logging.getLogger(__name__)
    tracer = trace.get_tracer(__name__)

```
