### DISCUSSION TITLE
Sampling strategies doesn't seem to work

### DISCUSSION THREAD

**Discussion by RieUchdia** [jaegertracing/jaeger#3365] [Q&A]
Hi, I have a question regarding probabilistic sampling in jaeger-collector.
I'm configuring Jaeger collector sampling using a json file named strategies.json for a Jaeger distributed system. And I'm using a docker-compose for Jaeger collector and the query.

Here is the strategies.json file I used,
```
{
  "service_strategies": [
    {
      "service": "<My service A>",
      "type": "probabilistic",
      "param": 0.0
    },
    {
      "service": "<My service B>",
      "type": "probabilistic",
      "param": 0.0
    }
  ],
  "default_strategy": {
    "type": "probabilistic",
    "param": 0.0
  }
}
```

and here is the docker-compose file I used,
```
version: "3.1"

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector
    volumes:
      - "./jaeger/:/etc/jaeger/"
    command:
      [
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--es.server-urls=http://elasticsearch:9200",
        "--collector.zipkin.host-port=:9411",
        "--sampling.strategies-file=/etc/jaeger/sampling.json",
      ]
    ports:
      - "14269"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - LOG_LEVEL=debug
    restart: on-failure
    links:
      - elasticsearch
  jaeger-query:
    image: jaegertracing/jaeger-query
    command:
      [
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--es.server-urls=http://elasticsearch:9200",
      ]
    ports:
      - "16686:16686"
      - "16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - LOG_LEVEL=debug
    restart: on-failure
    links:
      - elasticsearch
networks:
  default:
    external:
      name: environment_network
```

 I would expect that, the samplingRate: 0 applies and those traces will not be stored.

The jaeger-client within application is configured to use remote-sampling.
Any suggestions on what may be the issue, or how can I troubleshoot this further?

**Comment by joe-elliott** [comment]
By default the Jaeger client will attempt to send traces to `localhost:6831`. I'm unsure if your docker-compose correctly sets up communication on localhost between jaeger-query and jaeger-collector. Since I don't see any other applications I assume that you're tracing Jaeger query here?

Configuration env vars here: https://github.com/jaegertracing/jaeger-client-go

> I would expect that, the samplingRate: 0 applies and those traces will not be stored.  

Can you be more explicit about what you're seeing and what you expect?

**Reply by RieUchdia** [reply]
Thank you for your response.

I configured env vars for jaeger-client and my apps:
```
version: '3.1'
services:
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=10.13.255.36:14250", "--reporter.grpc.retry.max=1000"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
  my-service-A:
    image: <my-service-A-image>
    volumes:
      - ./dest:/go/dest
    ports:
      - "${HOST_PORT}:50051"
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLER_REFRESH_INTERVAL=30ms
  my-service-B:
    image: <my-service-B-image>
    volumes:
      - ./dest:/app/dest
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLER_REFRESH_INTERVAL=30ms
networks:
  default:
    external:
      name: environment_network

```

> Can you be more explicit about what you're seeing and what you expect?

I would expect that, the samplingRate: 0 applies and those traces is not displayed on the Web UI for Jaeger.
Actually, those traces is displayed on Jaeger-UI even though I configured samplingRate:0.
