### DISCUSSION TITLE
Integration with Data prepper

### DISCUSSION THREAD

**Discussion by serg-bs** [jaegertracing/jaeger#3426] [Q&A]
Now we have installed jaeger-operator with backend elastic.
Now I want to integrate [Data prepper](https://github.com/opensearch-project/data-prepper/blob/main/examples/jaeger-hotrod/docker-compose.yml) 

But don't know how to right traslate from docker-compose
```yaml
 otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.24.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    working_dir: "/project"
    volumes:
      - ${PWD}/:/project
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      - ../demo/demo-data-prepper.crt:/etc/demo-data-prepper.crt
    ports:
      - "14250:14250"
    depends_on:
      - data-prepper
    networks:
      - my_network
```

to 
```yaml
kind: Jaeger
metadata:
    name: simple-prod
spec:
    strategy: production
    ingress:
        enabled: false
    collector:
      image: otel/opentelemetry-collector
      # Here is I should setup some config
```

How could I see all possible config for operator? 
In case of helm chart I could manage resource, but here many detail hidden and I could not see whole picture.
