### DISCUSSION TITLE
How to set es-provision using jaeger operator

### DISCUSSION THREAD

**Discussion by ErikXu** [jaegertracing/jaeger#3463] [Q&A]
I am using the jaeger operator v1.22.1 to create a jaeger instance with self provisioned elasticsearch. I get this message
`level=warning msg="An Elasticsearch cluster should be provisioned, but provisioning is disabled for this Jaeger Operator" instance=jaeger namespace=istio-system` from the jaeger pod.

I might need to set the flag `--es-provision=true`, but I can not find a place to do so.

Here is my crd yaml:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  namespace: istio-system
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 1
      storage:
        storageClassName: gp2
        size: 5Gi
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi
      redundancyPolicy: ZeroRedundancy
  collector:
    options:
      collector.zipkin.host-port: ':9411'
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  query:
    replicas: 1
    labels:
      sidecar.jaegertracing.io/injected: "false"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
```
