### DISCUSSION TITLE
How to set args in Jaeger DaemonSet?

### DISCUSSION THREAD

**Discussion by mitul01** [jaegertracing/jaeger#3536] [Q&A]
I am trying to deploy a jaeger daemonset which collects traces and sends it to wavefront dashboard. As per the documentation I have installed jaeger operator and I'm using below yaml file to deploy a daemon set with updated args but the agent is still using the default args which is the jaeger collector.
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
spec:
  agent:
    strategy: DaemonSet
    args:
      #- --reporter.grpc.host-port=dns:///jaeger-collector-headless.observability:14250
      - --reporter.type=grpc
      - --reporter.grpc.host-port=wavefront-proxy.default:14250 # sending data to wavefront UI using a proxy 
```
The documentation provides an example of how to update the args in the manual sidecar method which I tried and it works successfully. 
But I wanted to try the daemon set method since I have large number of pods and injecting a manual sidecar in each of the pods does not sound to be the most efficient method. But I'm not sure how to edit the arguments of the DaemonSet agent. 

Below is the log which shows the daemonset connected to the default collector instead of the wavefront proxy that i provided.
```
{"level":"info","ts":1645079306.225089,"caller":"grpc/builder.go:121","msg":"Agent collector connection state change","dialTarget":"dns:///my-jaeger-collector-headless.default:14250","status":"READY"}
```

**Comment by frzifus** [comment]
Hi mitul01, maybe your arguments are ignored because they are not assigned to `options`[0].

```yaml
  agent:
    strategy: DaemonSet
    options:
      args:
        - --reporter.type=grpc
        - --reporter.grpc.host-port=wavefront-proxy.default:14250 
```

Could you test this?


0: https://github.com/jaegertracing/jaeger-operator/blob/030142aeda1076deaeafa9f70795128f6de98777/apis/v1/jaeger_types.go#L460
