### DISCUSSION TITLE
K8s Jaeger Operator on version 1.29.0 loops on Terminating and ContainerCreating

### DISCUSSION THREAD

**Discussion by stevensim226** [jaegertracing/jaeger#3586] [Q&A]
I am currently using Jaeger Operator version 1.29.0 on Kubernetes `v1.21.6-gke.1503` with a production configuration as follows:
```
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: <JAEGER NAME>
  namespace: <NAMESPACE NAME>
spec:
  agent:
    options: {}
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 10Mi
  allInOne:
    options: {}
    resources: {}
  collector:
    options: {}
    resources:
      limits:
        cpu: 250m
        memory: 160Mi
      requests:
        cpu: 150m
        memory: 160Mi
  ingester:
    options: {}
    resources: {}
  query:
    options: {}
    resources:
      limits:
        cpu: 250m
        memory: 100Mi
      requests:
        cpu: 150m
        memory: 100Mi
  sampling:
    options: {}
  storage:
    dependencies:
      enabled: true
      resources:
        limits:
          memory: 4096Mi
        requests:
          memory: 4096Mi
      schedule: 55 16 * * *
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      schedule: 55 16 * * *
    options:
      es:
        server-urls: http://A.B.C.D:XYZ/
    type: elasticsearch
  strategy: production
```

It worked fine before, but as of today the collector and query pods went into a loop of Terminating and ContainerCreating. I tried downgrading to `1.22.0` and it went kind of fine as in there's at least 1 healthy pod for each Collector and Query but I also found that it keeps spawning new collector and query pods that also went into the same loop

FYI, I also found that in `kubectl events` that there's an error about Volume as follows
```
38m         Warning   Failed                    pod/<COLLECTOR POD NAME>       Error: cannot find volume "<COLLECTOR POD NAME>-configuration-volume" to mount into container "jaeger-collector"
```

Does anyone have an idea about this?
