### DISCUSSION TITLE
Rollover ES indices

### DISCUSSION THREAD

**Discussion by VladimirTitov4** [jaegertracing/jaeger#3634] [Q&A]
Hello everyone, thank you for your time in advance. 

Below is my docker-compose configuration for running jaeger with ES storage. 
I miss one thing - customizing **rollover for ES indices**. 

```
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
  networks:
    - elastic-jaeger
  ports:
    - "127.0.0.1:9200:9200"
    - "127.0.0.1:9300:9300"
  restart: on-failure
  environment:
    - cluster.name=jaeger-cluster
    - discovery.type=single-node
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    - xpack.security.enabled=false
  volumes:
    - esdata:/usr/share/elasticsearch/data

jaeger-collector:
  image: jaegertracing/jaeger-collector
  ports:
    - "14269:14269"
    - "14268:14268"
    - "14267:14267"
    - "14250:14250"
    - "9411:9411"
  networks:
    - elastic-jaeger
  restart: on-failure
  environment:
    - SPAN_STORAGE_TYPE=elasticsearch
  command: [
    "--es.server-urls=http://elasticsearch:9200",
    "--es.num-shards=1",
    "--es.num-replicas=0",
    "--es.use-aliases=true",
    "--log-level=error"
  ]
  depends_on:
    - elasticsearch

jaeger-agent:
  image: jaegertracing/jaeger-agent
  hostname: jaeger-agent
  command: [ "--reporter.grpc.host-port=jaeger-collector:14250" ]
  ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
  networks:
    - elastic-jaeger
  restart: on-failure
  environment:
    - SPAN_STORAGE_TYPE=elasticsearch
  depends_on:
    - jaeger-collector

jaeger-query:
  image: jaegertracing/jaeger-query
  environment:
    - SPAN_STORAGE_TYPE=elasticsearch
    - no_proxy=localhost
  ports:
    - "16686:16686"
    - "16687:16687"
  networks:
    - elastic-jaeger
  restart: on-failure
  command: [
    "--es.server-urls=http://elasticsearch:9200",
    "--span-storage.type=elasticsearch",
    "--log-level=debug"
  ]
  depends_on:
    - jaeger-agent

#start here I've got problems, this container doesn't start
jaeger-rollover:
  image: jaegertracing/jaeger-es-rollover
  command: [
    "rollover",
    "http://elasticsearch:9200",
    "--conditions",
    "{\"max_age\": \"20s\"}"
  ]
networks:
  - elastic-jaeger
#end

volumes:
esdata:
  driver: local

networks:
elastic-jaeger:
  driver: bridge
```

Could you please explain, how to configure rollover time for jaeger indices ?

Actually, with provided docker-compose I have daily indices, such as jaeger-span-2022-04-18 & jaeger-service-2022-04-18
