### DISCUSSION TITLE
jaeger-all-in-one returns GRPC error NOT_FOUND for GetTrace

### DISCUSSION THREAD

**Discussion by pkrishnanreflexion** [jaegertracing/jaeger#3809] [Q&A] [answered]
I am using Jaeger-all-in-one deployed like this in docker-compose
```

   jaeger-all-in-one:
        image: jaegertracing/all-in-one:1.23
        networks:
            - elastic-jaeger
        ports:
            - "16686:16686" # localhost
            - "16685:16685" # jaeger grpc
            - "14269:14269" # /metrics
            - "6831:6831/udp" # agent
        restart: on-failure
        environment:
            - ES_MAX_SPAN_AGE=2160h0m0s
            - SPAN_STORAGE_TYPE=elasticsearch
            - ES_SERVER_URLS=http://elasticsearch:9200
            - ES_TAGS_AS_FIELDS_ALL=true
            - JAEGER_DISABLED=true
        command: "--log-level=debug"
        depends_on:
            - elasticsearch
          
```
I am using GRPC query `getTrace` in Python as follows

```
   channel1 = grpc.insecure_channel(JAEGER_QUERY_GRPC)
   stub1 = query_pb2_grpc.QueryServiceStub(channel1)
   try:
        t = b'a58f82ec66388fde'
        response1 = stub1.GetTrace(query_pb2.GetTraceRequest(trace_id=t))
    except grpc.RpcError as e:
        print(e.details())
        status_code = e.code()
        print(status_code.name)
        print(status_code.value)

```
This code does not go into the "except" block and fetches result. However on trying to use response, the following error is seen.

> grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
> 	status = StatusCode.NOT_FOUND
> 	details = "trace not found: trace not found"
> 	debug_error_string = "{"created":"@1657643059.385252000","description":"Error received from peer ipv6:[::1]:16685","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"trace not found: trace not found","grpc_status":5}"
> 

However, the Jaeger UI and CURL command fetch expected results for the same trace id.
The logs of jaeger-all-in-one in debug mode do not reveal anything more than the above msg. 
Also, in the same setup, I am able to run other GRPC queries like "GetServices" and "FindTraces" without problems.

What is in correct in the "GetTrace" call?
