### DISCUSSION TITLE
Jaeger unable to use opensearch 1.3

### DISCUSSION THREAD

**Discussion by cablunar** [jaegertracing/jaeger#3916] [Q&A] [answered]
I just upgraded my instance to opensearch 1.3.
However, this seams to break the jaeger deployment.

Is it possible to use, if so what needs to be changed in my jaeger deployment?
Thx 🙏 
![image](https://user-images.githubusercontent.com/99737288/191041323-2de6f33e-1722-41f9-aaa0-4768539a94ae.png)

**Comment by cablunar** [comment, marked as answer]
I needed to add the following parameters, then it worked with 1.3.
```
es:
  index-prefix: jaeger_
  version: 7                                  
  create-index-templates: false
```
