### DISCUSSION TITLE
How to use jaeger-query-ui to use the data collected by open telemetry collector

### DISCUSSION THREAD

**Discussion by sathishsoundharajan** [jaegertracing/jaeger#3952] [Q&A] [answered]
Hi, I'm using otel-collector as agent and otel-collector as gateway to collect the traces and send it to elasticsearch backend. How can i use jaeger-ui to visulize this ?

Config Files

Agent Config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-agent-config
  labels:
    app: otel-collector-agent
data:
  otel-collector-agent.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 156
        spike_limit_mib: 48
      
    extensions:
      health_check: {}
      memory_ballast:
        size_mib: "78"
      
    exporters:
      logging: {}
      otlp:
        endpoint: otel-collector:4317
        tls:
          insecure: true

    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        traces:
          exporters:
            - otlp
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
```

Collector Config

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      
    exporters:
      logging: {}

      elasticsearch/trace:
        endpoints: [http://elasticsearch:9200]
        # traces_index: otlp-traces
        tls:
          insecure_skip_verify: true

    extensions:
      health_check: {}
      memory_ballast: {}

    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_mib: 156
        spike_limit_mib: 48

    service:
      extensions:
        - health_check
        - memory_ballast
      
      pipelines:
        traces:
          exporters:
            - logging
            - elasticsearch/trace
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch

```

I can see the traces like this collected in elastic search.
```
health status index                  uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .geoip_databases       xb503ibjSdS6QxGtBnyScA   1   0         40            0     38.4mb         38.4mb
yellow open   traces-generic-default Q3nFwpg1S4m3GsXPPSZ85Q   1   1         74            0    173.5kb        173.5kb

```
Screenshot

<img width="1621" alt="Screenshot 2022-10-07 at 9 24 39 PM" src="https://user-images.githubusercontent.com/8023447/194596487-469d0b50-68c9-4c0d-95ee-f84fbfc62326.png">
