### DISCUSSION TITLE
Can not export when another service hosted in docker tries

### DISCUSSION THREAD

**Discussion by bfaccruent** [jaegertracing/jaeger#4064] [Q&A] [answered]
Hi

I have the following configuration of docker-compose : 

```
version: '3.4'

services:
 api:
  image: api_6_sample
  build:
   dockerfile: API_6/Dockerfile
   args:
    Nuget_CustomFeedPassword: ""
  environment:
    ASPNETCORE_ENVIRONMENT: "Development"
  ports:
    - "5100:80"
    - "5101:443"
  depends_on:
    - jaeger
  links:
      - "jaeger:jaeger"
  networks:
    - gateway

 sample_host:
   image: sample_6_host
   build:
    dockerfile: Sample_WorkerService/Dockerfile
    args:
     Nuget_CustomFeedPassword: ""
   environment:
    DOTNET_ENVIRONMENT: "Development"
   links:
      - "jaeger:jaeger"
   networks:
    - gateway 

 jaeger:
  hostname: "jaeger"
  image: jaegertracing/all-in-one:latest
  ports:
      - "14268:14268"
      - "16686:16686"
  networks:
   - gateway

networks:
  gateway:
```

I tried to ping "jaeger" from "API" service and it returned success. But the API_App using the following configuration in .NET does not export data and shows no error. When I run the API locally and use change host name from "jaeger" to "localhost" it works. 

What could be the cause ? 

```
builder.AddJaegerExporter(x =>
                {
                    x.Protocol = HttpBinaryThrift
                    x.AgentPort = 14268;
                    x.AgentHost = "jaeger";
                });
```
