### DISCUSSION TITLE
Unable to connect ElasticSearch from docker image 'jaegertracing/all-in-one:1.36'

### DISCUSSION THREAD

**Discussion by mong0520** [jaegertracing/jaeger#4203] [Q&A]
Hi folks, 

I'm new to jaeger and now I can successfully setup an jaegertracing/all-in-one:1.36 with in-memory storage.

Now I'm trying to change the storage from in-memory to ElasticCache by setting the `docker-compose.yaml` below:
```yaml
...
jaeger:
    image: jaegertracing/all-in-one:1.41
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: https://docker.for.mac.host.internal:9200
      ES_ARCHIVE_USERNAME: master
      ES_ARCHIVE_PASSWORD: mypassword
      ES_TLS_SKIP_HOST_VERIFY: "true"
      ES_TLS_ENABLED: "true"
...
```

Before that, I do make sure that the ElasticCache service can be visited from the jaeger container inside by running the curl command:
```sh
# inside the jaeger container
curl --request GET --url 'https://docker.for.mac.host.internal:9200' --header 'Authorization: Basic mypassword' -k
{
  "name" : "8b72877d3f2427f3922634dc51847aaa",
  "cluster_name" : "410964885858:es-demo",
  "cluster_uuid" : "PN_j1yKGTguGJeqlpbVOCA",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2022-09-01T11:13:58.536555Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

However, when I run the jaeger container via docker-compose, it raises error and quit, what should I do?
key error:
`"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available"`
```shell
docker-compose up jaeger

Recreating demo_jaeger_1 ... done
jaeger_1    | 2023/02/02 06:41:44 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
jaeger_1    | {"level":"info","ts":1675320104.264377,"caller":"flags/service.go:119","msg":"Mounting metrics handler on admin server","route":"/metrics"}
jaeger_1    | {"level":"info","ts":1675320104.2644293,"caller":"flags/service.go:125","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
jaeger_1    | {"level":"info","ts":1675320104.2646875,"caller":"flags/admin.go:129","msg":"Mounting health check on admin server","route":"/"}
jaeger_1    | {"level":"info","ts":1675320104.2647483,"caller":"flags/admin.go:143","msg":"Starting admin HTTP server","http-addr":":14269"}
jaeger_1    | {"level":"info","ts":1675320104.264761,"caller":"flags/admin.go:121","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
jaeger_1    | {"level":"fatal","ts":1675320109.5729213,"caller":"./main.go:109","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available","stacktrace":"main.main.func1\n\t./main.go:109\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t./main.go:240\nruntime.main\n\truntime/proc.go:250"}
demo_jaeger_1 exited with code 1

```
