### DISCUSSION TITLE
Jaeger Query integration with Prometheus on OCP4

### DISCUSSION THREAD

**Discussion by fabry00** [jaegertracing/jaeger#4367] [Q&A] [answered]
Hi

we have configured Opentelemetry collector to send the metrics to Jaeger and Prometheus (deployed at cluster level in OCP - [Configuring the monitoring stack)](https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#enabling-query-logging-for-thanos-querier_configuring-the-monitoring-stack) to scrape the metrics of the Opentelemry collector:

otel-collector.yaml 
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679  

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"    
  jaeger:
    endpoint: http://jaeger.mynamespace.svc.cluster.local:14250
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
```

ServiceMonitor.yaml
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  ......
spec:
  endpoints:
  - interval: 10s
    port: metrics
    scheme: http
  - interval: 10s
    port: otel-metrics
    scheme: http
 ......
  selector:
    matchLabels:
      component: otel-collector
```

In the otel-collector I can see that Prometheus is scraping the logs:

`2023-04-05T06:03:57.182Z	debug	prometheusexporter@v0.74.0/accumulator.go:279	Accumulator collect called	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}`

and I can query in OCP Observe the metrics with PromQL. e.g: otelcol_process_uptime

Now I would like to configure jaeger query to get the metrics from Prometheus:

Jaeger env variables:
```yaml
env:
          - name: COLLECTOR_OTLP_ENABLED
            value: "true"
          - name: MEMORY_MAX_TRACES
            value: {{ .Values.traces.memory.max | quote }}
          - name: METRICS_STORAGE_TYPE
            value: "prometheus"
          - name: PROMETHEUS_SERVER_URL
            value: "https://thanos-querier.openshift-monitoring.svc:9091"
          - name: PROMETHEUS_TLS_ENABLED
            value: "true"
          - name: PROMETHEUS_TLS_SKIP_HOST_VERIFY
            value: "true"
```

What I am missing is how to configure the barer token for thanos authentication in Jaeger Query (https://thanos-querier.openshift-monitoring.svc:9091) because now I can see in the Jaeger logs:

`"level":"error","ts":1680674889.211048,"caller":"app/http_handler.go:494","msg":"HTTP handler, Internal Server Error","error":"failed executing metrics query: client_error: client error: 403"`

thank you in advance
