### DISCUSSION TITLE
Why is this path not excluded from the tracing

### DISCUSSION THREAD

**Discussion by jeroenjacobs79** [jaegertracing/jaeger#4404] [Q&A]
We have SpringBoot applications that have an actuator running on port 8081 on path `/actuator/health`. I want to exclude those from Jaeger tracing, so I tried the following config:

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-production
  namespace: istio-system-upgrade
spec:
  allInOne:
    config: {}
    metricsStorage: {}
    options: {}
    resources: {}
  resources:
    limits:
      cpu: 250m
      memory: 200Mi
    requests:
      cpu: 20m
      memory: 128Mi
  agent:
    config: {}
    options: {}
    resources: {}
  sampling:
    options:
      default_strategy:
        operation_strategies:
          - operation: /actuator/health
            param: 0
            type: probabilistic
        param: 1
        type: probabilistic
  query:
    metricsStorage: {}
    options: {}
    resources: {}
  collector:
    config: {}
    kafkaSecretName: ''
    options:
      sampling:
        strategies-reload-interval: 30s
    resources: {}
  ingester:
    config: {}
    kafkaSecretName: ''
    options: {}
    resources: {}
  strategy: production
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      name: elasticsearch
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 10Gi
        requests:
          cpu: 250m
          memory: 8Gi
      storage:
        size: 200Gi
        storageClassName: ssd-3800g
    esIndexCleaner:
      enabled: true
      numberOfDays: 2
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    grpcPlugin: {}
    options: {}
    type: elasticsearch

```

Aas you can see, the sampling rate is set to 0 for `/actuator/health`, but still they show up in the tracing. What am I missing? Do I have to include the port number in the strategy in some way?

Also, are wildcards supported? I want to exclude everything from the actuator endpoint, so can I use `/actuator/*` in the strategy pattern?

Thanks.
