### DISCUSSION TITLE
How to customize cassandra port with spark-dependencies

### DISCUSSION THREAD

**Discussion by jay-annapureddy** [jaegertracing/jaeger#4610] [Q&A]
Hi,
I used Jaeger operator and installed Jaeger components using production strategy. Jaeger Collector and UI are working fine.
 In the background Jaeger operator also installed spark-dependencies (is enabled by default) and taken Cassandra storage connection details. By default it is connecting to 9042 port, how to customize it to use 10350 ( it is a port opened on azure cosmos db cassandra api)

Any help on how to pass on port information to spark-dependencies ?

**Comment by jay-annapureddy** [comment]
Hi @yurishkuro @pavolloffay 

Any help?

Attached here the 

- output of k get cronjob.batch/jaeger-spark-dependencies -o yaml
- jaeger-prod deployment file

[spark-dependencies.txt](https://github.com/jaegertracing/jaeger/files/12237384/spark-dependencies.txt)
[jaeger-prod.txt](https://github.com/jaegertracing/jaeger/files/12237410/jaeger-prod.txt)

**Comment by jay-annapureddy** [comment]
@jpkrohling, @yurishkuro, @pavolloffay, any help on this ?

I managed to pass on the port to "spark-dependencies" cron job just by postfix the port number to servers

```
  storage:
    type: cassandra
    options:
      cassandra:
        servers: coscas-dejt-jaeger-tst-001.cassandra.cosmos.azure.com:10350
        port: 10350
        username: coscas-dejt-jaeger-tst-001
        password: removed
        keyspace: jaeger_keyspace
        connect-timeout: 60s
        tls:
          enabled: true
          skip-host-verify: true
```

BUT it is ignoring tls configuration, like enabled and skipping host verification, does this spark-dependencies support tls for cassandra storage ?

https://github.com/jaegertracing/jaeger-operator/blob/58f91556e182a4fd929f1abbd0522b1e560e51b3/pkg/cronjob/spark_dependencies.go#L167-L183

![image](https://github.com/jaegertracing/jaeger/assets/109361008/0a052cba-315e-487b-bd29-80a0b6904d5e)
