### DISCUSSION TITLE
How to configure OTLP CORS in docker container

### DISCUSSION THREAD

**Discussion by dirthsj** [jaegertracing/jaeger#4691] [Q&A] [answered]
I'm using the following `compose.yml`:

```
services:
  logs:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_CORS_ALLOWED_ORIGINS=*
    ports:
      - 16686:16686 # web ui
      - 4317:4317   # OTLP (gRPC)
      - 4318:4318   # OTLP (http)
```

with `docker compose up`

Which I believe *should* allow all origins using CORS. However, I still get CORS errors when attempting to POST to the OTLP endpoint in the browser.
