### DISCUSSION TITLE
Jaeger Collector cli flag cassandra.index.logs: false isnt working

### DISCUSSION THREAD

**Discussion by jay-annapureddy** [jaegertracing/jaeger#4901] [Q&A] [answered]
Hi,
I am using Jaeger collector **1.50** version with azure cosmosdb **cassandra api** and using couple of cli flags not to persist the span tags but it isnt working as i see those tags on the Jaeger UI, could you please help what is wrong here ?

I followed this guide https://grafana.com/blog/2020/07/30/how-to-maximize-span-ingestion-while-limiting-writes-per-second-to-a-scylla-backend-with-jaeger-tracing/ but it isnt working, see my deployment file below and suggest

--cassandra.index.logs
Controls log field indexing. Set to false to disable.
--cassandra.index.process-tags
Controls process tag indexing. Set to false to disable.
--cassandra.index.tag-blacklist
The comma-separated list of span tags to blacklist from being indexed. All other tags will be indexed. Mutually exclusive with the whitelist option.
--cassandra.index.tag-whitelist	
The comma-separated list of span tags to whitelist for being indexed. All other tags will not be indexed. Mutually exclusive with the blacklist 
option.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: dejt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/port: "14269"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: jaeger-collector
          image: '#{DOCKER_REGISTRY_URL}#/#{JAEGER_REPOSITORY_NAME}#:#{JAEGER_VERSION}#'
          ports:
            - containerPort: 9411 # Default endpoint for Zipkin receiver.
            - containerPort: 4317 # Default endpoint for OpenTelemetry receiver gRPC.
            - containerPort: 4318 # Default endpoint for OpenTelemetry receiver HTTP.
            - containerPort: 14269 # Default endpoint for metrics.
          env:
            - name: LOG_LEVEL
              value: 'debug'
            - name: COLLECTOR_OTLP_ENABLED
              value: 'true'
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: '9411'
            - name: COLLECTOR_QUEUE_SIZE
              value: '10000'
            - name: SPAN_STORAGE_TYPE
              value: cassandra
            - name: CASSANDRA_SERVERS
              value: '#{CASSANDRA_SERVER}#'
            - name: CASSANDRA_PORT
              value: '#{CASSANDRA_PORT}#'
            - name: CASSANDRA_USERNAME
              value: '#{CASSANDRA_USERNAME}#'
            - name: CASSANDRA_PASSWORD
              value: '#{CASSANDRA_PASSWORD}#'
            - name: CASSANDRA_KEYSPACE
              value: '#{CASSANDRA_KEYSPACE}#'
            - name: CASSANDRA_CONNECT_TIMEOUT
              value: '120s'
            - name: CASSANDRA_TLS_ENABLED
              value: 'true'
            - name: CASSANDRA_TLS_SKIP_HOST_VERIFY
              value: 'true'
            - name: CASSANDRA_INDEX_TAG_BLACKLIST
              value: 'client-uuid,span.kind,component,internal.span.format,ip,jaeger.version,sampler.type,sampler.param,http.method'
            - name: CASSANDRA_INDEX_LOGS
              value: 'false'
```
