### DISCUSSION TITLE
Override host on openshift route

### DISCUSSION THREAD

**Discussion by jean2978** [jaegertracing/jaeger#4936] [Q&A]
Hello,

I'm having issues with the jaeger operator on openshift. Is it possible to override the host in the route that jaeger operator automatically creates? 

This is my Jaeger CRD:

I thought the spec.ingress.hosts would do the trick but seems like the host wont update when created. 

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  labels:
    jaegertracing.io/operated-by: openshift-distributed-tracing.jaeger-operator
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  allInOne:
  strategy: allinone
  ui:
    options:
      menu:
        - items:
            - label: Documentation
              url: >-
                https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/distributed_tracing/index
          label: About
        - anchorTarget: _self
          label: Log Out
          url: /oauth/sign_in
  ingress:
    hosts:
      - {{ .Values.host }}
    openshift:
      sar: '{"namespace": "{{ .Values.namespace }}", "resource": "pods", "verb": "get"}'
    security: oauth-proxy
    tls:
      - hosts:
          - {{ .Values.host }}
```

Let me know if further information is required 😀
