### DISCUSSION TITLE
Jaeger with OtelCollector, Error send trace, BLOCK-CONNECT  URL Filtering Bypassed https://jaeger-all-in-one

### DISCUSSION THREAD

**Discussion by brianmolinaspring** [jaegertracing/jaeger#5024] [Q&A]
### What happened?

Hello guys, the issue is that I am trying to get up from my unix server with docker, jaege with otelcollecto, the issue is that I am receiving an error that cannot connect to https://jaeger-all-in-one.

Be careful, my jaeger is not configured for https, I want it only for http, in a non-productive environment what I don't understand is why it is redirected to https.

I am using this
yaml jaeger:
```yaml
version: "2"
services:

 # Jaeger
 jaeger-all-in-one:
   image: jaegertracing/all-in-one:1.41.0
   ports:
     - "16686:16686"
     - "14268:14268"
     - "14250:14250"
   volumes:
     - /logs/jaeger:/logs/jaeger
   environment:
     - BADGER_DIRECTORY_KEY=/logs/jaeger/key
     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
     - SPAN_STORAGE_TYPE=badger
     - BADGER_EPHEMERAL=false
     - BADGER_DIRECTORY_VALUE=/logs/jaeger/data
     - COLLECTOR_OTLP_ENABLED=true
 # Collector
 otel-collector:
   image: otel/opentelemetry-collector:0.52.0
   command: ["--config=/etc/otel-collector-config.yaml"]
   volumes:
     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:Z
   ports:
     - "13133:13133" # Health_check extension
     - "4317:4317"  # OTLP gRPC receiver
   depends_on:
     - jaeger-all-in-one
```
     
     
     yaml otel
     
```yaml
     receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
      insecure_skip_verify: true
processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
      
      
      como puede visualiza en el yaml de otel tengo esto:
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
      insecure_skip_verify: true
```
As you can see in the otel yaml I have this:
```yaml
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
      insecure_skip_verify: true
```

where you see everything is insecure, but still you don't take it. it redirects it, this only happens in linux, I tested it in docker desktop and it works, I don't know if it is a restriction of the server or the image as such, what do you recommend, some restart of docker or something to implement on the server in the container logs from jaeger I see this

>This Page Cannot Be Displayed</h1>\\\\n\\\\n\\\\n<p>\\\\nThe host name resolution (DNS lookup) for this host name\\\\n(&nbsp;&nbsp;) has failed. The Internet address may be misspelled or obsolete,\\\\nthe host (&nbsp;&nbsp;) may be temporarily unavailable,\\\\nor the DNS server may be unresponsive.\\\\n</p>\\\\n\\\\n<p>\\\\nPlease check the spelling of the Internet address entered.\\\\nIf it is correct, try this request later.\\\\n</p>\\\\n\\\\n\\\\n\\\\n<p>\\\\nIf you have questions, please contact\\\\nyour organization's network administrator \\\\nand provide the codes shown below

URL: CONNECT https:///<br />\\\\nCategory: URL Filtering Bypassed<br />\\\\nReason: UNKNOWN<br />\\\\nNotification: DNS_FAIL

### Steps to reproduce

Configurate yaml

### Expected behavior

error

### Operating system

Linux

### Deployment model

Docker
