### DISCUSSION TITLE
Unable to do Cassandra Schema Migration with MODE=prod

### DISCUSSION THREAD

**Discussion by rmscoal** [jaegertracing/jaeger#5070] [Q&A] [answered]
I am trying to store my jaeger traces in Cassandra. Hence I have this docker compose file:

```yaml

  # Jaeger
  jaeger:
    container_name: moilerplate_jaeger
    image: jaegertracing/all-in-one:1.41.0
    environment:
      - SPAN_STORAGE_TYPE=cassandra
      - CASSANDRA_SERVERS=cassandra
      - CASSANDRA_KEYSPACE=jaeger_v1_dc1
    ports:
      - "14250:14250" # Collector gRPC
      - "16686:16686" # Web HTTP
    networks:
      - moilerplate-network
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-schema:
        condition: service_completed_successfully

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema:1.43
    container_name: moilerplate_cassandra_schema
    environment:
      - CASSANDRA_PROTOCOL_VERSION=4
      - CASSANDRA_VERSION=4
      - CQLSH_HOST=cassandra
      - DATACENTER=dc1
      - MODE=prod
      - REPLICATION_FACTOR=3
    networks:
      - moilerplate-network
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra:
    restart: always
    image: cassandra:4.0
    container_name: moilerplate_cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - moilerplate-network
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 1s
      retries: 120
      timeout: 1s
```

However when I ran it, I got this error message from `jaeger-cassandra-schema` container:
`<stdin>:157:InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'jaeger_v1_dc1' doesn't exist"`

Is there something that I am missing. Is `MODE=prod` unable to create the keyspace? Should I create the keyspace manually?

NOTE: Using `MODE=test` works perfectly fine.

Thanks, any help is wonderful.
