### DISCUSSION TITLE
Jaeger with ElasticSearch 8 as a storage error

### DISCUSSION THREAD

**Discussion by therus000** [jaegertracing/jaeger#5156] [Q&A] [answered]
Good day
finally i got connect to elastic 8

but now i got this error in query

"{"level":"error","ts":1706616890.9132898,"caller":"app/http_handler.go:492","msg":"HTTP handler, Internal Server Error","error":"search operations failed: elastic: Error 400 (Bad Request): all shards failed [type=search_phase_execution_exception]","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).handleError\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:492\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).getOperationsLegacy\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:185\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).handleFunc.traceResponseHandler.func2\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/http_handler.go:536\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*APIHandler).handleFunc.WithRouteTag.func3\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:285\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:229\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:81\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.8.1/mux.go:212\ngithub.com/jaegertracing/jaeger/cmd/query/app.createHTTPServer.additionalHeadersHandler.func4\n\tgithub.com/jaegertracing/jaeger/cmd/query/app/additional_headers_handler.go:28\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngithub.com/jaegertracing/jaeger/cmd/query/app.createHTTPServer.CompressHandler.CompressHandlerLevel.func6\n\tgithub.com/gorilla/handlers@v1.5.1/compress.go:141\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2136\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.5.1/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2938\nnet/http.(*conn).serve\n\tnet/http/server.go:2009"}"

in elastic  i see two index jaeger-span and jaeger-service

my config of storage is 
        server-urls: 
        username: 
        password: 
        version: 8                                  
        create-index-templates: false               
        tls.skip-host-verify: "true" 

![image](https://github.com/jaegertracing/jaeger/assets/48754322/89517697-58ce-41c1-b19d-ef06b9468d9d)

i tried to add those templates to elastic 
https://github.com/jaegertracing/jaeger/tree/main/plugin/storage/es/mappings/fixtures
but error when add 

may be someone fix this error in elastic 8?

**Comment by therus000** [comment]
i found where is the error

**Reply by yurishkuro** [reply]
you can help the community by posting your findings in case someone else runs into this issue

**Reply by therus000** [reply, marked as answer]
you can add this config to deployment to use ES as a storage, it works for me on ES 8.5.2
```
  storage:
    type: elasticsearch # <1>
    options:
      es:
        server-urls: https://e;asticur:9200 # <2>
        username: elastic
        password: password
        version: 8                                  # Necessary as it doesn't work with 8 yet
        create-index-templates: false               # Necessary as it doesn't work with 8 yet 
        tls.skip-host-verify: "true" 
```
