### DISCUSSION TITLE
Old Traces not visible

### DISCUSSION THREAD

**Discussion by parammamaniaslb** [jaegertracing/jaeger#5723] [Q&A]
I am using Open Telemetry demo app to see how traces are generated. However, when I go to Jaeger UI to look for traces I can only see the recent ones. Older traces either are not visible or get deleted.

<img width="1920" alt="Screenshot 2024-07-09 at 5 33 58 PM" src="https://github.com/jaegertracing/jaeger/assets/175169350/0ebabe1f-450d-474d-9a82-4b67bc296246">

In the above image the lookback is set to 2 days and limit results is set to 1000. We see only 3 traces and the oldest one is 2 mins ago. The app is running since several hours and traces were generated during this time.

are there any configurations that need be done in order to get all the Traces generated for the past 2 Days?

**Comment by dosubot** [comment]
Hey @parammamaniaslb! I'm here to help you with any issues you're experiencing. Let's work together to figure out what's going on with the traces.


Yes, there is a configuration that needs to be done to get all the traces generated for the past 2 days in the Jaeger UI. The default rollover conditions have been changed to 2 days, as mentioned in the changelog:

```md
##### Change default rollover conditions to 2 days ([#1963](https://github.com/jaegertracing/jaeger/pull/1963), [@pavolloffay](https://github.com/pavolloffay))

Change default rollover conditions from 7 days to 2 days.

Given that by default Jaeger uses daily indices and some organizations do not keep data longer than 7 days
the default of 7 days seems unreasonable - it might result in a too big index and
running curator would immediately remove the old index.
```

This means that the default configuration should already be set to retain data for 2 days. Additionally, you need to ensure that the archive feature is enabled in your Jaeger configuration to access historical traces. You can do this by setting `archiveEnabled` to `true` in your configuration file:

```json
{
    "archiveEnabled": true
}
```

Moreover, if you are using the memory storage backend, you can configure the retention period for both the main and archive storage as shown in the `cmd/jaeger/config.yaml` file:

```yaml
service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: memstore
    trace_storage_archive: memstore_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    memory:
      memstore:
        max_traces: 100000
      memstore_archive:
        max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
      http:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore
```

In this configuration, `max_traces` is set to `100000` for both the main and archive storage. Adjust these values as needed to fit your retention requirements <sup>[[1]](https://github.com/jaegertracing/jaeger/blob/main/CHANGELOG.md)</sup><sup>[[2]](https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-ui.json)</sup><sup>[[3]](https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-badger.yaml)</sup><sup>[[4]](https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
