### DISCUSSION TITLE
How to configure the jaeger ui with path based routing

### DISCUSSION THREAD

**Discussion by ghost** [jaegertracing/jaeger#5823] [Q&A]
Hello I have trouble accessing the jaeger UI though my ingress controller.  The issue is that domain/ is taken already so i have to use domain/jaeger. however im getting 500 from my nginx controller. If i port forward the service i dont have issue however that is not a viable long term solution.

here is my ingress resource :

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: query-ingress
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest-query
    app.kubernetes.io/part-of: jaeger
  name: simplest-query
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: $2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-compression: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <obfuscated>
    secretName: ingress-tls
  rules:
  - host: <obfuscated>
    http:
      paths:
      - path: /jaeger(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: simplest-query
            port:
              number: 16686

```

![image](https://github.com/user-attachments/assets/eb3b025a-357b-4c0a-b533-6a74dfdafc6e)

**Comment by dosubot** [comment]
Hello, @Cuwudia! I'm here to help you with your Jaeger UI configuration. Let's tackle this issue together.


To configure the Jaeger UI with path-based routing and avoid the 500 error from your Nginx ingress controller, you need to adjust your Ingress resource. Here is an example configuration that should work for your setup:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: query-ingress
    app.kubernetes.io/instance: simplest
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: simplest-query
    app.kubernetes.io/part-of: jaeger
  name: simplest-query
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-compression: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <obfuscated>
    secretName: ingress-tls
  rules:
  - host: <obfuscated>
    http:
      paths:
      - path: /jaeger(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: simplest-query
            port:
              number: 16686
```

Key changes:
- The `nginx.ingress.kubernetes.io/rewrite-target` annotation is set to `/$2` to correctly rewrite the path.
- The `path` is set to `/jaeger(/|$)(.*)` to match the `/jaeger` prefix and capture the rest of the path.

This configuration should help you access the Jaeger UI at `domain/jaeger` without encountering the 500 error <sup>[[1]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.25/operator.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
