### DISCUSSION TITLE
Jaeger all in one badger local storage

### DISCUSSION THREAD

**Discussion by bishop20012** [jaegertracing/jaeger#5865] [General]
Greetings, I'm running yaeger all-in-one binary on a windows machine, I see there is option of local storage called badger. I don't see that as an option in the yeager binary. How do I set that up? Thanks.

**Comment by dosubot** [comment]
Hey @bishop20012! I'm a bot designed to help with bug fixes, answer questions, and assist with contributions. Feel free to ask me anything while waiting for a human maintainer to join the conversation.


To set up Badger local storage in the Jaeger all-in-one binary on a Windows machine, you need to modify the configuration to specify the directories for Badger storage. Here is an example configuration:

```yaml
service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: some_store
    trace_storage_archive: another_store
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
      some_store:
        badger:
          directory_key: "C:\\path\\to\\jaeger\\keys"
          directory_value: "C:\\path\\to\\jaeger\\values"
          ephemeral: false
      another_store:
        badger:
          directory_key: "C:\\path\\to\\jaeger_archive\\keys"
          directory_value: "C:\\path\\to\\jaeger_archive\\values"
          ephemeral: false

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_store
```

Replace `C:\\path\\to\\jaeger\\keys`, `C:\\path\\to\\jaeger\\values`, `C:\\path\\to\\jaeger_archive\\keys`, and `C:\\path\\to\\jaeger_archive\\values` with the actual paths where you want to store the Badger data on your Windows machine. Ensure that the `ephemeral` setting is set to `false` to persist the data.

You can also use the following command-line options to configure Badger storage directly:

- `--badger.directory-key="C:\\path\\to\\jaeger\\keys"`
- `--badger.directory-value="C:\\path\\to\\jaeger\\values"`
- `--badger.ephemeral=false`

These options can be added when running the Jaeger all-in-one binary to specify the storage directories and ensure data persistence <sup>[[1]](https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-badger.yaml)</sup><sup>[[2]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.48/jaeger-all-in-one-badger.yaml)</sup><sup>[[3]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.44/jaeger-all-in-one-badger.yaml)</sup><sup>[[4]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.53/jaeger-all-in-one-badger.yaml)</sup><sup>[[5]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.41/jaeger-all-in-one-badger.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by bishop20012** [reply]
I don't see these options availible in the yaeger all in  one binary 

--badger.directory-key
--badger.directory-value
--badger.ephemeral

**Reply by dosubot** [reply]
The options `--badger.directory-key`, `--badger.directory-value`, and `--badger.ephemeral` are indeed available for configuration in the Jaeger all-in-one binary. These options are used to configure various aspects of the Badger storage backend.

- `--badger.directory-key`: Path to store the keys (indexes), this directory should reside in SSD disk. Set ephemeral to false if you want to define this setting.
- `--badger.directory-value`: Path to store the values (spans). Set ephemeral to false if you want to define this setting.
- `--badger.ephemeral`: Mark this storage ephemeral, data is stored in tmpfs.

If you do not see these options, ensure you are using a version of the Jaeger all-in-one binary that includes the Badger storage plugin. The default configuration might use an in-memory database, so you may need to explicitly set these options in your configuration or command-line flags <sup>[[1]](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/badger/options_test.go)</sup><sup>[[2]](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/badger/options.go)</sup><sup>[[3]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.53/jaeger-all-in-one-badger.yaml)</sup><sup>[[4]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.41/jaeger-all-in-one-badger.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by bishop20012** [comment]
I'm using 1.60.0 and i don't see these options.

**Reply by dosubot** [reply]
The options `--badger.directory-key`, `--badger.directory-value`, and `--badger.ephemeral` are indeed present in the Jaeger all-in-one binary version 1.60.0. Here are the relevant entries from the documentation:

- `--badger.directory-key`: 
  ```yaml
  - name: badger.directory-key
    default_value: /go/bin/data/keys
    usage: |
      Path to store the keys (indexes), this directory should reside in SSD disk. Set ephemeral to false if you want to define this setting.
  ```

- `--badger.directory-value`: 
  ```yaml
  - name: badger.directory-value
    default_value: /go/bin/data/values
    usage: |
      Path to store the values (spans). Set ephemeral to false if you want to define this setting.
  ```

- `--badger.ephemeral`: 
  ```yaml
  - name: badger.ephemeral
    default_value: "true"
    usage: Mark this storage ephemeral, data is stored in tmpfs.
  ```

Additionally, the source code in `plugin/storage/badger/options.go` confirms the presence and functionality of these options <sup>[[1]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.16/jaeger-all-in-one-badger.yaml)</sup><sup>[[2]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.60/jaeger-all-in-one-badger.yaml)</sup><sup>[[3]](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/badger/options_test.go)</sup><sup>[[4]](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/badger/options.go)</sup>.

If you are not seeing these options, it might be due to an issue with the specific binary you are using or how you are invoking the help command. Ensure you are using the correct version and try running the help command again:

```sh
jaeger-all-in-one --help
```



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
