### DISCUSSION TITLE
kubernetes deployment of jager with clickhouse

### DISCUSSION THREAD

**Discussion by AshishM-Protean** [jaegertracing/jaeger#5948] [Q&A]
I need help for this deployment can we have any document for this

**Comment by dosubot** [comment]
Hey @AshishM-Protean! I'm here to help you with your Kubernetes deployment of Jager with ClickHouse. I can assist you with bugs, questions, and becoming a contributor. Let's tackle this together!


I found a similar unsolved discussion on deploying Jaeger with ClickHouse on Kubernetes: [Jaeger with Clickhouse](https://github.com/orgs/jaegertracing/discussions/5542) <sup>[[1]](https://github.com/orgs/jaegertracing/discussions/5542)</sup>.

To deploy Jaeger with ClickHouse on Kubernetes, you can use the Jaeger Operator. Here are some useful resources:

1. [Jaeger Operator for Kubernetes](https://github.com/jaegertracing/jaeger-operator#getting-started)
2. [ClickHouse integration](https://github.com/jaegertracing/jaeger-clickhouse)
3. [Jaeger Deployment Documentation](https://www.jaegertracing.io/docs/1.60/deployment/) <sup>[[2]](https://github.com/jaegertracing/jaeger/blob/main/README.md)</sup><sup>[[3]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.60/deployment.md)</sup>.

Additionally, the Jaeger documentation provides specific guidelines and an example for deploying Jaeger with ClickHouse on Kubernetes:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: clickhouse-grpc-plugin
spec:
  strategy: allInOne
  storage:
    type: grpc-plugin
    grpcPlugin:
      image: ghcr.io/pavolloffay/jaeger-clickhouse:0.5.1
    options:
      grpc-storage-plugin:
        binary: /plugin/jaeger-clickhouse
        configuration-file: /plugin-config/config.yaml
        log-level: debug
  volumeMounts:
    - name: plugin-config
      mountPath: /plugin-config
  volumes:
    - name: plugin-config
      configMap:
        name: jaeger-clickhouse
```

Refer to [jaeger-clickhouse](https://github.com/pavolloffay/jaeger-clickhouse) for documentation and a fully functional example <sup>[[4]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.41/operator.md)</sup><sup>[[5]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.46/operator.md)</sup><sup>[[6]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.42/operator.md)</sup>.

These resources should help you get started with deploying Jaeger with ClickHouse on Kubernetes.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
