### DISCUSSION TITLE
How to Migrate Jaeger from Agent to Collector (OTLP) as DaemonSet?

### DISCUSSION THREAD

**Discussion by eilaytal** [jaegertracing/jaeger#6106] [Q&A]
Hi all,

I’m using Jaeger with the agent running as a **DaemonSet** to collect traces from each node and forward them to the collector. Here's my current config:

```yaml
agent:
  enabled: true
  strategy: DaemonSet
  service:
    binaryPort: 6832
    compactPort: 6831
    samplingPort: 5778
  env:
    - name: COLLECTOR_SERVICE_HOST
      value: "jaeger-collector.jaeger.svc.cluster.local"
    - name: COLLECTOR_SERVICE_PORT_GRPC
      value: "14250"

collector:
  enabled: true
  service:
    grpc:
      port: 14250
    http:
      port: 14268

storage:
  type: elasticsearch  # This points to my OpenSearch backend
```

Since the agent may be deprecated, I’m looking to **migrate to a collector-only setup** (using OTLP) as a **DaemonSet**.

- How can I update my config to achieve this migration?
- Are there any potential issues to be aware of?

Thanks in advance!

**Comment by dosubot** [comment]
Hey there, @eilaytal! I'm here to assist you with any bugs, questions, or contributions you have. Let's tackle this migration together!


To migrate from a Jaeger Agent to a Collector-only setup using OTLP as a DaemonSet, you'll need to update your configuration and be aware of some potential issues.

### Configuration Update

1. **Remove the Agent Configuration**: Since you're moving to a Collector-only setup, you can remove the agent configuration from your setup.

2. **Configure the Collector to Use OTLP**: Update your collector configuration to receive data via the OTLP protocol. Here's an example configuration:

   ```yaml
   collector:
     enabled: true
     strategy: DaemonSet
     service:
       grpc:
         port: 4317  # Default gRPC port for OTLP
       http:
         port: 4318  # Default HTTP port for OTLP
     env:
       - name: SPAN_STORAGE_TYPE
         value: "elasticsearch"  # Ensure this matches your OpenSearch setup
   ```

3. **Update Application Configuration**: Ensure your applications are configured to send traces directly to the Jaeger Collector using the OTLP protocol. This typically involves setting the OTLP endpoint in your application's tracing configuration.

### Potential Issues

1. **Configuration Complexity**: Without the Jaeger Agent, each application needs to be configured with the Collector's endpoint, which can add complexity, especially in multi-region setups.

2. **Lack of Local Proxy**: The Jaeger Agent acts as a local proxy, simplifying configuration. Without it, each application must be configured individually to communicate with the Collector.

3. **Traffic Management**: The Agent helps manage traffic to the Collectors by load balancing and reducing the number of open connections. Without it, there might be too many open connections for each Collector to handle, especially in environments with many hosts and applications.

4. **Metadata Enrichment**: The Agent can enrich tracing data with infrastructure-specific metadata. This functionality might be lost or require additional setup when using a Collector-only setup.

5. **Additional Functionality**: Features like strong authentication and multi-tenancy provided by the Agent might need alternative solutions in a Collector-only setup.

If these functionalities are required, consider deploying an OpenTelemetry Collector as a host agent <sup>[[1]](https://github.com/jaegertracing/documentation/blob/main/content/docs/next-release/faq.md)</sup><sup>[[2]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.28/faq.md)</sup>.

By addressing these configuration changes and potential issues, you can successfully migrate to a Collector-only setup using OTLP as a DaemonSet.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by eilaytal** [comment]
---

 @dosu I've updated my configuration as follows:

```yaml
agent:
  enabled: false

collector:
  enabled: true
  strategy: DaemonSet
  image:
    repository: jaegertracing/jaeger-collector
  service:
    type: ClusterIP
    otlp:
      grpc:
        port: 4317
        name: otlp-grpc
      http:
        port: 4318
        name: otlp-http
```

However, the collector is not deploying as a DaemonSet. Could you provide any insights on what I might be missing? I appreciate your help!

**Reply by dosubot** [reply]
If your Jaeger Collector is not deploying as a DaemonSet, here are a few things to check:

1. **Kubernetes DaemonSet Configuration**: Ensure that your Kubernetes manifest specifies the `kind: DaemonSet` for the Jaeger Collector. Here's a basic example:

   ```yaml
   apiVersion: apps/v1
   kind: DaemonSet
   metadata:
     name: jaeger-collector
     namespace: jaeger
   spec:
     selector:
       matchLabels:
         app: jaeger-collector
     template:
       metadata:
         labels:
           app: jaeger-collector
       spec:
         containers:
         - name: jaeger-collector
           image: jaegertracing/jaeger-collector
           ports:
           - containerPort: 4317
             name: otlp-grpc
           - containerPort: 4318
             name: otlp-http
   ```

2. **Check Logs and Events**: Use `kubectl logs` and `kubectl describe` to check for any errors or events related to the DaemonSet. This can provide insights into why the DaemonSet might not be deploying correctly.

3. **Resource Quotas and Limits**: Ensure that there are no resource quotas or limits in your namespace that might prevent the DaemonSet from being scheduled on all nodes.

4. **Node Selectors and Tolerations**: Verify if there are any node selectors or tolerations required for the DaemonSet to be scheduled on the nodes.

5. **Network Policies**: Check if there are any network policies that might be preventing the Collector from communicating with other services or nodes.

By reviewing these aspects, you should be able to identify and resolve the issue preventing the Jaeger Collector from deploying as a DaemonSet.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
