### DISCUSSION TITLE
Connecting to AWS OpenSearch with ARN

### DISCUSSION THREAD

**Discussion by wmashal** [jaegertracing/jaeger#6169] [Q&A]
Hi,

Are there any examples demonstrating how to connect to AWS OpenSearch using an ARN instead of a username and password?

In our deployments, we typically connect pods to AWS services by creating a Role and RoleBinding with a master user ARN.

However, in the Jaeger production strategy and Elasticsearch storage configurations, I only see options for username and password authentication.

Could you please provide guidance or examples on how to use ARN-based authentication for OpenSearch connections in Jaeger?

If I am creating service account with the ARN the refrence it in the configurations like the following ? it works ?
```yaml
  jaeger:
    spec:
      strategy: production    # Change to production strategy instead of allInOne
      collector:
        serviceAccount: jaeger-collector
        options:
          log-level: info
        annotations:
          sidecar.istio.io/inject: "true"
      query:
        serviceAccount: jaeger-collector 
        options:
          log-level: info
        annotations:
          sidecar.istio.io/inject: "true"
      ingester:
        serviceAccount: jaeger-collector
        options:
          log-level: info
        annotations:
          sidecar.istio.io/inject: "true"
      storage:
        type: elasticsearch
        options:
          es:
            log-level: info
            server-urls: https://<domain> 
            usePassword: false
            nodesWanOnly: false
            tls:
              skip-host-verify: true

```

Thanks!
