### DISCUSSION TITLE
How to limit file size when using Jaeger-all-in-one and Badger in docker composer

### DISCUSSION THREAD

**Discussion by fernando-viegas** [jaegertracing/jaeger#6250] [Q&A]
I have a docker compose file that runs a Jaeger + Badger with disk storage:

```
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "4317:4317"
      - "16686:16686"
      - "14268:14268"
      - "14269:14269"
      - "14250:14250"
    environment:
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger_data
      - BADGER_DIRECTORY_KEY=/badger_data
      - BADGER_MAINTENANCE_INTERVAL=24h
      - BADGER_SPAN_STORE_TTL=120h
      - BADGER_TRUNCATE=true
    volumes:
      - ./jaeger:/badger_data
    mem_limit: "512M"
    mem_reservation: "512M"
```

It is mandatory that I set the file size to control disk space. I have searched a lot to find a solution, but no information!

I would really appreciate solutions to solve this problem.
