### DISCUSSION TITLE
Can't see latest version of jaeger in helm search

### DISCUSSION THREAD

**Discussion by andytael** [jaegertracing/jaeger#6592] [Q&A]
After install them jaeger helm chart using `helm repo add jaegertracing https://jaegertracing.github.io/helm-charts` I search the repo using `helm search repo jaegertracing/jaeger` and I only get this:

```
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION
jaegertracing/jaeger         	3.3.4        	1.53.0     	A Jaeger Helm chart for Kubernetes
jaegertracing/jaeger-operator	2.57.0       	1.61.0     	jaeger-operator Helm chart for Kubernetes
```

I was expecting a lot later version of jaeger and the helm chart. I tried executing `helm repo update` but no difference.

I'm looking for version 1.65 or 2.2.

Any idea what I'm doing wrong?

**Comment by paulDashkevich** [comment]
```
    chart: jaeger-operator
    helm:
      values: |-
        image:
          repository: jaegertracing/jaeger-operator
          tag: 1.65.0    <<<< Provide the tag in values.yaml
```
