### DISCUSSION TITLE
Jaeger v2 docker image configuration

### DISCUSSION THREAD

**Discussion by vvuk** [jaegertracing/jaeger#6623] [Q&A]
I could just be missing it, but I can't find anywhere in the documentation about how to actually provide a configuration file to the jaeger v2 docker container. (The docs don't even seem to give information where the config file lives or is passed in.)

This is me trying to set QUERY_BASE_PATH (which doesn't seem to work via env var any more?). Any suggestions?

**Comment by dosubot** [comment]
Hey @vvuk 👋, I'm here to assist you with any bugs, questions, or contributions you have. Let's tackle this together!


To provide a configuration file to the Jaeger v2 Docker container and set `QUERY_BASE_PATH`, you need to mount a configuration file into the container. The default location for configuration files in the Jaeger v2 Docker container is `/etc/jaeger/` <sup>[[1]](https://github.com/orgs/jaegertracing/discussions/6558)</sup>.

Here's how you can modify your Docker Compose file to include a volume that mounts your configuration file into the container:

```yaml
services:
  jaeger:
    image: docker-release.repo.XXX.cz/jaegertracing/jaeger:2.0.0
    container_name: jaeger
    hostname: jaeger  
    ports: ['14268:14268', '14269:14269', '14250:14250', '4318:4318', '4317:4317', '16686:16686', '16687:16687', '16685:16685']
    restart: 'unless-stopped'
    environment:
      SPAN_STORAGE_TYPE: 'elasticsearch'
    volumes:
      - '/var/opt/jaeger:/var/opt/jaeger'
      - './jaeger-config.yaml:/etc/jaeger/jaeger-config.yaml'  # Mount your config file
```

Ensure that your `jaeger-config.yaml` file is correctly formatted and includes the necessary configuration for `query.base-path`. You can specify the `query.base-path` option in your configuration file like this:

```yaml
query:
  base-path: /your/base/path
```

This setup should allow you to configure the `QUERY_BASE_PATH` using a configuration file. For more details on the configuration file format and options, you can refer to Jaeger's official documentation <sup>[[2]](https://github.com/orgs/jaegertracing/discussions/6548)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/5dcaf886-1e2e-47f4-afa6-6adf34c431c5?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/5dcaf886-1e2e-47f4-afa6-6adf34c431c5?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/5dcaf886-1e2e-47f4-afa6-6adf34c431c5?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/5dcaf886-1e2e-47f4-afa6-6adf34c431c5?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/5dcaf886-1e2e-47f4-afa6-6adf34c431c5?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/5dcaf886-1e2e-47f4-afa6-6adf34c431c5?feedback_type=other)</sup>
