### DISCUSSION TITLE
Proper way to run v2 separately as collector and query

### DISCUSSION THREAD

**Discussion by ABAG603** [jaegertracing/jaeger#6682] [Q&A] [answered]
As stated in the title, what is the proper way to run Jaeger v2 only in query mode? I mostly interested in the correct configuration. My assumption was that I just leave **jaeger_storage** and **jaeger_query** as extensions and won't specify any **receivers**, **processors** and **exporters** but such config is considered as invalid:

Getting something like
```
Error: invalid configuration: no receiver configuration specified in config
```
or 
```
Error: invalid configuration: no exporter configuration specified in config
```

But the whole OTEL pipeline is not needed at all for the Jeager UI, in my undestanding.

**Comment by dosubot** [comment]
Hey there, @ABAG603! I'm here to help you with any bugs, questions, or contributions. Let's tackle this together while we wait for a human maintainer.


To run Jaeger v2 in query mode only, you need to ensure that the configuration includes the necessary components for the `jaeger_query` extension, which handles the query APIs and UI frontend. The error messages you're encountering suggest that the configuration is expecting certain components that are not needed for query mode.

For a valid configuration in query mode, focus on setting up the `jaeger_storage` and `jaeger_query` extensions without specifying receivers, processors, or exporters. The `jaeger_storage` extension should be configured with at least one trace storage backend, as this is required for the query service to function properly. The `jaeger_query` extension should reference this storage backend to access trace data.

Here's a simplified example of what the configuration might look like:

```yaml
extensions:
  jaeger_storage:
    backends:
      some_storage:
        type: memory
        memory:
          max_traces: 100000

  jaeger_query:
    traces_storage: some_storage
    grpc_server:
      endpoint: ":16685"
    http_server:
      endpoint: ":16686"
```

Ensure that the `jaeger_storage` extension is properly configured with a storage backend, and the `jaeger_query` extension is set to use this backend. This setup should allow you to run Jaeger in query mode without needing the OTEL pipeline components like receivers, processors, or exporters <sup>[[1]](https://github.com/jaegertracing/documentation/blob/main/content/docs/next-release-v2/configuration.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/c2a1720d-bb01-4e7b-b3c5-f369e6eb635c?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/c2a1720d-bb01-4e7b-b3c5-f369e6eb635c?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/c2a1720d-bb01-4e7b-b3c5-f369e6eb635c?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/c2a1720d-bb01-4e7b-b3c5-f369e6eb635c?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/c2a1720d-bb01-4e7b-b3c5-f369e6eb635c?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/c2a1720d-bb01-4e7b-b3c5-f369e6eb635c?feedback_type=other)</sup>

**Reply by ABAG603** [reply]
I use same config and it doesn't work. It would be great to see a reply from a real person. @yurishkuro could you please clarify how to run v2 in just query mode?

**Reply by yurishkuro** [reply]
OTEL Collector has `nop` receiver and exporter, but we did not include them in the Jaeger binary, an oversight. https://github.com/jaegertracing/jaeger/issues/6683

**Reply by yurishkuro** [reply, marked as answer]
For now you would have to run query like a collector, with a real pipeline. Technically you don't even need different configurations between collector/query, just two different clusters for isolation purposes and a routing for the UI for one of them.

**Reply by ABAG603** [reply]
@yurishkuro thanks for the prompt reply.

**Reply by ABAG603** [reply]
@yurishkuro sorry, last one. Do I understand correctly that once #6683 is done, query config will look something like below?
```yaml
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [nop]
      processors: [batch]
      exporters: [nop]
  
extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: opensearch_storage
    ui:
      config_file: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    backends:
     
receivers:
  nop:

processors:
  batch:

exporters:
 nop:
```
