### DISCUSSION TITLE
Jaeger on windows installation working only on localhost

### DISCUSSION THREAD

**Discussion by formentinif** [jaegertracing/jaeger#6690] [Q&A] [answered]
[config.zip](https://github.com/user-attachments/files/18703853/config.zip)
Hello, I have succesfully installed Jaeger v2 on a windows server following the documentation with the config file attached. However the port 4317 is open only on localhost, I'm not able to reach the server port by IP from anoter application server. The UI on 16686 works fine. I wasn't able to find any documentation on how set the ip of the server properly on the configuration file, can anyone help me? Thanks

**Comment by dosubot** [comment]
Hello @formentinif! I'm here to assist you with any bugs, questions, or contributions you may have.


To resolve the issue of Jaeger only being accessible on `localhost`, you need to configure it to listen on all network interfaces. This can be done by setting the host to `0.0.0.0` in your configuration file. Specifically, for the OTLP gRPC receiver, you should set the following environment variable:

```yaml
- COLLECTOR_OTLP_GRPC_HOST_PORT=0.0.0.0:4317
```

This change will allow the port to be accessible from other machines on the network. This is a known issue with Jaeger v2, where the OTLP receivers default to listening on `localhost` instead of `0.0.0.0` <sup>[[1]](https://github.com/jaegertracing/jaeger/blob/main/CHANGELOG.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/b337b7d9-8226-4591-b9e0-890e231e4151?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/b337b7d9-8226-4591-b9e0-890e231e4151?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/b337b7d9-8226-4591-b9e0-890e231e4151?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/b337b7d9-8226-4591-b9e0-890e231e4151?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/b337b7d9-8226-4591-b9e0-890e231e4151?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/b337b7d9-8226-4591-b9e0-890e231e4151?feedback_type=other)</sup>

**Reply by yurishkuro** [reply]
Correct about 0.0.0.0, ignore the part about env var, set it in the config.

**Reply by formentinif** [reply]
> Correct about 0.0.0.0, ignore the part about env var, set it in the config.

Thank for the reply, i'm a bit confused on how to set in the config, could you give me a sample? my config.yaml is:

 
```
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      address: 0.0.0.0:8888
    logs:
      level: debug
 
extensions:
  healthcheckv2:
    use_v2: true
    http:

 
  jaeger_query:
    storage:
      traces: some_store
      traces_archive: another_store
    ui:
      config_file: config-ui.json
    max_clock_skew_adjust: 0s

  jaeger_storage:
    backends:
      some_store:
        badger:
          directories:
            keys: "/Jaeger/data/"
            values: "/Jaeger/data/"
          ephemeral: false
      another_store:
        badger:
          directories:
            keys: "/Jaeger/data_archive/"
            values: "/Jaeger/data_archive/"
          ephemeral: false

receivers:
  otlp:
    protocols:
      grpc:
      http:  
        
  jaeger:
    protocols:
      grpc: 
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin: 

processors:
  batch:
  adaptive_sampling:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_store

```
