### DISCUSSION TITLE
Unable to connect to cosmos db cassandra storage: unable to connect to initial hosts: EOF

### DISCUSSION THREAD

**Discussion by Steve887** [jaegertracing/jaeger#6767] [General]
I'm trying to setup a connection to an Azure Cosmos DB account via the Cassandra API. I think I have the config setup correctly, although it's difficult to tell, but when my Jaeger app starts up I get the following error in the console:

> failed to start extensions: failed to initialize storage 'cassandra_storage': gocql: unable to create session: unable to connect to initial hosts: EOF

My storage config is as follows:

```
  jaeger_storage:
    backends:
      cassandra_storage:
        cassandra:
          connection:
            servers: '<accountname>.cassandra.cosmos.azure.com'
            port: 10350
            tls:
              insecure: true
            auth: 
              basic:
                username: 'username'
                password: 'password'
          schema:
            create: true
            keyspace: jaeger_dc1
            datacenter: dc1
            trace_ttl: 48h
            #dependencies_ttl: 48d
            compaction_window: 2h
            replication_factor: 1
```

Do I have something wrong in my config, or anything else I can try>
