### DISCUSSION TITLE
cannot run with custom config

### DISCUSSION THREAD

**Discussion by kurkoc** [jaegertracing/jaeger#6777] [Q&A]
maybe I'm asking a very simple question, but this problem has taken me a long time.

i am running a otelcollector and jaeger with same network on docker. (windows machine)

`docker run -d --name jaeger -p 16686:16686 -p 4319:4317 -p 4320:4318 -p 5778:5778 -p 9411:9411 -p 13134:13133 --network tracing-pipeline jaegertracing/jaeger:2.3.0` 

sending traces with telemetrygen and everything looks good. 

but when I change my jager run command I get an error on otelcollector logs. cant find the "jaeger:4317"

`docker run -d --name jaeger -p 16686:16686 -p 4319:4317 -p 4320:4318 -p 5778:5778 -p 9411:9411 -p 13134:13133 -v C:\jaeger\config.yaml:/jaeger/config.yaml --network tracing-pipeline jaegertracing/jaeger:2.3.0 --config /jaeger/config.yaml`

* I changed the ports for host machine to avoid conflicts with otelcollector

Can you write a config for the simplest example in this way? Whatever I did, it didn't work.

```
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: 0.0.0.0:13133

  jaeger_query:
    storage:
      traces: query_storage

  jaeger_storage:
    backends:
      query_storage:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: query_storage
```

**Comment by dosubot** [comment]
Hey @kurkoc! 👋 I'm here to help you out with your issue. I'm a bot designed to assist with bug fixes, answer questions, and guide you on your open source journey.


To resolve the "jaeger:4317" error and ensure your custom configuration works, you need to ensure that the OpenTelemetry Collector and Jaeger are correctly configured to avoid port conflicts and communicate properly. Here's a simplified configuration and setup:

1. **Jaeger Configuration:**
   Ensure that Jaeger is not using port 4317 if it's not needed. Your current setup seems to map port 4317 to 4319 on the host, which should be fine as long as no other service is using 4317 internally.

2. **OpenTelemetry Collector Configuration:**
   Make sure the OpenTelemetry Collector is configured to use the correct ports and endpoints. Here's a simplified configuration based on your provided setup:

```yaml
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: 0.0.0.0:13133

  jaeger_query:
    storage:
      traces: query_storage

  jaeger_storage:
    backends:
      query_storage:
        memory:
          max_traces: 100000

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: query_storage
```

3. **Docker Run Commands:**
   Ensure that the ports are correctly mapped and that the configuration file is correctly mounted. Here's how you can run Jaeger and the OpenTelemetry Collector:

   - **Jaeger:**
     ```sh
     docker run -d --name jaeger \
       -p 16686:16686 \
       -p 4319:4317 \
       -p 4320:4318 \
       -p 5778:5778 \
       -p 9411:9411 \
       -p 13134:13133 \
       -v C:\jaeger\config.yaml:/jaeger/config.yaml \
       --network tracing-pipeline \
       jaegertracing/jaeger:2.3.0 \
       --config /jaeger/config.yaml
     ```

   - **OpenTelemetry Collector:**
     Ensure that the collector is configured to send traces to the correct Jaeger endpoint. If you are using OTLP, make sure the endpoint is set to `jaeger:4318` (or the correct port if changed).

By ensuring that each service uses unique ports and that the configuration files are correctly set up, you should be able to resolve the "jaeger:4317" error and have a working setup <sup>[[1]](https://github.com/jaegertracing/jaeger/blob/main/docker-compose/tail-sampling/docker-compose.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/03d05111-1508-42d5-91b6-e343b36f6161?feedback_type=other)</sup>
