### DISCUSSION TITLE
Run jaeger with docker compose config

### DISCUSSION THREAD

**Discussion by outsinre** [jaegertracing/jaeger#6847] [Q&A]
I am playing with Jaeger with Docker compose, but have a few questions on the config part.

I drafted the Docker compose from Google search. However, I cannot find any information on the `services.jaeger-all-in-one.environment` part.

For example, where is the `COLLECTOR_OTLP_ENABLED` defined? How can I change `LOG_LEVEL` to `debug`. Cannot find the official documentation.

Seems those environment variables are exclusive to Jaeger V1, not V2?

```yaml
name: opentelemetry
services:
  jaeger-all-in-one:
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"
      LOG_LEVEL: info
      SPAN_STORAGE_TYPE: memory
    image: jaegertracing/jaeger:2.4.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 16686
        protocol: tcp
      - mode: ingress
        target: 4317
        protocol: tcp
      - mode: ingress
        target: 4318
        protocol: tcp
      - mode: ingress
        target: 9411
        protocol: tcp
      - mode: ingress
        target: 14269
        protocol: tcp
      - mode: ingress
        target: 13133
        protocol: tcp
  otel-collector:
    depends_on:
      jaeger-all-in-one:
        condition: service_started
        required: true
    environment:
      DD_API_KEY: a1b2c3d4e5
      DD_SITE: datadoghq.com
    image: otel/opentelemetry-collector-contrib:0.121.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 1888
        protocol: tcp
      - mode: ingress
        target: 13133
        protocol: tcp
      - mode: ingress
        target: 55679
        protocol: tcp
      - mode: ingress
        target: 8888
        protocol: tcp
      - mode: ingress
        target: 8889
        protocol: tcp
      - mode: ingress
        target: 4317
        protocol: tcp
      - mode: ingress
        target: 4318
        protocol: tcp
    volumes:
      - type: bind
        source: ./otel-collector-config.yaml
        target: /etc/otelcol-contrib/config.yaml
        bind:
          create_host_path: true
  tracegen:
    command:
      - -duration
      - 5s
      - -workers
      - "3"
      - -pause
      - 250ms
    depends_on:
      jaeger-all-in-one:
        condition: service_started
        required: true
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger-all-in-one:14268/api/traces
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger-all-in-one:4318/v1/traces
    image: jaegertracing/jaeger-tracegen:latest
    networks:
      default: null
```

**Comment by dosubot** [comment]
Hey @outsinre! 👋 I'm here to help you with your Docker compose config for Jaeger while we wait for a human maintainer. Let's dive in and solve this together! 😊


I found some relevant information that might help you with your Docker Compose configuration for Jaeger.

1. **`COLLECTOR_OTLP_ENABLED`**: This environment variable is used to enable the OpenTelemetry Protocol (OTLP) receiver in Jaeger. When set to `true`, it allows Jaeger to receive traces using OTLP over dedicated HTTP and gRPC ports. The default HTTP port is 4318, and the default gRPC port is 4317. This configuration facilitates the integration of Jaeger with OpenTelemetry by allowing it to receive telemetry data using the OTLP standard. The default value for this environment variable is "true" <sup>[[1]](https://github.com/jaegertracing/jaeger/blob/main/cmd/tracegen/docker-compose.yml)</sup><sup>[[2]](https://github.com/jaegertracing/documentation/blob/8fe5a47de7f21e542098465e582cf6caabe6da60/data/cli/1.67/jaeger-all-in-one.yaml#L125-L161)</sup>.

2. **Changing `LOG_LEVEL` to `debug`**: You can change the `LOG_LEVEL` to `debug` by setting it in the environment section of your Docker Compose file. Here is how you can modify your configuration:

   ```yaml
   services:
     jaeger-all-in-one:
       environment:
         COLLECTOR_OTLP_ENABLED: "true"
         COLLECTOR_ZIPKIN_HOST_PORT: "9411"
         LOG_LEVEL: debug
         SPAN_STORAGE_TYPE: memory
       image: jaegertracing/jaeger:2.4.0
       ...
   ```

   You can also set the `log-level` parameter via a command-line flag or configuration file if needed <sup>[[3]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.19/operator.md)</sup><sup>[[4]](https://github.com/jaegertracing/documentation/blob/main/content/docs/1.27/operator.md)</sup>.

If you have further questions or need more detailed examples, feel free to ask!



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/61f21e26-ff42-4c76-b064-750119567f23?feedback_type=other)</sup>
