### DISCUSSION TITLE
TLS issue with elasticsearch backend

### DISCUSSION THREAD

**Discussion by rickraven** [jaegertracing/jaeger#7010] [Q&A]
Hi,
I have jaeger 2.5.0 deployed as a singe file on vm (not docker/k8s). I specified elasticsearch as a backend storage and tried to disable tls checking.
My jaeger.yaml config file:
```yaml
extensions:
  jaeger_storage:
    backends:
      trace_storage:
        elasticsearch:
          server_urls:
            - https://example.com:9200
          auth:
            basic:
              username: user
              password: pass
          tls:
            insecure: true
            insecure_skip_verify: true
```
And after that I still have an issue:
```
failed to initialize trace storage 'trace_storage':  failed to create Elasticsearch client: heath check timeout: tls: failed to verify certificate: x509: certificate has expired or is not yet valid
```
Any ideas why check disabling doesn't work?
