### DISCUSSION TITLE
retry_on_failure for jaeger_storage_exporter

### DISCUSSION THREAD

**Discussion by aujjwal-smarsh** [jaegertracing/jaeger#7105] [Q&A] [answered]
Hello folks,

I am working on deploying Jaeger V2 with OpenTelemetry CRD. The storage backend is Elasticsearch. I have deployed it in my local cluster, and it is working fine. Though I am struggling with one issue. I want to tune the queue size and retry mechanism for exporter failures.

I found that we can set the queue size using 

```
 jaeger_storage_exporter:
        trace_storage: some_storage
        queue:
          enabled: true
          num_consumers: 10
          queue_size: 1000
```

Now, the general [exporterhelper](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md#:~:text=can%20be%20modified%3A-,retry_on_failure,-enabled%20(default%20%3D%20true) provides a mechanism to `retry_on_failure`
```
retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 1m
            max_elapsed_time: 1h
```

But I am not able to find any documentation on Jaeger that shows how to leverage the same in the Jaeger v2 storage backend. 

Appreciate your help, and thanks in advance.
