### DISCUSSION TITLE
How to change span store ttl for Jaeger V2?

### DISCUSSION THREAD

**Discussion by norin-dlkh** [jaegertracing/jaeger#7108] [Q&A]
Hi everyone,
I tried to change span store ttl in jaeger:2.5.0 but it doesn't seem like it's working.

In version 1, we can use `--badger.span-store-ttl` param to adjust to expire of the span. But, for V2, I have follow the migration guide on [google doc ](https://docs.google.com/document/d/1il8WE54BDTZPsVmpaYFXFOsvq7bPukSJPeOBuVcJ15k/edit?tab=t.0#heading=h.qbckwiyz30oe) but it doesn't seem like it's working.

Here is my `config.yml` 
```
...
     jaeger_query:
        storage:
          traces: primary_store
          traces_archive: archive_store
          metrics: metrics_storage
        ui:
          config_file: /jaeger/config-ui.json


      jaeger_storage:
        backends:
          primary_store:
            badger:
              ttl:
                span_store: 720h

              directories:
                keys: "/app/data"
                values: "/app/data"
              ephemeral: false

            memory:
              max_traces: 100000
...
```

I got some error when running with the above configuration;
```
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'extensions': error reading configuration for "jaeger_storage": decoding failed due to the following error(s):

error decoding 'backends[primary_store]': decoding failed due to the following error(s):

'badger.ttl' has invalid keys: span_store
2025/05/09 07:16:24 failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'extensions': error reading configuration for "jaeger_storage": decoding failed due to the following error(s):

error decoding 'backends[primary_store]': decoding failed due to the following error(s):

'badger.ttl' has invalid keys: span_store
``` 

Anyone know how to fix this?

**Comment by dosubot** [comment]
Hey there, @norin-dlkh! I'm [Dosu](https://dosu.dev), your friendly bot here to help you tackle bugs, answer questions, and assist you in becoming a contributor while you wait for a human maintainer. Let's dive into your Jaeger issue! 🤖


To change the span store TTL for Jaeger V2, you should use the `badger.span-store-ttl` configuration option instead of `badger.ttl.span_store`. The correct configuration should look like this:

```yaml
jaeger_storage:
  backends:
    primary_store:
      badger:
        span-store-ttl: 720h

        directories:
          keys: "/app/data"
          values: "/app/data"
        ephemeral: false

      memory:
        max_traces: 100000
```

Make sure to replace `badger.ttl.span_store` with `badger.span-store-ttl` to avoid errors. This configuration sets the TTL to 720 hours, as you intended <sup>[[1]](https://github.com/jaegertracing/documentation/blob/main/data/cli/1.64/jaeger-all-in-one-badger.yaml)</sup>.



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=reply-with-mention&utm_term=jaegertracing%2Fjaeger).*

---

Share context across your team and agents. Try [Dosu](https://dosu.dev?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-tagline&utm_term=jaegertracing%2Fjaeger).

[![Leave Feedback](https://img.shields.io/badge/Leave%20Feedback-555555?style=flat)](https://app.dosu.dev/response-feedback?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-feedback&utm_term=jaegertracing%2Fjaeger#message_id=b4cd2998-31a2-4f88-80ab-c907984b7476) [![Learn about jaeger with Dosu](https://img.shields.io/badge/Learn%20about%20jaeger%20with%20Dosu-2f7b3f?style=flat&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iODYiIGhlaWdodD0iODkiIHZpZXdCb3g9IjAgMCA4NiA4OSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4yOTIzNiAxMi43OTI4TDE3Ljc1OTMgNi42ODE4OFY3Mi41NjY3TDUuMjkyMzYgODQuMDYxOFYxMi43OTI4WiIgZmlsbD0iI0I0QkI5MSIvPjxwYXRoIGQ9Ik0xOC4yNTc1IDczLjExOTZMNTkuMTMyOSA3Mi43NDhMNTEuNzAxMSA4Mi40MDk1TDI5LjAzMzggODYuMjkxTDYuMjM5NjIgODUuMTU1NEwxOC4yNTc1IDczLjExOTZaIiBmaWxsPSIjNzc4NTYxIi8%2BPHBhdGggZD0iTTE3LjQ5MTYgMy43MzYzM0wzLjU4NTU3IDEyLjcwOTlWODMuNTc5MkMzLjU4NTU3IDg0Ljc1NDIgNC45ODU2MyA4NS4zNjUyIDUuODQ3MDUgODQuNTY2TDE5LjYyOTYgNzEuNzgwMSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjQyODQ0IiBzdHJva2UtbGluZWNhcD0icm91bmQiLz48bWFzayBpZD0iZG9zdS1kLWN1dG91dCIgZmlsbD0id2hpdGUiPjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNNDAuNzA0IDAuNTE4MDY2SDE3LjA0MzlWNzYuMjIyMUg0MC43MDRINDIuNTgwNUg0Ny44MDEzQzY4LjcwNjQgNzYuMjIyMSA4NS42NTMzIDU5LjI3NTIgODUuNjUzMyAzOC4zNzAxQzg1LjY1MzMgMTcuNDY1IDY4LjcwNjMgMC41MTgwNjYgNDcuODAxMyAwLjUxODA2Nkg0Mi41ODA1SDQwLjcwNFoiLz48L21hc2s%2BPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00MC43MDQgMC41MTgwNjZIMTcuMDQzOVY3Ni4yMjIxSDQwLjcwNEg0Mi41ODA1SDQ3LjgwMTNDNjguNzA2NCA3Ni4yMjIxIDg1LjY1MzMgNTkuMjc1MiA4NS42NTMzIDM4LjM3MDFDODUuNjUzMyAxNy40NjUgNjguNzA2MyAwLjUxODA2NiA0Ny44MDEzIDAuNTE4MDY2SDQyLjU4MDVINDAuNzA0WiIgZmlsbD0iI0YzRjZGMSIvPjxwYXRoIGQ9Ik0xNy4wNDM5IDAuNTE4MDY2Vi02LjU3OTE5SDkuOTQ2NjlWMC41MTgwNjZIMTcuMDQzOVpNMTcuMDQzOSA3Ni4yMjIxSDkuOTQ2NjlWODMuMzE5NEgxNy4wNDM5Vjc2LjIyMjFaTTE3LjA0MzkgNy42MTUzMkg0MC43MDRWLTYuNTc5MTlIMTcuMDQzOVY3LjYxNTMyWk0yNC4xNDEyIDc2LjIyMjFWMC41MTgwNjZIOS45NDY2OVY3Ni4yMjIxSDI0LjE0MTJaTTQwLjcwNCA2OS4xMjQ5SDE3LjA0MzlWODMuMzE5NEg0MC43MDRWNjkuMTI0OVpNNDIuNTgwNSA2OS4xMjQ5SDQwLjcwNFY4My4zMTk0SDQyLjU4MDVWNjkuMTI0OVpNNDcuODAxMyA2OS4xMjQ5SDQyLjU4MDVWODMuMzE5NEg0Ny44MDEzVjY5LjEyNDlaTTc4LjU1NiAzOC4zNzAxQzc4LjU1NiA1NS4zNTU1IDY0Ljc4NjcgNjkuMTI0OSA0Ny44MDEzIDY5LjEyNDlWODMuMzE5NEM3Mi42MjYxIDgzLjMxOTQgOTIuNzUwNSA2My4xOTQ5IDkyLjc1MDUgMzguMzcwMUg3OC41NTZaTTQ3LjgwMTMgNy42MTUzMkM2NC43ODY2IDcuNjE1MzIgNzguNTU2IDIxLjM4NDcgNzguNTU2IDM4LjM3MDFIOTIuNzUwNUM5Mi43NTA1IDEzLjU0NTMgNzIuNjI2IC02LjU3OTE5IDQ3LjgwMTMgLTYuNTc5MTlWNy42MTUzMlpNNDIuNTgwNSA3LjYxNTMySDQ3LjgwMTNWLTYuNTc5MTlINDIuNTgwNVY3LjYxNTMyWk00MC43MDQgNy42MTUzMkg0Mi41ODA1Vi02LjU3OTE5SDQwLjcwNFY3LjYxNTMyWiIgZmlsbD0iYmxhY2siIG1hc2s9InVybCgjZG9zdS1kLWN1dG91dCkiLz48cGF0aCBkPSJNNjguOTIxNSAzNi4wMTM1QzY4LjkyMTUgMzYuMDEzNSA2NS43MzY5IDQ5LjQ3MzggNTEuNDIzMSA0OS40NzM4QzM3LjEwOTMgNDkuNDczOCAzMi41Nzg3IDM3LjM1OTYgMzIuNTc4NyAzNi4wMTM1IiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjcuNjkxNjEiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPjxwYXRoIGQ9Ik0wLjM0ODYzMyA4NS40OTQ2QzAuMzQ4NjMzIDg1LjQ5NDYgMjkuNDg1NiA4NS44MzA5IDM0LjgwOSA4NS42OThDNDQuODMzNyA4NS40NDc3IDUxLjI4NzIgODQuNDAyIDU3LjUyNjkgNzguOTcyNEM2Mi44MTI5IDc0LjM3MjcgNzUuMTM0MiA1OS42ODM2IDc1LjEzNDIgNTkuNjgzNiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjE2NDgyIi8%2BPC9zdmc%2B)](https://github.dosu.com/jaegertracing/jaeger?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-learn-repo&utm_term=jaegertracing%2Fjaeger) [![Add Dosu to your team](https://img.shields.io/badge/Add%20Dosu%20to%20your%20team-1f6feb?style=flat)](https://app.dosu.dev/signup?referrer=openSource&source=github-footer&utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-add-team&utm_term=jaegertracing%2Fjaeger)

**Comment by norin-dlkh** [comment]
Wait, just a random input value, when I use `ttl.spans`, it seems like it is no longer crash. Not sure if it's the correct value. Will see if it's working as I expect.

**Reply by Sawn-CG** [reply]
did it work?

**Reply by norin-dlkh** [reply]
Nope, it doesn't. I can only retrieve data in the last few day only. Further than that, no data is response

**Reply by Sawn-CG** [reply]
have you tried setting env var BADGER_SPAN_STORE_TTL=120h as said in https://github.com/orgs/jaegertracing/discussions/6250.
I tried, now the querier service does not start in jaeger v2

**Comment by yurishkuro** [comment]
```
badger:
  directories:
    ...
  ttl:
    spans: 720h
```

**Reply by norin-dlkh** [reply]
```
  service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 14269
    logs:
      level: debug
    # TODO Initialize telemetry tracer once OTEL released new feature.
    # https://github.com/open-telemetry/opentelemetry-collector/issues/10663

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: 0.0.0.0:14133
      status:
        enabled: true
        path: "/status"

  jaeger_query:
    storage:
      traces: primary_store
      traces_archive: archive_store
      metrics: metrics_storage
    ui:
      config_file: /jaeger/config-ui.json


  jaeger_storage:
    backends:
      primary_store:
        badger:
          directories:
            keys: "/app/data"
            values: "/app/data"
          ephemeral: false
          ttl:
            spans: 720h
        memory:
          max_traces: 100000
      archive_store:
        badger:
          directories:
            keys: "/app/jaeger_archive/"
            values: "/app/jaeger_archive/"
          ephemeral: false
          ttl:
            spans: 720h
        memory:
          max_traces: 100000
    metric_backends:
      metrics_storage:
        prometheus:
          endpoint: http://prometheus:9090
          normalize_calls: true
          normalize_duration: true

connectors:
  spanmetrics:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"


processors:
  batch:



exporters:
  jaeger_storage_exporter:
    trace_storage: primary_store
    queue:
      num_consumers: 50
      queue_size: 1000
  prometheus:
    endpoint: "0.0.0.0:14270"
```

Here is my full config, but it doesn't seem working. It doesn't crash but when I tried query back date for more than 2 days, no data is response.
