### DISCUSSION TITLE
Issue with Jaeger V2 deployment with cassandra TLS enabled

### DISCUSSION THREAD

**Discussion by Sidhartha-Biswal** [jaegertracing/jaeger#7130] [Q&A]
Hi,
 
We are working on Jaeger V1 to V2 Migration, as part of this trying to deploy jaeger with backend as cassandra(with TLS) with below exporter configuration, but the deployment is failing with below error, without TLS deployment works fine.
 
is Cassandra with TLS support is there in V2? if yes please help us with how to configure.
 
https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-cassandra.yaml
 
From the above link configuration given for no TLS case, TLS case how to pass certificates configuration is missing and did not find this information in below cassandra V1 to V2 migration guide also.
 
https://docs.google.com/document/d/16M50j-ATIGb0AgKQBz-719XzJNwJWoouNTs7_N3fKfY/edit?tab=t.0#heading=h.qbckwiyz30oe
 
```
jaeger_storage:

    backends:

      another_storage:

        cassandra:

          schema:

            keyspace: "jaeger_v1_datacenter1"

            create: true

          connection:

            local_dc: "datacenter1"

            servers: cassandra:9042

            port: 9042

            auth:

              basic:

                username: ""

                password: ""

            tls:

              cert_file: /path/client/tls.crt

              key_file: /path/client/tls.key

              ca_file: /path/root-cert/ca.crt

              cipher_suites:

              min_version: "1.2"

              max_version: "1.3"

exporters:

  jaeger_storage_exporter:

    trace_storage: another_storage
```

We are getting the below error we are getting with this configuration.

2025-05-16T05:26:51.355Z        info    extensions/extensions.go:41     Starting extensions...

2025-05-16T05:26:51.355Z        info    extensions/extensions.go:45     Extension is starting...

2025-05-16T05:26:51.355Z        info    jaegerstorage/extension.go:159  Initializing storage 'another_storage'

2025/05/16 05:26:54 error: failed to connect to "[HostInfo hostname=\"192.168.x.x\" connectAddress=\"192.168.x.x\" peer=\"<nil>\" rpc_address=\"192.168.x.x\" broadcast_address=\"192.168.x.x\" preferred_ip=\"<nil>\" connect_addr=\"192.168.x.x\" connect_addr_source=\"connect_address\" port=9042 data_centre=\"datacenter1\" rack=\"rack1\" host_id=\"bd3436-ab35-450e-893\" version=\"v4.1.0\" state=UP num_tokens=16]" due to error: tls: failed to verify certificate: x509: cannot validate certificate for 192.168.x.x because it doesn't contain any IP SANs

2025-05-16T05:26:54.499Z        error   extensions/extensions.go:58     Failed to start extension       {"error": "failed to initialize storage 'another_storage': no connections were made when creating the session"}
