### DISCUSSION TITLE
jaeger 2.6.0 compability with Elasticsearch 8.X

### DISCUSSION THREAD

**Discussion by VolodymyrVolodymyrovych** [jaegertracing/jaeger#7153] [Q&A]
Hello!

I have the issue with compability with Jaeger 2.6.0 with Elastic 8.X. It's my config:

```
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
    logs:
      level: debug
    # TODO Initialize telemetry tracer once OTEL released new feature.
    # https://github.com/open-telemetry/opentelemetry-collector/issues/10663

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: elastic_storage
      #traces_archive: another_elastic_storage
    ui:
      config_file: ./config-ui.json

  jaeger_storage:
    backends:
      elastic_storage:
        elasticsearch:
          server_urls:
            - https://elastic.com
          indices:
            index_prefix: "jaeger-main"
            spans:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            services:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            dependencies:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
            sampling:
              date_layout: "2006-01-02"
              rollover_frequency: "day"
              shards: 5
              replicas: 1
      #another_elastic_storage:
      #  elasticsearch:
      #    server_urls:
      #      - http://localhost:9200
      #    indices:
      #      index_prefix: "jaeger-archive"

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: elastic_storage
```

After running the command I have an error:

./jaeger --config=config-elastic.yaml   (I used binary)

```
Error: cannot start pipelines: failed to start "jaeger_storage_exporter" exporter: cannot create trace writer: failed to create template "jaeger-main-jaeger-span": error creating index template jaeger-main-jaeger-span: [400 Bad Request] {"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}
2025/05/23 10:48:48 cannot start pipelines: failed to start "jaeger_storage_exporter" exporter: cannot create trace writer: failed to create template "jaeger-main-jaeger-span": error creating index template jaeger-main-jaeger-span: [400 Bad Request] {"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}
```

Is it Jaeger 2.6.0 compatible with Elastic 8.X  ? Give me please some suggestions :) Maybe I need to use an older version?
Thanks!

**Comment by yurishkuro** [comment]
All releases are tested against ES v8, e.g. [the recent run](https://github.com/jaegertracing/jaeger/actions/runs/15206352388/job/42770301672?pr=7154), which has a config similar to yours.

My guess is this is related to your setup.
 
The error `{"type":"parse_exception","reason":"request body is required"}` is odd. Do you have some kind of proxy between jaeger and ES?

**Reply by VolodymyrVolodymyrovych** [reply]
Sorry for inaccurate information, I have the elastic 9, and jaeger see it:
```
info    config/config.go:302    Elasticsearch detected  {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension", "version": 9}
```

yes, I have ... it's nginx which is configured to use instead http://elastic.com:9200 to https://elastic.com

**Reply by yurishkuro** [reply]
V9 is not supported atm.

**Reply by VolodymyrVolodymyrovych** [reply]
ok, thanks a lot

**Comment by dosubot** [comment]
Jaeger 2.6.0 is compatible with Elasticsearch 8.X—this is confirmed in the official documentation, which states that Jaeger supports Elasticsearch versions 7.x and 8.x, and will automatically detect and use the correct API and index mappings for your Elasticsearch version [(source)](https://github.com/jaegertracing/documentation/blob/main/content/docs/2.4/elasticsearch.md).

The error you are seeing:

```
error creating index template jaeger-main-jaeger-span: [400 Bad Request] {"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}
```

means that Jaeger is sending a request to Elasticsearch to create an index template, but the request body is empty when Elasticsearch expects data. This can happen due to a misconfiguration or a missing part of the configuration that results in Jaeger not sending the required template definition [(source)](https://github.com/jaegertracing/jaeger/blob/main/internal/storage/elasticsearch/client/client.go).

**Suggestions:**

1. **Check your Elasticsearch endpoint:**  
   The `server_urls` field in your config is set to `https://elastic.com`, which is not a valid Elasticsearch server endpoint. It should point to your actual Elasticsearch instance, e.g., `http://localhost:9200` or your cluster's address.

2. **Explicitly set the Elasticsearch version:**  
   If auto-detection fails, you can explicitly set the version in your config under the `elasticsearch` section:
   ```yaml
   elasticsearch:
     version: 8
     server_urls:
       - http://your-elasticsearch-host:9200
     ...
   ```

3. **Review your index template configuration:**  
   Make sure there are no missing or misconfigured fields in your `indices` section. Compare your config with the [official sample config](https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-elasticsearch.yaml) to ensure all required fields are present.

4. **Elasticsearch authentication:**  
   If your Elasticsearch instance requires authentication (username/password or API key), ensure those credentials are included in your config.

**Summary:**  
Jaeger 2.6.0 should work with Elasticsearch 8.X. The error is likely due to an invalid Elasticsearch endpoint or a misconfiguration in your Jaeger config, resulting in an empty request body when creating index templates. Double-check your `server_urls` and other config fields, and try explicitly setting the Elasticsearch version if needed.



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=reply-with-mention&utm_term=jaegertracing%2Fjaeger).*

---

Docs are dead. Just use [Dosu](https://dosu.dev?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-tagline&utm_term=jaegertracing%2Fjaeger).

[![Leave Feedback](https://img.shields.io/badge/Leave%20Feedback-555555?style=flat)](https://app.dosu.dev/response-feedback?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-feedback&utm_term=jaegertracing%2Fjaeger#message_id=b3cff5f0-2dd2-44f0-835f-ad9187c72649) [![Ask Dosu about jaeger](https://img.shields.io/badge/Ask%20Dosu%20about%20jaeger-2f7b3f?style=flat&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iODYiIGhlaWdodD0iODkiIHZpZXdCb3g9IjAgMCA4NiA4OSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4yOTIzNiAxMi43OTI4TDE3Ljc1OTMgNi42ODE4OFY3Mi41NjY3TDUuMjkyMzYgODQuMDYxOFYxMi43OTI4WiIgZmlsbD0iI0I0QkI5MSIvPjxwYXRoIGQ9Ik0xOC4yNTc1IDczLjExOTZMNTkuMTMyOSA3Mi43NDhMNTEuNzAxMSA4Mi40MDk1TDI5LjAzMzggODYuMjkxTDYuMjM5NjIgODUuMTU1NEwxOC4yNTc1IDczLjExOTZaIiBmaWxsPSIjNzc4NTYxIi8%2BPHBhdGggZD0iTTE3LjQ5MTYgMy43MzYzM0wzLjU4NTU3IDEyLjcwOTlWODMuNTc5MkMzLjU4NTU3IDg0Ljc1NDIgNC45ODU2MyA4NS4zNjUyIDUuODQ3MDUgODQuNTY2TDE5LjYyOTYgNzEuNzgwMSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjQyODQ0IiBzdHJva2UtbGluZWNhcD0icm91bmQiLz48bWFzayBpZD0iZG9zdS1kLWN1dG91dCIgZmlsbD0id2hpdGUiPjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNNDAuNzA0IDAuNTE4MDY2SDE3LjA0MzlWNzYuMjIyMUg0MC43MDRINDIuNTgwNUg0Ny44MDEzQzY4LjcwNjQgNzYuMjIyMSA4NS42NTMzIDU5LjI3NTIgODUuNjUzMyAzOC4zNzAxQzg1LjY1MzMgMTcuNDY1IDY4LjcwNjMgMC41MTgwNjYgNDcuODAxMyAwLjUxODA2Nkg0Mi41ODA1SDQwLjcwNFoiLz48L21hc2s%2BPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00MC43MDQgMC41MTgwNjZIMTcuMDQzOVY3Ni4yMjIxSDQwLjcwNEg0Mi41ODA1SDQ3LjgwMTNDNjguNzA2NCA3Ni4yMjIxIDg1LjY1MzMgNTkuMjc1MiA4NS42NTMzIDM4LjM3MDFDODUuNjUzMyAxNy40NjUgNjguNzA2MyAwLjUxODA2NiA0Ny44MDEzIDAuNTE4MDY2SDQyLjU4MDVINDAuNzA0WiIgZmlsbD0iI0YzRjZGMSIvPjxwYXRoIGQ9Ik0xNy4wNDM5IDAuNTE4MDY2Vi02LjU3OTE5SDkuOTQ2NjlWMC41MTgwNjZIMTcuMDQzOVpNMTcuMDQzOSA3Ni4yMjIxSDkuOTQ2NjlWODMuMzE5NEgxNy4wNDM5Vjc2LjIyMjFaTTE3LjA0MzkgNy42MTUzMkg0MC43MDRWLTYuNTc5MTlIMTcuMDQzOVY3LjYxNTMyWk0yNC4xNDEyIDc2LjIyMjFWMC41MTgwNjZIOS45NDY2OVY3Ni4yMjIxSDI0LjE0MTJaTTQwLjcwNCA2OS4xMjQ5SDE3LjA0MzlWODMuMzE5NEg0MC43MDRWNjkuMTI0OVpNNDIuNTgwNSA2OS4xMjQ5SDQwLjcwNFY4My4zMTk0SDQyLjU4MDVWNjkuMTI0OVpNNDcuODAxMyA2OS4xMjQ5SDQyLjU4MDVWODMuMzE5NEg0Ny44MDEzVjY5LjEyNDlaTTc4LjU1NiAzOC4zNzAxQzc4LjU1NiA1NS4zNTU1IDY0Ljc4NjcgNjkuMTI0OSA0Ny44MDEzIDY5LjEyNDlWODMuMzE5NEM3Mi42MjYxIDgzLjMxOTQgOTIuNzUwNSA2My4xOTQ5IDkyLjc1MDUgMzguMzcwMUg3OC41NTZaTTQ3LjgwMTMgNy42MTUzMkM2NC43ODY2IDcuNjE1MzIgNzguNTU2IDIxLjM4NDcgNzguNTU2IDM4LjM3MDFIOTIuNzUwNUM5Mi43NTA1IDEzLjU0NTMgNzIuNjI2IC02LjU3OTE5IDQ3LjgwMTMgLTYuNTc5MTlWNy42MTUzMlpNNDIuNTgwNSA3LjYxNTMySDQ3LjgwMTNWLTYuNTc5MTlINDIuNTgwNVY3LjYxNTMyWk00MC43MDQgNy42MTUzMkg0Mi41ODA1Vi02LjU3OTE5SDQwLjcwNFY3LjYxNTMyWiIgZmlsbD0iYmxhY2siIG1hc2s9InVybCgjZG9zdS1kLWN1dG91dCkiLz48cGF0aCBkPSJNNjguOTIxNSAzNi4wMTM1QzY4LjkyMTUgMzYuMDEzNSA2NS43MzY5IDQ5LjQ3MzggNTEuNDIzMSA0OS40NzM4QzM3LjEwOTMgNDkuNDczOCAzMi41Nzg3IDM3LjM1OTYgMzIuNTc4NyAzNi4wMTM1IiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjcuNjkxNjEiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPjxwYXRoIGQ9Ik0wLjM0ODYzMyA4NS40OTQ2QzAuMzQ4NjMzIDg1LjQ5NDYgMjkuNDg1NiA4NS44MzA5IDM0LjgwOSA4NS42OThDNDQuODMzNyA4NS40NDc3IDUxLjI4NzIgODQuNDAyIDU3LjUyNjkgNzguOTcyNEM2Mi44MTI5IDc0LjM3MjcgNzUuMTM0MiA1OS42ODM2IDc1LjEzNDIgNTkuNjgzNiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjE2NDgyIi8%2BPC9zdmc%2B)](https://github.dosu.com/jaegertracing/jaeger?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-ask-repo&utm_term=jaegertracing%2Fjaeger) [![Share Dosu with your team](https://img.shields.io/badge/Share%20Dosu%20with%20your%20team-1f6feb?style=flat)](https://app.dosu.dev/signup?referrer=openSource&source=github-footer&utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=static-docs-share-team&utm_term=jaegertracing%2Fjaeger)
