### DISCUSSION TITLE
Help on why Jaeger with jaeger-storage, jaeger-query hangs on restarts

### DISCUSSION THREAD

**Discussion by j-a-l-a-j** [jaegertracing/jaeger#7241] [Q&A]
I am using Jaeger to receive data through otlp from my applications and then forward metrics related data to Prometheus.

It works perfectly as such. However, it seems like whenever I restart Jaeger for any reason, it hangs and does not initialise the OTLP collectors.

```
$ /usr/local/bin/jaeger --version
2025/06/20 07:05:42 application version: git-commit=02128431cc2566b5cc3f38b8aea88a30f182ce3d, git-version=v2.6.0, build-date=2025-05-09T19:30:14Z
jaeger version v2.6.0
```

Here is the jaeger config:

```
service:
    extensions: [jaeger_storage, jaeger_query]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [jaeger_storage_exporter, spanmetrics]

        metrics/spanmetrics:
            receivers: [spanmetrics]
            exporters: [prometheus]

        metrics:
            receivers: [otlp] # New: receives application metrics via OTLP
            processors: [batch]
            exporters: [prometheus] # New exporter for app metrics

    telemetry:
        resource:
            service.name: jaeger
        logs:
            level: DEBUG

extensions:
    jaeger_query:
        storage:
            traces: badger_storage
            metrics: prometheus_storage
    jaeger_storage:
        backends:
            badger_storage:
                badger:
                    directories:
                        keys: "/var/lib/jaeger/badger/keys/"
                        values: "/var/lib/jaeger/badger/data/"
                    ephemeral: false
                    ttl:
                        spans: 72h
        metric_backends:
            prometheus_storage:
                prometheus:
                    endpoint: http://localhost:9090
                    normalize_calls: true
                    normalize_duration: true

connectors:
    spanmetrics:

receivers:
    otlp:
        protocols:
            grpc:
                endpoint: "0.0.0.0:4317"
            http:
                endpoint: "0.0.0.0:4318"

processors:
    batch:

exporters:
    jaeger_storage_exporter:
        trace_storage: badger_storage
    prometheus:
        endpoint: "0.0.0.0:8889"
```

Here is the log output from Jaeger:
```
jaeger[2333561]: 2025/06/20 06:41:30 application version: git-commit=02128431cc2566b5cc3f38b8aea88a30f182ce3d, git-version=v2.6.0, build-date=2025-05-09T19:30:14Z
jaeger[2333561]: 2025-06-20T06:41:30.267Z        info        service@v0.125.0/service.go:199        Setting up own telemetry...
jaeger[2333561]: 2025-06-20T06:41:30.267Z        debug        builders/builders.go:24        Beta component. May change in the future.        {"otelcol.component.id": "prometheus", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics"}
jaeger[2333561]: 2025-06-20T06:41:30.267Z        info        builders/builders.go:26        Development component. May change in the future.        {"otelcol.component.id": "jaeger_storage_exporter", "otelcol.component.kind": "exporter", "otelcol.signal": "traces"}
jaeger[2333561]: 2025-06-20T06:41:30.267Z        debug        builders/builders.go:24        Alpha component. May change in the future.        {"otelcol.component.id": "spanmetrics", "otelcol.component.kind": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
jaeger[2333561]: 2025-06-20T06:41:30.267Z        info        spanmetricsconnector@v0.125.0/connector.go:108        Building spanmetrics connector        {"otelcol.component.id": "spanmetrics", "otelcol.component.kind": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        builders/builders.go:24        Beta component. May change in the future.        {"otelcol.component.id": "batch", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "traces", "otelcol.signal": "traces"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        builders/builders.go:24        Stable component.        {"otelcol.component.id": "otlp", "otelcol.component.kind": "receiver", "otelcol.signal": "traces"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        otlpreceiver@v0.125.0/otlp.go:58        created signal-agnostic logger        {"otelcol.component.id": "otlp", "otelcol.component.kind": "receiver"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        builders/builders.go:24        Beta component. May change in the future.        {"otelcol.component.id": "batch", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "metrics", "otelcol.signal": "metrics"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        builders/builders.go:24        Stable component.        {"otelcol.component.id": "otlp", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        builders/extension.go:48        Beta component. May change in the future.        {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension"}
jaeger[2333561]: 2025-06-20T06:41:30.268Z        debug        builders/extension.go:48        Beta component. May change in the future.        {"otelcol.component.id": "jaeger_query", "otelcol.component.kind": "extension"}
jaeger[2333561]: 2025-06-20T06:41:30.269Z        info        service@v0.125.0/service.go:266        Starting jaeger...        {"Version": "v2.6.0", "NumCPU": 32}
jaeger[2333561]: 2025-06-20T06:41:30.269Z        info        extensions/extensions.go:41        Starting extensions...
jaeger[2333561]: 2025-06-20T06:41:30.269Z        info        extensions/extensions.go:45        Extension is starting...        {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension"}
jaeger[2333561]: 2025-06-20T06:41:30.270Z        info        jaegerstorage/extension.go:159        Initializing storage 'badger_storage'        {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension"}
jaeger[2333561]: badger 2025/06/20 06:41:30 INFO: All 45 tables opened in 2ms
jaeger[2333561]: badger 2025/06/20 06:41:30 INFO: Discard stats nextEmptySlot: 0
jaeger[2333561]: badger 2025/06/20 06:41:30 INFO: Set nextTxnTs to 482984
jaeger[2333561]: badger 2025/06/20 06:41:30 INFO: Deleting empty file: /var/lib/jaeger/badger/data//000002.vlog
jaeger[2333561]: 2025-06-20T06:41:30.312Z        info        badger/factory.go:160        Badger storage configuration        {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension", "configuration": {"Dir":"/var/lib/jaeger/badger/keys/","ValueDir":"/var/lib/jaeger/badger/data/","SyncWrites":false,"NumVersionsToKeep":1,"ReadOnly":false,"Logger":{},"Compression":1,"InMemory":false,"MetricsEnabled":true,"NumGoroutines":8,"MemTableSize":67108864,"BaseTableSize":2097152,"BaseLevelSize":10485760,"LevelSizeMultiplier":10,"TableSizeMultiplier":2,"MaxLevels":7,"VLogPercentile":0,"ValueThreshold":1048576,"NumMemtables":5,"BlockSize":4096,"BloomFalsePositive":0.01,"BlockCacheSize":268435456,"IndexCacheSize":0,"NumLevelZeroTables":5,"NumLevelZeroTablesStall":15,"ValueLogFileSize":1073741823,"ValueLogMaxEntries":1000000,"NumCompactors":4,"CompactL0OnClose":false,"LmaxCompaction":false,"ZSTDCompressionLevel":1,"VerifyValueChecksum":false,"EncryptionKey":"","EncryptionKeyRotationDuration":864000000000000,"BypassLockGuard":false,"ChecksumVerificationMode":0,"DetectConflicts":true,"NamespaceOffset":-1,"ExternalMagicVersion":0}}
jaeger[2333561]: 2025-06-20T06:41:30.312Z        info        jaegerstorage/extension.go:210        Initializing metrics storage 'prometheus_storage'        {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension"}
jaeger[2333561]: 2025-06-20T06:41:30.313Z        info        extensions/extensions.go:62        Extension started.        {"otelcol.component.id": "jaeger_storage", "otelcol.component.kind": "extension"}
jaeger[2333561]: 2025-06-20T06:41:30.313Z        info        extensions/extensions.go:45        Extension is starting...        {"otelcol.component.id": "jaeger_query", "otelcol.component.kind": "extension"}
jaeger[2333561]: 2025-06-20T06:41:30.313Z        info        grpc@v1.72.0/clientconn.go:176        [core] original dial target is: "localhost:4317"        {"grpc_log": true}
jaeger[2333561]: 2025-06-20T06:41:30.313Z        info        grpc@v1.72.0/clientconn.go:459        [core] [Channel #1]Channel created        {"grpc_log": true}
jaeger[2333561]: 2025-06-20T06:41:30.313Z        info        grpc@v1.72.0/clientconn.go:207        [core] [Channel #1]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"dns", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/localhost:4317", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}        {"grpc_log": true}
jaeger[2333561]: 2025-06-20T06:41:30.313Z        info        grpc@v1.72.0/clientconn.go:208        [core] [Channel #1]Channel authority set to "localhost:4317"        {"grpc_log": true}
```

And it hangs there. Never proceeds from that point. Some other observations that might be helpful:

- Deleting the badger storage directory and then restarting jaeger fixes the issue
- Disabling the jaeger query extension also fixes the issue

Any idea what is happening and how can this be fixed?
