### ISSUE TITLE
depoly the collector,elasticsearch and query, but cannot find the data in query ui

### ISSUE THREAD

**Issue by wxyu9191** [jaegertracing/jaeger#1059]
the collector's logs show that the spans are stored successful, but in the query ui I cannot search anything. 
And with the some program, in the all-in-one, it can show the traces.So what is the problem?

these my deployed order:
docker run -d --name elasticsearch --restart=always -p 9200:9200 -p 9300:9300 -e ES_JAVA_OPTS="-Xms512m -Xmx512m" elasticsearch:5.6.4

docker run -d --name jaeger-collector -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://elasticsearch:9200 -e ES_USERNAME=elastic -p 14267:14267 -p 14268:14268 -p 9411:9411 jaegertracing/jaeger-collector

docker run -d --name jaeger-query -e SPAN_STORAGE_TYPE=elasticsearch -e ES_SERVER_URLS=http://10.60.170.56:9200 -p 16686:16686/tcp jaegertracing/jaeger-query

can you give some advise?

**Comment by fredipevcin** [comment]
Have you tried passing the same values for ES to query?
`-e ES_SERVER_URLS=http://elasticsearch:9200 -e ES_USERNAME=elastic`

Does query logs anything that will give more context?

**Comment by wxyu9191** [comment]
> Have you tried passing the same values for ES to query?
> `-e ES_SERVER_URLS=http://elasticsearch:9200 -e ES_USERNAME=elastic`
> 
> Does query log anything that will give more context?
these are all the logs of query:
{"level":"info","ts":1537050099.5767357,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":16687,"status":"unavailable"}
{"level":"info","ts":1537050129.6174698,"caller":"query/main.go:180","msg":"Archive storage not created","reason":"Archive storage not supported"}
{"level":"info","ts":1537050130.2850518,"caller":"query/main.go:125","msg":"Registering metrics handler with HTTP server","route":"/metrics"}
{"level":"info","ts":1537050130.285338,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1537050130.2854176,"caller":"query/main.go:134","msg":"Starting jaeger-query HTTP server","port":16686}

I pass the same data to the es one and all-in-one....and now I cannot find any point....so puzzled

**Comment by fredipevcin** [comment]
Are you running an agent?

Try with this docker-compose file
```yaml
version: '2.2'
services:

  elasticsearch:
    image: elasticsearch:5.6.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  collector:
    image: jaegertracing/jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - LOG_LEVEL=debug

  agent:
    image: jaegertracing/jaeger-agent
    environment:
      - COLLECTOR_HOST_PORT=collector:14267
      - LOG_LEVEL=debug

  query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_USERNAME=elastic
      - LOG_LEVEL=debug
    ports:
      - 16686:16686

  hotrod:
    image: jaegertracing/example-hotrod:1.6
    command: all --jaeger-agent.host-port=agent:6831
    ports:
      - 8080:8080
```
