### ISSUE TITLE
unknown command "/go/bin/agent-linux" for "jaeger-agent" for docker-compose

### ISSUE THREAD

**Issue by douzizuibang** [jaegertracing/jaeger#1173]
I have a VM of ubuntu 16.04,
and then install docker(18.09.0), install docker-compose(1.20.0).

**the follew is docker-compose.yml:**
```
version: "3"

services:
  collector:
    image: jaegertracing/jaeger-collector
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "9411:9411"
    restart: on-failure
    command: ["/go/bin/collector-linux", "--es.server-urls=http://es-loadbalancer:9200", "--es.username=jaeger_remote_agent", "--es.password=HunterSpir!t", "--es.num-shards=1", "--span-storage.type=elasticsearch", "--log-level=error"]

  agent:
    image: jaegertracing/jaeger-agent
    command: ["/go/bin/agent-linux", "--collector.host-port=collect:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - collector

  query:
    image: jaegertracing/jaeger-query
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    command: ["/go/bin/query-linux", "--es.server-urls=http://es-loadbalancer:9200", "--span-storage.type=elasticsearch", "--log-level=debug", "--es.username=jaeger_remote_agent", "--es.password=HunterSpir!t", "--query.static-files=/go/jaeger-ui/"]
    depends_on:
      - agent
```

**the log has been print after docker-compose up:**
```
root@k8s-1:~/te# docker-compose up
Pulling collector (jaegertracing/jaeger-collector:latest)...
latest: Pulling from jaegertracing/jaeger-collector
94a3ce3bf7a9: Pull complete
9956a1a8ce48: Pull complete
Digest: sha256:9279f8f3a5501ecd441c9ef91dbf38f0ee75ab9c030cd8e11d27df3f31c0faa8
Status: Downloaded newer image for jaegertracing/jaeger-collector:latest
Pulling query (jaegertracing/jaeger-query:latest)...
latest: Pulling from jaegertracing/jaeger-query
94a3ce3bf7a9: Already exists
7e7b356beb40: Pull complete
Digest: sha256:84e286750ba6b15793837c29102147c2544eef8583ab87a23ac072b0d3b1ced9
Status: Downloaded newer image for jaegertracing/jaeger-query:latest
Creating te_collector_1 ... done
Recreating te_agent_1   ... done
Creating te_query_1     ... done
Attaching to te_collector_1, te_agent_1, te_query_1
collector_1  | WARNING: found deprecated command line option --span-storage.type=elasticsearch, please use environment variable SPAN_STORAGE_TYPE instead
collector_1  | Error: unknown command "/go/bin/collector-linux" for "jaeger-collector"
collector_1  | Run 'jaeger-collector --help' for usage.
collector_1  | unknown command "/go/bin/collector-linux" for "jaeger-collector"
agent_1      | Error: unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | Run 'jaeger-agent --help' for usage.
agent_1      | unknown command "/go/bin/agent-linux" for "jaeger-agent"
query_1      | WARNING: found deprecated command line option --span-storage.type=elasticsearch, please use environment variable SPAN_STORAGE_TYPE instead
query_1      | Error: unknown command "/go/bin/query-linux" for "jaeger-query"
query_1      | Run 'jaeger-query --help' for usage.
query_1      | unknown command "/go/bin/query-linux" for "jaeger-query"
te_agent_1 exited with code 1
agent_1      | Error: unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | Run 'jaeger-agent --help' for usage.
agent_1      | unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | Error: unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | Run 'jaeger-agent --help' for usage.
agent_1      | unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | Error: unknown command "/go/bin/agent-linux" for "jaeger-agent"
agent_1      | Run 'jaeger-agent --help' for usage.
te_query_1 exited with code 1
query_1      | WARNING: found deprecated command line option --span-storage.type=elasticsearch, please use environment variable SPAN_STORAGE_TYPE instead
query_1      | Error: unknown command "/go/bin/query-linux" for "jaeger-query"
query_1      | Run 'jaeger-query --help' for usage.
query_1      | unknown command "/go/bin/query-linux" for "jaeger-query"
query_1      | WARNING: found deprecated command line option --span-storage.type=elasticsearch, please use environment variable SPAN_STORAGE_TYPE instead
query_1      | Error: unknown command "/go/bin/query-linux" for "jaeger-query"
query_1      | Run 'jaeger-query --help' for usage.
query_1      | unknown command "/go/bin/query-linux" for "jaeger-query"
te_collector_1 exited with code 1
te_query_1 exited with code 1
te_agent_1 exited with code 1
```

**Comment by annanay25** [comment]
Hi,

Did you try using the official `docker-compose.yml` distributed with this repo?
https://github.com/jaegertracing/jaeger/blob/master/docker-compose/jaeger-docker-compose.yml

**Comment by pavolloffay** [comment]
@douzizuibang in jaeger 1.6 we have changed dockerfiles to use entrypoint. Please use official docker-compose.yml from this repo.

**Comment by jpkrohling** [comment]
Also, I would recommend using fixed versions on the image specification to avoid this kind of issue. 

```yaml
services:
  collector:
    image: jaegertracing/jaeger-collector:1.6 # always specify a version here
...
  agent:
    image: jaegertracing/jaeger-agent:1.6 # and here
...
  query:
    image: jaegertracing/jaeger-query:1.6 # and here
...
```
