### ISSUE TITLE
Jaeger Agent Not Connecting to Collector

### ISSUE THREAD

**Issue by gituser1379** [jaegertracing/jaeger#1395]
I have deployed an application to container along with Jaeger agent as side car deployment

## Problem

Kubernetes used to startup both the containers in the pod with out any problem, from last week the jaeger agent seems to be having problems starting up within the same pod. When I looked at the container logs in the pod I see the following error

```
{"level":"warn","ts":1551640126.4296134,"caller":"tchannel/flags.go:72","msg":"Using deprecated configuration","option":"collector.host-port"}
{"level":"fatal","ts":1551640126.4301643,"caller":"agent/main.go:78","msg":"Could not create collector proxy","error":"could not create collector proxy, address is missing","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/main.go:78\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/main.go:121\nruntime.main\n\t/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/proc.go:201"}
```

I am deploying Jaeger components to Kubernetes using the following command
```
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml
```

My application yaml file looks like this 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testproject-deployment
spec:
   selector:
    matchLabels:
      app: bwce-testproject
   replicas: 2
   template:
     metadata:
       labels:
         app: bwce-testproject
     spec:
       containers:
       - image: docker.io/syadavalli/bwce-testproject:latest
         name: bwce-testproject
         ports:
         - containerPort: 18000
         env:
         - name: BW_JAVA_OPTS
           value: "-Dbw.engine.opentracing.enable=true -Dbw.monitor.batchsize=1 -Dbw.monitor.publishtimer=1500"
         - name: BW_LOGLEVEL
           value: ERROR
         - name: BW_APP_MONITORING_CONFIG
           value: "{\"url\":\"http://100.98.34.21:80\"}"
       - image: jaegertracing/jaeger-agent
         name: jaeger-agent
         ports:
         - containerPort: 5775
           protocol: UDP
         - containerPort: 6831
           protocol: UDP
         - containerPort: 6832
           protocol: UDP
         - containerPort: 5778
           protocol: TCP
         args: ["--collector.host-port=100.69.87.41:14267"]
---
apiVersion: v1
kind: Service
metadata:
  name: my-testproject
spec:
  selector:
   app: bwce-testproject
  ports:
  - name: http
    port: 80
    targetPort: 18000
    protocol: "TCP"
  type: LoadBalancer
```

The collector host port is the correct one. I have manually replaced the --collector.host-port value by looking at the Kubernetes service 

## Proposal

I don't have a suggestion as to how to solve the problem.

Looks like there was a version upgrade from 1.9 to 1.10. Not sure if the issue I am experiencing has to do with the version upgrade. Please let me know why I am expriencing the above problem.
