### ISSUE TITLE
connection refused from app to Jaeger

### ISSUE THREAD

**Issue by weworksonam** [jaegertracing/jaeger#1532]
I have a golang app that creates a Opentracing span on a endpoint and should be showing in jaegerui but I keep seeing connection refused errors in my app such as following:

```
myapp     | Reporting span f87cb2fdba9daaf:f87cb2fdba9daaf:0:1
myapp     | time="2019-05-13T14:52:29Z" level=info msg="sent response back with token"
myapp     | Reporting span 7bb2263580f40006:7bb2263580f40006:0:1
2019/05/13 - 14:52:29 | 200 |     10.1704ms |      172.22.0.1 | POST     /myapp/mytoken
myapp     | ERROR: error when flushing the buffer: write udp 127.0.0.1:43256->127.0.0.1:6831: write: connection refused
```

The following is my docker-compose file:

```
myapp:
        container_name: myapp
        command:  --jaeger-agent.host-port=jaeger:6831 all
#        links:   
#            - jaeger
        build:
          context: ../../
          dockerfile: ./package/folder/Dockerfile
        ports:
         - "5555:5555"
         - "8080:8080"
        links:
            - vault:vault
        volumes:
            - ../../.:/go/src/myapp
        environment:
            - "VAULT_ADDRESS=http://vault:8200"
            - "jaeger-agent.host-port=jaeger:6831"
            - "JAEGER_SERVICE_NAME=jaeger"
            - "JAEGER_AGENT_HOST=jaeger"
            - "JAEGER_AGENT_PORT=6831"     
            - "JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778"

    jaeger: 
        image: jaegertracing/all-in-one:latest
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"    

```
What am I missing?  Any hints?  I am able to connect from the hotrod sample docker container and send reports to the docker jaegerui but does not work from my app.
