### ISSUE TITLE
Traces not showing up when docker-compose is used. Working in all-in-one

### ISSUE THREAD

**Issue by meredrica** [jaegertracing/jaeger#1535]
## General Description
We run a micronaut service that we want to trace. With the all-in-one docker the traces show up, with the docker-compose it does not. Since we plan to host the whole stack in Openshift, we need to have a docker setup as close as possible to our cloud. We can't use Helm Charts for various reasons out of our control.

## micronaut 
Our micronaut integration is confirmed working with the all-in-one container, so we are very sure it's not a bug in our code.
### pom.xml (partial)
```
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-tracing</artifactId>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>io.jaegertracing</groupId>
      <artifactId>jaeger-thrift</artifactId>
      <version>0.31.0</version>
      <scope>compile</scope>
    </dependency>
```
### application.yaml
```
--- # jaeger
tracing:
    jaeger:
        enabled: true
        sampler:
            probability: 1
        sender:
            agentHost: localhost
            agentPort: 5775
        reporter:
            flushInterval: 1
            maxQueueSize: 200
```

## docker-compose file
The dockerfile we use is more or less a copy paste from the one from the repo [here](https://github.com/jaegertracing/jaeger/blob/master/docker-compose/jaeger-docker-compose.yml)
The only differences: we use ``version: '3'``, we added `` "--log-level=info"``

This is the actual file:
```
version: '3'
services:
 jaeger-collector:
    image: jaegertracing/jaeger-collector
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411", "--log-level=info"]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--log-level=info"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    depends_on:
      - cassandra-schema

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250", "--log-level=info"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector

  cassandra:
    image: cassandra:3.9
    volumes:
      - cassandra:/var/lib/cassandra

  cassandra-schema:
    image: jaegertracing/jaeger-cassandra-schema
    depends_on:
      - cassandra
```

we also tried to set up the stack with elastic search like this (same problem):
```
version: '3'
services:
  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.11
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    depends_on:
      - elasticsearch
    restart: always
    command: --reporter.grpc.host-port=jaeger-collector:14250

  jaeger-query:
    image: jaegertracing/jaeger-query:1.11
    ports:
      - "16686:16686"
      - "16687:16687"
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: always

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.11
    command: [
       "--es.server-urls=http://elasticsearch:9200",
       "--span-storage.type=elasticsearch",
       "--es.num-shards=1",
       "--es.num-replicas=0",
       "--log-level=debug"
    ]
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elasticsearch:9200
    ports:
      - "14269:14269"
      - "14250:14250"
    depends_on:
      - elasticsearch
    restart: always

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=debug"
    ]
    depends_on:
      - elasticsearch

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    hostname: jaeger-agent
    command: ["--collector.host-port=jaeger-collector:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: always
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "16686:16686"
      - "16687:16687"
    restart: always
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug"
    ]
    depends_on:
      - jaeger-agent

  elasticsearch:
    image: elasticsearch:6.7.2
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - "elastic:/usr/share/elasticsearch/data"
volumes:
  elastic:
```

## Requirement - what kind of business use case are you trying to solve?

Tracing HTTP Calls with micronaut

## Problem - what in Jaeger blocks you from solving the requirement?

The docker-compose.yml file seems to be misconfigured.

## Any open questions to address
* How can I enable better logs?
