### ISSUE TITLE
Docker example not working

### ISSUE THREAD

**Issue by quantdaddy** [jaegertracing/jaeger#1573]
I am using the docker compose file below to run the HotRod example on a mac (following the example in the second chapter of Mastering Distributed Tracing book). However, I don't get any dependency graph in `Dependencies` UI. I also sometimes get this error in the hotrod service log. Please suggest how to fix the issue. :
```
hotrod_1  | 2019-05-30T22:13:23.906Z	ERROR	log/logger.go:42	error when flushing the buffer: write udp 172.21.0.4:49149->23.202.231.166:6831: write: connection refused	{"service": "frontend"}
```

```yaml
version: '3.7'
services:
  jaegar:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - my-network
  hotrod:
    image: jaegertracing/example-hotrod:latest
    ports: ["8080-8083:8080-8083"]
    command: ["all"]
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    networks:
      - my-network
    depends_on:
      - jaegar

networks:
  my-network:
```
