### ISSUE TITLE
Jaeger agent don't push metrics

### ISSUE THREAD

**Issue by mholleville** [jaegertracing/jaeger#1644]
Hello ! I'm trying to install jaeger since yesterday.

I have an ES 6.8.0 cluster. First strange thing, I have all Jaeger stack to install but I only have one index finger. Is that normal?

<img width="637" alt="Capture d’écran 2019-06-28 à 09 03 36" src="https://user-images.githubusercontent.com/49511757/60323978-cb2cff00-9983-11e9-9955-c97c7b2d200b.png">

Then I deployed the agents in daemonset and when I log the container I do have an active connection with the collector

<img width="1256" alt="Capture d’écran 2019-06-28 à 09 06 05" src="https://user-images.githubusercontent.com/49511757/60324042-fa437080-9983-11e9-9c18-d0d276206089.png">

My collector tells me he’s ready to pick up the Metrics

<img width="1256" alt="Capture d’écran 2019-06-28 à 09 08 41" src="https://user-images.githubusercontent.com/49511757/60324186-6de57d80-9984-11e9-8479-1309db1acfbd.png">

And now my query component has this error :

`"caller":"zap/logger.go:33","msg":"error when flushing the buffer: write udp 127.0.0.1:35143->127.0.0.1:6831: write: connection refused`

Can you explain me ?

**Comment by jpkrohling** [comment]
If your agent is running as a `DaemonSet`, then `127.0.0.1` isn't the correct location for it. The appropriate IP is the node's, which can be referenced like this in your deployment:

```yaml


apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: acme/myapp:myversion
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

Reference: https://github.com/jaegertracing/jaeger-operator/#agent-as-daemonset

In time: if you can, I recommend using the Jaeger Agent as a sidecar instead of daemonset.
