### ISSUE TITLE
Please document the required permissions for Elasticsearch

### ISSUE THREAD

**Issue by yardbirdsax** [jaegertracing/jaeger#1691]
## Requirement - what kind of business use case are you trying to solve?

As someone who is configuring Jaeger to connect to a secured Elasticsearch cluster, it would be very helpful to have it documented as to the specific permissions required to get Jaeger to successfully connect. Unfortunately, the errors thrown aren't terribly helpful.

## Problem - what in Jaeger blocks you from solving the requirement?

Without specific documentation, it took quite a bit of trial and error to determine what privileges were required.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Include a section in the ES plugin docs around how to create a role that satisfies the minimal requirements.

**Comment by yardbirdsax** [comment]
Here's an example role definition JSON for what worked for us.

{
  "jaeger" : {
    "cluster" : [
      "monitor"
    ],
    "indices" : [
      {
        "names" : [
          "jaeger-*"
        ],
        "privileges" : [
          "create",
          "create_index",
          "write",
          "read"
        ],
        "field_security" : {
          "grant" : [
            "*"
          ]
        },
        "allow_restricted_indices" : false
      }
    ],
    "applications" : [ ],
    "run_as" : [ ],
    "metadata" : { },
    "transient_metadata" : {
      "enabled" : true
    }
  }
}

The cluster level "monitor" right was what took quite a bit to figure out.

I'm happy to update the documentation files and send in a PR if it's helpful. Thanks!

**Comment by yurishkuro** [comment]
@yardbirdsax thanks for posting the example.

@pavolloffay I am not that familiar with administering ES. Would  a file like this make sense as part of documentation, or in the code, next to our other ES tools?

**Comment by pavolloffay** [comment]
+1 on documenting these 

@yardbirdsax what plugin is this configuration for? 

@yardbirdsax or @jaegertracing/elasticsearch do you know where are the Elasticsearch permissions documented? The latests dosc I found are for 2.2 https://www.elastic.co/guide/en/shield/2.2/privileges-list.html


Here is an example of SearchGuard for Jaeger https://github.com/openshift/origin-aggregated-logging/blob/master/elasticsearch/sgconfig/sg_roles.yml#L56, There will be a change to add cluster role `MANAGE` because of #1627

**Comment by trondhindenes** [comment]
Permissions for Elasticsearch will rely on which permission plugin is used (if any - it's an optional thing). I'm guessing @yardbirdsax 's example is for the regular x-pack plugin, but there are tons of others in the ecosystem so it should probably be clearly documented which permission system the example config targets.

**Comment by yardbirdsax** [comment]
You’re correct that my example was for x-pack. Here’s a link with relevant information:

https://www.elastic.co/guide/en/elastic-stack-overview/7.2/security-privileges.html

@pavolloffay re the “manage” privilege: it looks like this is for index templates? As someone in an organization with strict security requirements, justifying giving the account this privilege when it (I think?) would only need it once to install the template would be a little tricky. Perhaps it should only attempt this when a flag is set, and manual steps to install the template once by an admin should be provided? Or at least fail gracefully and carry on if it doesn’t have that right? I haven’t dug into the change in detail, so apologies if it already does this. I can also comment on that issue too, depending on what you say here.

**Comment by pavolloffay** [comment]
@yardbirdsax you brought a valid point that somebody might not want to add manage privilege for jaeger.

We could introduce a flag which would disable template creation. In that case it would be user responsibility to create the mappings manually before jaeger startup. The mappings are available here https://github.com/jaegertracing/jaeger/tree/master/plugin/storage/es/mappings so they are easily consumable.

**Comment by andy812** [comment]
> ```json
> {
>     "cluster" : [
>       "monitor"
>     ],
>     "indices" : [
>       {
>         "names" : [
>           "jaeger-*"
>         ],
>         "privileges" : [
>           "create",
>           "create_index",
>           "write",
>           "read"
>         ],
>         "field_security" : {
>           "grant" : [
>             "*"
>           ]
>         },
>         "allow_restricted_indices" : false
>       }
>     ],
>     "applications" : [ ],
>     "run_as" : [ ],
>     "metadata" : { },
>     "transient_metadata" : {
>       "enabled" : true
>     }
>   }
> ```

Cluser permission `manage_index_templates` is required. Works for me:
```
POST /_security/role/jaeger
{
    "cluster" : [
      "monitor",
      "manage_index_templates"
    ],
    "indices" : [
      {
        "names" : [
          "jaeger-*"
        ],
        "privileges" : [
          "create",
          "create_index",
          "write",
          "read"
        ],
        "field_security" : {
          "grant" : [
            "*"
          ]
        },
        "allow_restricted_indices" : false
      }
    ],
    "applications" : [ ],
    "run_as" : [ ],
    "metadata" : { },
    "transient_metadata" : {
      "enabled" : true
    }
  }
```

**Comment by omerfsen** [comment]
With using above permissions I am getting error 

```
jaeger-es-index-cleaner-1611532500-b657j   0/1     Error     0          9h
jaeger-es-index-cleaner-1611532500-fdtgx   0/1     Error     0          9h
jaeger-es-index-cleaner-1611532500-hpmkz   0/1     Error     0          9h
jaeger-es-index-cleaner-1611532500-mqbsb   0/1     Error     0          8h
jaeger-es-index-cleaner-1611532500-mtf5f   0/1     Error     0          8h

```

```bash

kubectl logs -n observability jaeger-es-index-cleaner-1611532500-4lb6z 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/curator/utils.py", line 642, in get_indices
    client.indices.get_settings(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 719, in get_settings
    return self.transport.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 300, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'security_exception', 'action [indices:monitor/settings/get] is unauthorized for user [elastic-jaeger]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/es-index-cleaner/esCleaner.py", line 112, in <module>
    main()
  File "/es-index-cleaner/esCleaner.py", line 30, in main
    ilo = curator.IndexList(client)
  File "/usr/local/lib/python3.8/site-packages/curator/indexlist.py", line 31, in __init__
    self.__get_indices()
  File "/usr/local/lib/python3.8/site-packages/curator/indexlist.py", line 66, in __get_indices
    self.all_indices = utils.get_indices(self.client)
  File "/usr/local/lib/python3.8/site-packages/curator/utils.py", line 653, in get_indices
    raise exceptions.FailedExecution('Failed to get indices. Error: {0}'.format(e))
curator.exceptions.FailedExecution: Failed to get indices. Error: AuthorizationException(403, 'security_exception', 'action [indices:monitor/settings/get] is unauthorized for user [elastic-jaeger]')
```

So added **monitor** to the Privileges. 

```json
        "privileges" : [
          "create",
          "create_index",
          "write",
          "monitor",
          "read"
        ],
```

**Comment by sdickhoven** [comment]
fyi: i am using an aws-managed opendistro elasticsearch cluster (version 7.10) and the following permissions work for me:
```
{
  "description": "Jaeger permissions",
  "cluster_permissions": [
    "cluster:monitor/main",
    "indices:admin/template/put"
  ],
  "index_permissions": [
    {
      "index_patterns": [
        "*jaeger-*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "*"
      ]
    },
    {
      "index_patterns": [
        "*"
      ],
      "fls": [],
      "masked_fields": [],
      "allowed_actions": [
        "indices:admin/aliases/get",
        "indices:admin/rollover",
        "indices_monitor"
      ]
    }
  ]
}
```

these permissions are compatible with index prefixes and restrict permissions outside the jaeger indices to the bare minimum (as required by the current versions of `jaeger-es-rollover` and `jaeger-es-index-cleaner`).

however, i can only guarantee that `jaeger-es-index-cleaner` successfully executes against these permissions when there isn't anything to remove since i don't have anything to remove yet. 🤷‍♀️ 

if anyone's interested... here's how you add the jaeger user to a 7.x opendistro elasticsearch cluster (with internal user database):
```
$ curl --silent \
       --user "admin" \
       --header "Content-Type: application/json" \
       --data @jaeger_role.json \
       --request "PUT" \
       https://jaeger1-elasticsearch.example.com/_opendistro/_security/api/roles/jaeger

$ curl --silent \
       --user "admin" \
       --header "Content-Type: application/json" \
       --data '{"password": "0penSes@me"}' \
       --request "PUT" \
       https://jaeger1-elasticsearch.example.com/_opendistro/_security/api/internalusers/jaeger

$ curl --silent \
       --user "admin" \
       --header "Content-Type: application/json" \
       --data '{"users": ["jaeger"]}' \
       --request "PUT" \
       https://jaeger1-elasticsearch.example.com/_opendistro/_security/api/rolesmapping/jaeger
```
(where `jaeger_role.json` contains the above permission spec)

**Comment by alex-borkun** [comment]
Used mapping from @andy812 , thanks a lot.
Small addition:
`view_index_metadata` - is required for `/jaegertracing/spark-dependencies` job

**Comment by roberth1988** [comment]
One more addition, I've needed also "monitor" on the indices privileges. Th esCleaner failed otherwise with:

```
Traceback (most recent call last):
  File "/es-index-cleaner/esCleaner.py", line 112, in <module>
    main()
  File "/es-index-cleaner/esCleaner.py", line 30, in main
    ilo = curator.IndexList(client)
  File "/usr/local/lib/python3.9/site-packages/curator/indexlist.py", line 31, in __init__
    self.__get_indices()
  File "/usr/local/lib/python3.9/site-packages/curator/indexlist.py", line 72, in __get_indices
    self._get_index_stats()
  File "/usr/local/lib/python3.9/site-packages/curator/indexlist.py", line 149, in _get_index_stats
    iterate_over_stats(stats_result)
  File "/usr/local/lib/python3.9/site-packages/curator/indexlist.py", line 121, in iterate_over_stats
    for index in stats['indices']:
KeyError: 'indices'```

**Comment by sdickhoven** [comment]
i ended up using opendistro's built-in index state management instead of `jaeger-es-rollover` and `jaeger-es-index-cleaner` and adjusted the permissions accordingly.

i have a write-up about it [here](https://tech.everquote.com/jaeger-persistence-elasticsearch/) in case anyone's interested.

**Comment by ChristopherLenz** [comment]
Hello,

I tried the roles from this comment, but they did not work: https://github.com/jaegertracing/jaeger/issues/1691#issuecomment-827176019

Jaeger: 1.39.0
Elasticsearch: 7.17.8

But interestingly, I don't get any talking error message like: "this or this permission is missing". For me it comes to a connection error...

This is the role used for Elastic:
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: roles-secret
stringData:
  roles.yml: |-
    jaeger_writer:
      cluster: [ 'monitor', 'manage_index_templates' ]
      indices:
      - names: [ 'jaeger-*' ]
        privileges: [ 'create',
          'create_index',
          'write',
          'monitor',
          'delete_index',
          'view_index_metadata',
          'read' ]
        field_security:
          grant: ['*' ]
        allow_restricted_indices: false
      applications: [ ]
      run_as: [ ]
      metadata: { },
      transient_metadata: {
        enabled: true
      }
```

This leads to following error:

`failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available`

```
{"level":"fatal","ts":1671633125.2170196,"caller":"./main.go:82","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available","stacktrace":"main.main.func1\n\t./main.go:82\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t./main.go:155\nruntime.main\n\truntime/proc.go:250"}
```

After switching to the default `elastic`-user, Jaeger is able to connect to Elastic.

If I curl the URL of elastic with the jaeger-user I receive the following error:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "action [cluster:monitor/main] is unauthorized for user [jaegertracing] with roles [jaeger_writer], this action is granted by the cluster privileges [monitor,manage,all]"
            }
        ],
        "type": "security_exception",
        "reason": "action [cluster:monitor/main] is unauthorized for user [jaegertracing] with roles [jaeger_writer], this action is granted by the cluster privileges [monitor,manage,all]"
    },
    "status": 403
}
```

Therefore, I think that at least the user with the associated roles was created correctly.

This is Jaeger:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    config: {}
    metricsStorage: {}
    options: {}
    resources: {}
  collector:
    config: {}
    kafkaSecretName: ''
    options: {}
    resources: {}
  ingester:
    config: {}
    kafkaSecretName: ''
    options: {}
    resources: {}
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    enabled: true
    hosts:
      - <URL>
    openshift: {}
    options: {}
    resources: {}
    security: none
  query:
    metricsStorage: {}
    options: {}
    resources: {}
  resources: {}
  sampling:
    options: {}
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      name: elasticsearch
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: '1'
          memory: 16Gi
      storage: {}
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    grpcPlugin: {}
    options:
      es.server-urls: 'https://elasticjaegersearch-es-http.elastic-system.svc:9200'
      es.tls.ca: /es/secrets/ca.crt
      es.tls.enabled: 'true'
      es.tls.skip-host-verify: 'true'
    secretName: elasticsearch-jaeger
    type: elasticsearch
  strategy: production
  ui:
    options:
      dependencies:
        menuEnabled: false
  volumeMounts:
    - mountPath: /es/secrets/
      name: secrets
      readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: elasticjaegersearch-es-http-certs-public
status:
  phase: Running
  version: 1.39.0
```
