### ISSUE TITLE
jaeger-collector does not respect flag value 0.

### ISSUE THREAD

**Issue by vprithvi** [jaegertracing/jaeger#172]
Current Behavior
--
`jaeger-collector` stores spans with span context flags set to 0.

Expected Behavior
--
`jaeger-collector` should not store spans with span contexts where the flag value is 0 because these spans failed the sampling tests. 
This protects the `jaeger-collector` from buggy clients that assume that the collector only stores sampled spans. 

Reproduction steps
--

To reproduce, build jaeger, and run locally as such

```
make build_ui
cd cmd/standalone/
go run ./main.go --span-storage.type=memory --query.static-files=../../jaeger-ui-build/build/
```

Then use [yab](https://github.com/yarpc/yab) to make a request as such. Use jaeger.thrift from [here](https://github.com/uber/jaeger-idl/blob/master/thrift/jaeger.thrift).

```
yab -A trace-id:9 -y payload.yaml
```

`payload.yaml` contains the following
```
---
method: "Collector::submitBatches"
peer: "localhost:14267"
request:
  batches:
    -
      process:
        service_name: flags-test
        tags:
          -
            key: jaeger.hostname
            vStr: localhost
            vType: string
      spans:
        -
          duration: 1294
          flags: 0
          operation_name: arbitrary
          parent_span_id: 0
          span_id: 1
          start_time: 1494509316000000
          tags:
            -
              key: span.kind
              vStr: server
              vType: string
          trace_id_high: 0
          trace_id_low: "${trace-id:1}"
service: jaeger-collector
thrift: jaeger.thrift
```

Note that flags is set to **0**, yet the trace is retrievable using the UI at http://localhost:16686/trace/9
