### ISSUE TITLE
Jaeger in istio

### ISSUE THREAD

**Issue by packyzbq** [jaegertracing/jaeger#1864]
Hey, I want to deploy  jaeger in the production environment of istio. And in my understanding the istio sidecar will send tracing data to Jaeger collector, so it is not necessery to deploy the Jaeger agent, right? I did deploy the Jaeger collector and query, using ES as the storage backend. However there is nothing in the UI and ES.  All installation steps are referenced from https://github.com/jaegertracing/jaeger-kubernetes

My configration for istio:
tracing.zipkin.address : zipkin.<mynamespace>:9411

My configration for jaeger:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
data:
  span-storage-type: elasticsearch
  collector: |
    es:
      server-urls: http://elasticsearch-logging.kube-system:9200
    collector:
      zipkin:
        http-port: 9411
  query: |
    es:
      server-urls: http://elasticsearch-logging.kube-system:9200
  agent: |
    collector:
      host-port: "jaeger-collector:14267"
```

My environment:
istio: 1.2.5
es:  6.6.1

**Comment by jpkrohling** [comment]
Istio will create spans related to its own components, such as Proxy (ingress/egress) and Mixer checks. To be able to have a *distrubuted* trace, you'll need to at least propagate the context by relaying some HTTP headers from the incoming request to the outgoing request. See https://istio.io/docs/tasks/telemetry/distributed-tracing/overview/ .

In your case, you should at least be seeing the ingress spans. Could you please share how your deployment looks like? For reference, here's a [working example from the Jaeger Operator](https://github.com/jaegertracing/jaeger-operator/blob/5f250045063bc8490bceeb39d1aec4641c4c720a/deploy/examples/business-application-injected-sidecar.yaml) repository:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: myapp
        image: jaegertracing/vertx-create-span:operator-e2e-tests
        ports:
        - containerPort: 8080
          protocol: TCP
```
