### ISSUE TITLE
Debugging Jaeger Query (missing traces)

### ISSUE THREAD

**Issue by weeco** [jaegertracing/jaeger#1885]
## Any open questions to address

I have deployed Jaeger 1.14 (Agents, Collector and Query ui as separate services) and use Elasticsearch (7.4) as backend. I ensured that Jaeger traces and spans land in Elasticsearch and I can also query them in Kibana.

Unfortunately I can not see any services/spans in the Jaeger Query ui, nor do I see any error/warn/debug log messages in the query service which would help me to figure out why I can't see these spans. Can you point me in the right direction to figure out why I don't see any spans/traces in the Query UI even though I have plenty of data in Elasticsearch?

**Comment by jpkrohling** [comment]
Please, check the troubleshooting guide:
https://www.jaegertracing.io/docs/1.14/troubleshooting/

**Comment by weeco** [comment]
Well there's nothing related to debugging the Query UI which cannot find these spans and traces in Elasticsearch. Most of the guide focuses on the write path, which however works for me.

**Comment by jpkrohling** [comment]
Sorry, looks like I read your question a bit too fast. To be honest, I have not seen this before. The only thing I could offer right now is to double-check your connection settings, comparing the one from Query with the one from the Collector. 

You could also post the logs from your collector and query, perhaps we can spot something that you haven't...

**Comment by weeco** [comment]
I believe the elasticsearch configuration is fine and it can also connect to Elasticsearch. When I use a wrong config the query service does log that on startup like this:

```json
{"level":"info","ts":1572364318.4869714,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1572364318.4872856,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1572364318.487388,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":16687}
{"level":"info","ts":1572364318.487408,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":16687,"health-status":"unavailable"}
{"level":"fatal","ts":1572364324.5567038,"caller":"query/main.go:88","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: Head https://logging-es-http.elastic-system.svc:9201: context deadline exceeded","errorVerbose":"Head https://logging-es-http.elastic-system.svc:9201: context deadline exceeded\nfailed to create primary Elasticsearch client\ngithub.com/jaegertracing/jaeger/plugin/storage/es.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/factory.go:83\ngithub.com/jaegertracing/jaeger/plugin/storage.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/factory.go:108\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/main.go:87\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/main.go:130\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/main.go:88\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/query/main.go:130\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}
```

With the correct ElasticSearch settings the log looks fine:

```json
kubectl logs -f jaeger-query-74db5fd5c5-l2cr6
2019/10/29 16:03:37 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
{"level":"info","ts":1572365017.8689969,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1572365017.8692174,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1572365017.8693018,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":16687}
{"level":"info","ts":1572365017.869334,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":16687,"health-status":"unavailable"}
{"level":"info","ts":1572365017.9112318,"caller":"config/config.go:172","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1572365017.9125092,"caller":"healthcheck/handler.go:130","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1572365017.91256,"caller":"app/server.go:135","msg":"Starting CMUX server","port":16686}
{"level":"info","ts":1572365017.9125957,"caller":"app/server.go:112","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1572365017.9126284,"caller":"app/server.go:125","msg":"Starting GRPC server","port":16686}
```

I tend to believe that the query UI is for some reason not able to see/query the data in Elasticsearch (maybe because I am using ES v7?). 


Collector logs:

```json
kubectl logs -f jaeger-collector-556598c676-8qs6c
2019/10/29 12:42:47 maxprocs: Updating GOMAXPROCS=2: determined from CPU quota
{"level":"info","ts":1572352967.9401166,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1572352967.94039,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1572352967.9405358,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1572352967.9405482,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1572352968.021824,"caller":"config/config.go:172","msg":"Elasticsearch detected","version":7}
{"level":"info","ts":1572352968.6172075,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1572352968.6176662,"caller":"collector/main.go:128","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1572352968.6177654,"caller":"grpcserver/grpc_server.go:102","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1572352968.617974,"caller":"collector/main.go:147","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1572352968.618001,"caller":"healthcheck/handler.go:130","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1572352968.6600127,"caller":"collector/main.go:242","msg":"Listening for Zipkin HTTP traffic","zipkin.http-port":9411}
```

Kubernetes deployment of query component:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jaeger
    component: query
  name: jaeger-query
  namespace: jaeger
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jaeger
      component: query
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "16687"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: jaeger
        component: query
      namespace: default
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jaeger
                - key: component
                  operator: In
                  values:
                  - query
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jaeger
                - key: component
                  operator: In
                  values:
                  - query
              topologyKey: kubernetes.io/hostname
            weight: 20
      automountServiceAccountToken: false
      containers:
      - env:
        - name: QUERY_BASE_PATH
          value: /
        - name: SPAN_STORAGE_TYPE
          value: elasticsearch
        - name: ES_SERVER_URLS
          value: https://logging-es-http.elastic-system.svc:9200
        - name: LOG_LEVEL
          value: debug
        - name: ES_TLS_CA
          value: /etc/jaeger/elasticsearch-certs/ca.crt
        image: jaegertracing/jaeger-query:1.14.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: query
        ports:
        - containerPort: 16686
          name: ui
          protocol: TCP
        - containerPort: 16687
          name: health
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: health
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - mountPath: /etc/jaeger/elasticsearch-certs
          name: elasticsearch-certs
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-nodepool: default-v2
      securityContext: {}
      volumes:
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: logging-es-http-certs-public
```
