### ISSUE TITLE
showing latest traces not working properly using all-in-one with badger

### ISSUE THREAD

**Issue by flixr** [jaegertracing/jaeger#1913]
## Requirement - what kind of business use case are you trying to solve?

Seeing the latest traces while limiting the number of results.

## Problem - what in Jaeger blocks you from solving the requirement?

With all-in-one 1.15.1 I don't get the latest X traces anymore, but it seems rather the traces with highest trace ID first.
With 1.14 I correctly get the _latest_ X number of traces, regardless of their trace id.

Running jaeger/all-in-one via docker:
```
jaeger:
    image: jaegertracing/all-in-one:1.15.1
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
      - "SPAN_STORAGE_TYPE=badger"
      - "BADGER_EPHEMERAL=false"
      - "BADGER_DIRECTORY_VALUE=/badger/data"
      - "BADGER_DIRECTORY_KEY=/badger/key"
    volumes:
      - jaeger-storage:/badger
    expose:
      - "9411"
      - "16686"
    ports:
      - "16686:16686"
```
Just changing back to 1.14 shows me the latest (e.g. 20) traces again.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

It seems like the search is now giving back the first X number of traces in the given time range based on the highest traceID instead of latest time.
The behavior in 1.14 was correctly returning the latest traces first.
