### ISSUE TITLE
Elasticsearch alias config requires max-span-age to be configured

### ISSUE THREAD

**Issue by fischerman** [jaegertracing/jaeger#2138]
The docs for ES aliases suggest that `es.max-span-age` is not relevant if index aliases are enabled.
```
--es.use-aliases
(experimental)  Use read and write aliases for indices. Use this option with  Elasticsearch rollover API. It requires an external component to create  aliases before startup and then performing its management. Note that  es.max-span-age is not taken into the account and has to be substituted  by external component managing read alias.
```
We've noticed that traces, that are older than 72 hours (the default value of max span age) return a 404. Increasing the max span age resolved the problem. 

Am I misunderstanding the docs or is this a bug?

Jaeger version 1.17

**Comment by pavolloffay** [comment]
Just to confirm is your jaeger query configured with `--es.use-aliases=true`?

**Comment by fischerman** [comment]
Yes. To be precise, we use environment variables:
```
        env:
          - name: SPAN_STORAGE_TYPE
            value: elasticsearch
          - name: ES_SERVER_URLS
            value: http://{{ inv.jaeger.es.host }}:9200
          - name: ES_USE_ALIASES
            value: "true"
```
