### ISSUE TITLE
Review any security implications with OpenTelemetry Collector Jaeger receivers/exporters

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger#2156]
Re: https://github.com/jaegertracing/jaeger/issues/1718

1. Client To Agent
    1. UDP Channels - still no TLS/authentication :+1: 
    1. HTTP Config Channel - still no TLS/authentication :+1: 
1. Client To Collector
    1. HTTP - still no TLS/authentication :+1: 
1. Agent To Collector
    1. gRPC - TLS with client cert authentication: Exporter :+1: Receiver :-1: (see jaegertracing/jaeger-opentelemetry-collector#22)
1. Collector To Storage (relevant if storage implemented as exporters)
    1. Cassandra - TLS with client cert authentication supported (TO BE CONFIRMED)
    1. Elasticsearch - TLS with client cert authentication supported; bearer token propagation (TO BE CONFIRMED)
    1. Kafka - Kerberos authentication supported (TO BE CONFIRMED)

**Comment by yurishkuro** [comment]
what is the goal of this ticket vs. #1718?

**Comment by objectiser** [comment]
This was moved from the jaeger-opentelemetry-collector repo, so was referring to security implications related to OpenTelemetry Collector receivers/exporters.

**Comment by pavolloffay** [comment]
4) Storage exporters support all auth mechanisms.

The missing part is the TLS configuration in Jaeger gRPC exporter. I will submit a PR to OTEL.

**Comment by pavolloffay** [comment]
Replicated @jpkrohling deployment from https://github.com/jaegertracing/jaeger-opentelemetry-collector/issues/22 with Jaeger OTEL components. It uses TLS between agent and collector. But we need also mTLS.

Jager OTEL collector: `SPAN_STORAGE_TYPE=elasticsearch go run ./cmd/collector/main.go --config=conf.yaml --new-metrics=true`
```yaml
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: "localhost:14250"
        tls_credentials:
          cert_file: /home/ploffay/projects/opentelemetry/opentelemetry-collector/receiver/jaegerreceiver/testdata/certificate.pem
          key_file: /home/ploffay/projects/opentelemetry/opentelemetry-collector/receiver/jaegerreceiver/testdata/key.pem

service:
  pipelines:
    traces:
      receivers: [jaeger]
```
Jaeger OTEL agent: `go run ./cmd/agent/main.go --config=conf-agent.yaml --metrics-addr=:8889 --new-metrics=true`
```yaml
exporters:
  jaeger:
    endpoint: "localhost:14250"
    cert_pem_file: /home/ploffay/projects/opentelemetry/opentelemetry-collector/receiver/jaegerreceiver/testdata/certificate.pem
    server_name_override: opentelemetry.io

extensions:
  health_check:
    port: 13134
```
