### ISSUE TITLE
Observing many <trace-without-root-span> with streaming strategy

### ISSUE THREAD

**Issue by huikang** [jaegertracing/jaeger#2177]
I experimented with both the `production` and `streaming` strategy to collect trace from the same application. The `production` strategy works correctly, while there are many `<trace-without-root-span> ` in the query UI under the `streaming` strategy.

Following is the yaml file
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-streaming
spec:
  strategy: streaming
  collector:
    options:
      kafka: # <1>
        producer:
          topic: jaeger-spans
          brokers: my-cluster-kafka:9094
  ingester:
    options:
      kafka: # <1>
        consumer:
          topic: jaeger-spans
          brokers: my-cluster-kafka:9094
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-client.default.svc:9200
```

Could anyone help to provide any guidance to fix the issue? Thanks.
