### ISSUE TITLE
Should be Jaeger flags applied to all components or all only to the default configuration

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2223]
At the moment flags provide default values for all component configs. Should we keep this behavior or change it so that the flags work only in default/hardcoded configuration.

Let me illustrate:

The following configuration will have two Elasticsearch exporters - `jaeger_elasticsearch` and `jaeger_elasticsearch/custom` both will use 1 shard (default is 5). The first one will use `foo` as URL and the second one `bar` (otel config always overrides Jaeger https://github.com/jaegertracing/jaeger/issues/2209).

```
jaeger-opentelemetry-collector --es.num_shars=1 --es.server_urls=foo
exporter:
  jaeger_elasticsearch/custom:
    server_urls: bar

service:
  pipelines:
    traces:
      exporters: [jaeger_elasticsearch, jaeger_elasticsearch/custom]
```

The configuration precedence should be as simple as possible and easy to understand by users.
