### ISSUE TITLE
Expired spans in badger still exists in disk even after long time

### ISSUE THREAD

**Issue by vasanth29797** [jaegertracing/jaeger#2266]
## what kind of business use case are you trying to solve?

Using all-in-one:1.18 docker image with badger as storage in Azure Kubernetes Service

## Problem - what in Jaeger blocks you from solving the requirement?

Expired data (spans) and its metadata are not purged from disk and memory even after hours from its expiry time.

**Kubernetes deployment file**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-tracing
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
    spec:
        containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.18"
          imagePullPolicy: IfNotPresent
          env:
          - name: BADGER_EPHEMERAL
            value: "false"
          - name: SPAN_STORAGE_TYPE
            value: "badger"
          - name: BADGER_DIRECTORY_VALUE
            value: "/badger/data"
          - name: BADGER_DIRECTORY_KEY
            value: "/badger/key"
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: QUERY_BASE_PATH
            value:  /jaeger 
          - name: BADGER_SPAN_STORE_TTL
            value: 10m
          volumeMounts:
          - name: storage-volume
            mountPath: /badger/
          resources: {}
```

## Details:

I set span TTL as 10 minutes. Didn't set constraint on resources.  Spans once expired cannot be queried from jaeger UI. This is working as expected. But the data associated with those spans (key and value) are still in disk (PVC), even after 2 hours from its expiry time. I think the keys associated with those spans + some metadata are still in memory as well. The effect of GC and compaction aren't much. 

Jaeger instance received only 756K spans from its start and after that it didn't receive new spans.

**prometheus metrics after 2 hours from expiry time**

jaeger_badger_lsm_size_bytes - 330 MiB
jaeger_badger_vlog_size_bytes - 211 MiB

memory usage - 640 MiB
pvc usage - 508 MIB

directory wise:

data - 177.5 MiB (1 vlog file)
key - 330 MiB (6 sst file)

I am planning to use this jaeger instance in production although I am aware of other storage options. So this will become a serious issue atleast memory-wise when jaeger receives very high number of spans.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Cleaning up expired data in regular/consistent fashion, so both pvc and memory usage should come near to a state where jaeger was when it spawned up.

## Any open questions to address

In issue https://github.com/dgraph-io/badger/issues/1124, they mentioned the newer version of badger v2.0.0 will solve this. I think jaeger v1.18 uses badger v1.5.3. When jaeger uses newer version of badger, will this issue be resolved?
