### ISSUE TITLE
esCleaner.py fails to run with istio sidecar

### ISSUE THREAD

**Issue by snuggie12** [jaegertracing/jaeger#2283]
**Describe the bug**
I have istio 1.5.4 installed and the sidecar is being deployed to all components of jaeger. Services such as collector are able to handle issues at startup since the container will restart and after istio is setup everything succeeds. This is not true for the esCleaner (possibly other jobs.)

Possible solutions I see:
- Rescue a connection refused exception and retry some configurable amount of tries.
- Change the restart policy on the job to be OnFailure (perhaps this has too much potential for destruction?)
- Run a pre-check until the port is open and exit after some configurable amount of tries.

**To Reproduce**
1. Launch and configure istio
2. In the Jaeger resource, set spec.annotations.sidecar.istio.io/inject = "true" and setup jaeger to use elasticsearch
3. Wait for the cron job to fire and view the logs on the es index cleaner container.

**Expected behavior**
Container manages a temporary lack of connection to ES at startup

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.18
 - Deployment: Kubernetes 1.15 on GKE

**What troubleshooting steps did you try?**
Tried to see if there is a way to restart just the container with kubelet but did not succeed. Tried to kill the container before noticing the restart policy was set to never.

**Additional context**
Logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by pavolloffay** [comment]
@snuggie12 thanks for reporting the issue. We will need more information to understand the issue.

How is the Jaeger instance deployed? 

If it is deployed via Jaeger Operator then paste here the content of Jaeger CR. If it's deployed via other systems provide the config for those or paste the manifest of Jaeger collector `kubectl get deployment/jaeger-collector`.

**Comment by snuggie12** [comment]
@pavolloffay A little confused why you would want the jaeger-collector yaml. If it's because I mentioned it in my example I was merely comparing restart policies between any `Deployment` vs the esCleaner `Job`. I've clarified a bit in my summary as my collector actually talks to kafka.

I'm using the operator with istio mTLS on for all components (see repro steps,) and my ES cluster also has mTLS on as well.

`Jaeger` CR (omitted parts not involved):
```
---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: default
spec:
  agent:
    ...
  annotations:
    sidecar.istio.io/inject: "true"
  collector:
    ...
  ingester:
    options:
      kafka:
        consumer:
          brokers: jaeger-kafka-brokers.default:9092
          topic: jaeger-spans
  ingress:
    enabled: false
  storage:
    options:
      es:
        index-prefix: traces
        server-urls: http://jaeger-es-http.default.svc:9200
    secretName: jaeger-es-auth
    type: elasticsearch
  strategy: streaming
```
