### ISSUE TITLE
Unable to connect to Elasticsearch on AWS 

### ISSUE THREAD

**Issue by otherview** [jaegertracing/jaeger#2291]
Hi 👋 !

I've been trying to disable sniffing for Elasticsearch, but no luck.
Using the official chart and connecting to AWS Elasticsearch.
Initially posted a question here https://github.com/jaegertracing/helm-charts/issues/122
But everything looks ok in the charts 🤔  Maybe I'm doing something wrong ?

Tried with the defaults and got `the failed to create primary Elasticsearch client with health check timeout - no Elasticsearch node available`

After I used
```
collector:
    cmdlineParams:
      es.sniffer: "false"
```
And no change 🤔 

From what I can tell this is related with using https://github.com/olivere/elastic . And because I'm using an AWS Elasticsearch theres an issue when it sniffs the available nodes.

Any help would be much appreciated ! :)

**Comment by pavolloffay** [comment]
Sniffer is disabled by default - https://github.com/jaegertracing/jaeger/blob/6f3a169949bf97d736921147d3e23507762c2a26/plugin/storage/es/options.go#L82

There are Jaeger users using AWS Elasticsearch. This is most likely configuration issue. Could you please paste here all Jaeger ES configuration?

**Comment by otherview** [comment]
Thanks for reviewing this @pavolloffay 

My configs are pretty simple. 
```
jaeger:
  provisionDataStore:
    cassandra: false
    #elasticsearch: true
  storage:
    type: elasticsearch
    elasticsearch:
      host: AWS_HOST
      scheme: http
      port: 80

  collector:
    cmdlineParams:
      es.sniffer: "false"
```

Additionally everything is "open" on the AWS side
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:INSTANCE/search/*"
    }
  ]
}
```

So.. I'm really at a lost on why the sniffing is happening :\
