### ISSUE TITLE
Support for AWS managed Cassandra (aka AWS MCS, Amazon Keyspaces)

### ISSUE THREAD

**Issue by dahateb** [jaegertracing/jaeger#2294]
When trying to connect with the current Jaeger version to AWS MCS, the jaeger-collector connection fails with the following Error message:
> Consistency level ANY is not supported for this operation. Supported consistency levels are: ONE, LOCAL_QUORUM, LOCAL_ONE

This happens even with the commandline flag --cassandra.consistency=LOCAL_QUORUM

**To Reproduce**
1. run jaeger collector with AWS MCS configured (cassandra based  configuration with tls)

**Expected behavior**
jaeger-collector is connecting with AWS MCS

**Screenshots**

**Version (please complete the following information):**
 - OS: Amazon Linux (EKS 1.14)
 - Jaeger version: 1.18
 - Deployment: Kubernetes

deployment.yaml

```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-jaeger-collector
  labels:
    helm.sh/chart: jaeger-0.32.0
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.18.0"
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/component: collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config-env: fa599e48dfc1f40406f1b54ab64978c6cff37b3b96238cd1249f7cfdec30b956
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: collector
    spec:
      securityContext:
        {}
        
      serviceAccountName: release-name-jaeger-collector
      containers:
      - name: release-name-jaeger-collector
        securityContext:
          {}
          
        image: jaegertracing/jaeger-collector:1.18.0
        imagePullPolicy: IfNotPresent
        args:
          - --cassandra.consistency=LOCAL_QUORUM
          
        env:
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: SPAN_STORAGE_TYPE
            value: cassandra
          - name: CASSANDRA_SERVERS
            value: cassandra.eu-central-1.amazonaws.com
          - name: CASSANDRA_PORT
            value: "9142"
          
          - name: CASSANDRA_KEYSPACE
            value: XXXX
          - name: CASSANDRA_USERNAME
            value: XXXX
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: release-name-jaeger-cassandra
                key: password
          - name: "CASSANDRA_TLS"
            value: "true"
          
          - name: "CASSANDRA_TLS_SERVER_NAME"
            value: "cassandra.eu-central-1.amazonaws.com"
          
          - name: SAMPLING_STRATEGIES_FILE
            value: /etc/conf/strategies.json
        ports:
        - containerPort: 14250
          name: grpc
          protocol: TCP
        - containerPort: 14268
          name: http
          protocol: TCP
        - containerPort: 14269
          name: admin
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: admin
        livenessProbe:
          httpGet:
            path: /
            port: admin
        resources:
          {}
          
        volumeMounts:
          - name: cassandra-tls-secret
            mountPath: /root/.cassandra/ca-cert.pem
            subPath: ca-cert.pem
            readOnly: true
          - name: strategies
            mountPath: /etc/conf/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: cassandra-tls-secret
          secret:
            secretName: cassandra-tls-secret
        - name: strategies
          configMap:
            name: release-name-jaeger-sampling-strategies
``` 

**Additional context**
might be related to this fixed issue in gocql
https://github.com/gocql/gocql/pull/1422
