### ISSUE TITLE
Duplicate tag span.kind=server

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger#2321]
**Describe the bug**

Data reported by to OTEL service in Jaeger format might get duplicated tag `span.kind=server`. The tag is probably duplicated during the model conversion. 

**To Reproduce**
1.  `docker run -it --rm -e "ES_JAVA_OPTS=-Xms2g -Xmx2g" -p 9200:9200 -p 9300:9300 -e "http.host=0.0.0.0" -e "discovery.type=single-node" --name=elasticsearch docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.4`
2. `SPAN_STORAGE_TYPE=elasticsearch go run -tags ui ./cmd/all-in-one/main.go --new-metrics=true` (after PR https://github.com/jaegertracing/jaeger/pull/2295)
3. open Jaeger UI and create some requests. The first span from traces reported by query service has a warning `Duplicate tag "span.kind:server"`

**Expected behavior**

A single span kind tag

**Comment by albertteoh** [comment]
Tried reproducing the issue to understand the problem, off master (which includes #2295), but seeing the following error:
```
$ SPAN_STORAGE_TYPE=elasticsearch go run -tags ui ./cmd/all-in-one/main.go --new-metrics=true
2020/07/19 10:40:44 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
Error: unknown flag: --new-metrics
```

Removing the `--new-metrics` flag managed to get the all-in-one running, but I could not see the duplicate tag warnings in Jaeger UI for the traces generated on the `jaeger-query` service, mentioned in the description.

What steps am I missing in order to reproduce the problem successfully?

**Comment by pavolloffay** [comment]
Maybe the issue has been fixed in the Jaeger translator in OTEL repo. The `--new-metrics` also probably changed.

You did a good job by trying to reproduce it. I will have a look again at this soon. You could try to use a different application (e.g. hotrod) and wee whether reported data looks fine.

**Comment by schickling** [comment]
I'm seeing duplicates for the `status.code`. A possible correlation might be when errors occur. (I have to investigate further to confirm with confidence.)

Setup: 

OpenTelemetry JS client + the following Jaeger setup running in Docker:

```yml
version: '3'

services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    command: ['--config-file=/config/config.yaml']
    container_name: jaeger
    # environment:
    # - SPAN_STORAGE_TYPE=badger
    # - BADGER_EPHEMERAL=true
    # - BADGER_DIRECTORY_VALUE=/badger/data
    # - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - ./config.yaml:/config/config.yaml
      # - ./badger:/badger
    ports:
      - "6831:6831/udp"
      - '6832:6832/udp' # incoming traces
      - '16686:16686' # Jaeger UI
      - '55679:55679' # zpages
      - '13133:13133' # health check
    restart: on-failure

```
