### ISSUE TITLE
jaeger collector error during start (docker swarm)

### ISSUE THREAD

**Issue by goolzerg** [jaegertracing/jaeger#2342]
## Describe the bug
Jaeger-collector doesn't start (crash after start attempt).
I use ES as a backend storage and latest version of jaeger-collector.

Can't figure out how to solve this problem. Logs aren't enough informative in this case.
```
2020/07/14 14:34:55 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS,
{"level":"info","ts":1594748310.2356703,"caller":"server/zipkin.go:48","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":0"},
{"level":"info","ts":1594737295.3381145,"caller":"flags/service.go:116","msg":"Mounting metrics handler on admin server","route":"/metrics"},
{"level":"info","ts":1594748310.2700994,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"},
{"level":"info","ts":1594737295.3384924,"caller":"flags/admin.go:120","msg":"Mounting health check on admin server","route":"/"},
{"level":"info","ts":1594737295.3385606,"caller":"flags/admin.go:126","msg":"Starting admin HTTP server","http-addr":":14269"},
{"level":"info","ts":1594737295.3385816,"caller":"flags/admin.go:112","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"},
{"level":"info","ts":1594737295.3952463,"caller":"config/config.go:176","msg":"Elasticsearch detected","version":7},
{"level":"info","ts":1594737295.462271,"caller":"static/strategy_store.go:145","msg":"No sampling strategies provided, using defaults"},
{"level":"info","ts":1594737295.4672072,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"},
{"level":"info","ts":1594737295.467232,"caller":"server/http.go:44","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"},
{"level":"info","ts":1594737295.4674172,"caller":"server/zipkin.go:48","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":9411"},
{"level":"info","ts":1594737295.505003,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"},
{"level":"info","ts":1594748308.7199206,"caller":"flags/service.go:146","msg":"Shutting down"},
{"level":"info","ts":1594748308.7200391,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"unavailable"},
{"level":"info","ts":1594748308.721421,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"unavailable"},
{"level":"fatal","ts":1594748308.7214606,"caller":"server/zipkin.go:79","msg":"Could not launch Zipkin server","error":"http: Server closed","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app/server.serveZipkin.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/server/zipkin.go:79"},
```

## To Reproduce
Start jaeger-collector with ES backend storage inside swarm cluster.

## Expected behavior
Jaeger-collector starts correctly.

**Comment by jpkrohling** [comment]
Could you provide your swarm configuration?

**Comment by sushant-at-nitor** [comment]
This is an issue with non swarm mode as well:

```
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    healthcheck:
      test: exit 0
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 1m
    restart: always
```
