### ISSUE TITLE
Error: invalid Go type model.TraceID for field jaeger.api_v2.Span.trace_id (Badger storage)

### ISSUE THREAD

**Issue by schickling** [jaegertracing/jaeger#2367]
**Describe the bug**

I've switched out the `JaegerExporter` for the [`CollectorTraceExporter`](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-exporter-collector) in my Node app. When trying to view the recorded traces via the Jaeger UI or use the Jaeger Query API, I'm seeing the following error: `invalid Go type model.TraceID for field jaeger.api_v2.Span.trace_id`

![image](https://user-images.githubusercontent.com/1567498/89121242-84320700-d4bd-11ea-9334-3a3d70ce4deb.png)

**To Reproduce**

`docker-compose.yml`

```yml
version: '3'

services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    command: [
        '--config-file=/config/config.yaml',
        '--badger.ephemeral=false',
        '--badger.directory-value=/badger/data',
        '--badger.directory-key=/badger/key',
      ]
    container_name: jaeger
    environment:
      SPAN_STORAGE_TYPE: 'badger'
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - ./badger:/badger
    ports:
      - '55680:55680'
      - '55681:55681'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '16686:16686'

```

`config.yaml`

```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
        - http://*
        - https://*

processors:
  batch:
  queued_retry:

exporters:
  jaeger_badger:
    ephemeral: false
    # directory_key: key
    directory_key: /badger/key
    directory_data: /badger/data

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger_badger]
```

Example node app to reproduce: https://github.com/open-telemetry/opentelemetry-js/blob/master/examples/collector-exporter-node/start.js

**Expected behavior**

This error shouldn't occur.

**Version (please complete the following information):**

 - OS: `Linux v220200727333122057 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`
 - Jaeger version: `1.18.1`
 - Deployment: Local via docker-compose
