### ISSUE TITLE
Memory peaks on agent v1.19.2

### ISSUE THREAD

**Issue by zigmund** [jaegertracing/jaeger#2452]
**Describe the bug**
One group of jaeger agents (3 replicas), deployed on kubernetes. Not so loaded system - 500-700 spans per second.
Used v1.13.1 for year without any issues, upgraded all componenet to 1.19.2 (also replaced Tchannel with gRPC) and agent memory usage become unstable. Before upgrade agent instances used as low as 16 mb with 64 limit, but after upgrade memory usage peaks appeared and agent got oomkilled. I raised limits, but even 512 mb is not enough.

After few hours and tens of oomkills, I downgraded agent to 1.18.1 version and see no issues so far.

**To Reproduce**
1. Deploy agent v1.19.2
2. Send 500-700 spans per second
3. ???
4. Observe memory usage peaks.

**Expected behavior**
Agent memory usage close to lower versions.

**Screenshots**
![image](https://user-images.githubusercontent.com/1713091/92070460-dbcdd600-edcd-11ea-82eb-066d60b948df.png)

**Version (please complete the following information):**
 - OS: Kubernetes nodes based on Ubuntu 20.04 LTS, 5.4.0-39 kernel
 - Jaeger version: 1.19.2
 - Deployment: Kubernetes

**What troubleshooting steps did you try?**
Collected /metrics, will provide if needed.

**Additional context**
-

**Comment by jpkrohling** [comment]
When you downgraded to 1.18.1, did you change any other configuration? Would you mind sharing your agent configuration?

**Comment by zigmund** [comment]
@jpkrohling the only agent parameter used before and after downgrade is `--reporter.grpc.host-port=jaeger-collector:14250`.

Also played for a while after got first OOMkills with parameters, but reverted changes singe they didn't helped much:
```
        - --processor.jaeger-binary.server-queue-size=...
        - --processor.jaeger-binary.workers=...
        - --processor.jaeger-compact.server-queue-size=...
        - --processor.jaeger-compact.workers=...
        - --processor.zipkin-compact.server-queue-size=...
        - --processor.zipkin-compact.workers=...
```

**Comment by jpkrohling** [comment]
I'll take a look at list of commits affecting the agent between 1.18.1 and 1.19.2, perhaps I can spot a suspect there. I'll also try to reproduce the problem here. Do you think it would be reproducible with `minikube` and a simple agent with 64Mi of requests , 256Mi limit? Jaeger's `tracegen` would probably generate enough load ;-)

**Comment by jpkrohling** [comment]
@zigmund I'll need your help here. I tried to reproduce your problem but didn't succeed. I have a local minikube cluster with 20Gi of memory available, initialized with:

```console
$ minikube start --vm-driver kvm2 --cpus 6 --memory 20480 --container-runtime=crio --addons=ingress
```

Using the Jaeger Operator, I provisioned a Jaeger instance with the following spec:

```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: agent-as-daemonset
spec:
  agent:
    image: jaegertracing/jaeger-agent:latest
    strategy: DaemonSet
    resources:
      requests:
        memory: 64Mi
      limits:
        memory: 256Mi
  storage:
    options:
      memory:
        max-traces: 100000
```

And here's a trace generator, creating 1 trace per millisecond:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracegen
  annotations:
    "sidecar.jaegertracing.io/inject": "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracegen
  template:
    metadata:
      labels:
        app: tracegen
    spec:
      containers:
      - name: tracegen
        image: jaegertracing/jaeger-tracegen:1.19.2
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        args:
        - -pause=1ms
        - -duration=1h
        - -workers=1
```

The agent pod was up for the whole time, and the metrics shows me that the agent didn't even blink. I changed the Jaeger CR to use 1.18.1, to see if `latest` was in the same ballpark, and I couldn't spot any differences:

![Screenshot_2020-09-03 Prometheus Time Series Collection and Processing Server](https://user-images.githubusercontent.com/13387/92110177-99ff5880-edea-11ea-9b01-b223969aaf8b.png)

The first part of the graph is for an early test, where I set the tracegen to have 10 workers and no pause. I also forgot to set the pod limits and left for lunch. If I'm reading this data correctly, it shows about 200Mi of memory consumption for about 4M spans per minute.

The second part is `jaegertracing/jaeger-agent:latest`, with a 64Mi of requests and 256Mi of limit. The tracegen is with a pause of 1ms and 1 worker. 

The third part is the same a second part, only with `jaegertracing/jaeger-agent:1.18.1` as the image.

Here's how I need your help: are you able to reproduce your performance problems based on this setup? If you can't, could you perhaps then run a `git bisect` with the first good commit being `v1.18.1` and the bad as being `v1.19.2`? Like:

```console
$ git bisect start 
$ git bisect good v1.18.1
$ git bisect bad v1.19.2
$ make docker # this is the easiest, but will build everything, which might take a while
$ podman tag jaegertracing/jaeger-agent:latest quay.io/jpkroehling/jaeger-agent:issue2452-step1
$ podman push quay.io/jpkroehling/jaeger-agent:issue2452-step1
```

Change the last two commands accordingly, to tag and push to a namespace you own. At this point, configure your agent to use the image you just pushed. 

If you don't have Jaeger source code locally to run the previous steps, you should probably do this first (see [CONTRIBUTING.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING.md)):
```console
$ git clone https://github.com/jaegertracing/jaeger.git
$ cd jaeger
$ git submodule update --init --recursive
$ make install-tools
```
