### ISSUE TITLE
Multi-tenant Jaeger

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#2509]
## Requirement - what kind of business use case are you trying to solve?

The topic of multi-tenancy has being brought up quite a few times in the past. So far, our response has been that Jaeger is lightweight enough to have one instance per tenant, which is easier to manage with a provisioning tool like Helm or the Jaeger Operator.

That said, it would still be advantageous to be able to run one instance of Jaeger for all tenants, or to a set of tenants.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

The proposal, after brainstorming with @pavolloffay, @objectiser, @rubenvp8510, @kevinearls and @jkandasa is the following:

- Change the Agent, so that it can be configured to read a bearer token (flag/file)
- Use this token for all RPC's to the collector
- Collector/Query/UI can be configured to read a tenant configuration file. This configuration file can look like the example below
- The UI is already able to propagate the token to the backend, so, no changes are required there
- Both the Collector and the Query will be responsible for authenticating the incoming requests, using a new shared package

This is how the tenant configuration file could look like:

```yaml
tenants:
# a concrete tenant, highest precedence
- value: globex
  storageType: cassandra
  cassandra:
    servers: xyz
    port: 1234
# a set of tenants matching some regex, also matches "globex" but we have a specific entry for it already, second in precedence
- regex: ^globex[\-\d]*$
  storageType: elasticsearch
  es:
    # %s is replaced with the actual, concrete tenant name
    server-urls: "es.%s.globex.example.com"
# all other tenants, not matching anything that came earlier
default:
  storageType: elasticsearch
  es:
    server-urls: "big-cluster.es.acme.example.com"
    index-prefix: "jaeger-%s"
```
