### ISSUE TITLE
Jaeger query not picking up from Elasticsearch

### ISSUE THREAD

**Issue by foggy-glasses** [jaegertracing/jaeger#2699]
Hello..
I'm trying to setup Jaeger (production strategy) on an EKS cluster which has multiple services in multiple namespaces. I've followed the guide here https://www.jaegertracing.io/docs/next-release/operator/ and hooked it up to an elasticsearch storage that's running on the same VPC but on an EC2 machine. I've configured the jaegery-query basepath as /trace and hooked the setup to an nginx ingress.

The jaeger operator and other components are deployed in the observability namespace and I've configured one of my deployments in another namepace (added the annotation to deploy the jaeger sidecar) to use Jaeger. I can now see the traces being populated in Elasticsearch. However, the same doesn't show up in the jaeger UI. I can't even see the default jaeger-query as part of the traces.

Here's my YAML deployment file for the Jaeger instance.
```
# Create the Jaeger instance
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: production
  collector:
    maxReplicas: 20
    options:
      log-level: debug
      es:
        use-aliases: true
        server-urls: http://ec2elasticsearch:9200
    secretName: jaeger-secret
  storage:
    type: elasticsearch
    options:
      es:
        create-index-templates: false
        server-urls: http://ec2elasticsearch:9200
        num-replicas: 0
        index-prefix: test
    secretName: jaeger-secret
  query:
    options:
      log-level: debug
      es:
        use-aliases: true
        server-urls: http://ec2elasticsearch:9200
      query:
        base-path: /trace
    secretName: jaeger-secret
  ingress:
    enabled: false
  ui:
    options: 
      log-level: debug
      dependencies:
        menuEnabled: true
```
The collector and query logs don't show any errors. I've looked at another issue here which deals with something similar. However, it hasn't helped solved this issue. Is there something I'm missing?
