### ISSUE TITLE
Jaeger Agent  - collector.host value from configmap not updating dynamically

### ISSUE THREAD

**Issue by raz08** [jaegertracing/jaeger#2879]
I have a configmap and I'm passing these configmap values as ENV variables in Jaeger agent daemon set deployment file. But when i update collector.host in configmap , it is not getting reflected in Jaeger agent.

Configmap
```
apiVersion: v1
data:
  admin-http-port: "14271"
  collector.host-port: 1.1.1.1:14267
  metrics-backend: prometheus
  metrics-http-route: /metrics
```

Daemonset

```
      containers:
      - name: {{ template "jaeger.agent.name" . }}
        env:
        - name: COLLECTOR_HOST_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ template "jaeger.agent.name" . }}
              key: collector.host-port
        - name: METRICS_BACKEND
          valueFrom:
            configMapKeyRef:
              name: {{ template "jaeger.agent.name" . }}
              key: metrics-backend
        - name: METRCIS_HTTP_ROUTE
          valueFrom:
            configMapKeyRef:
              name: {{ template "jaeger.agent.name" . }}
              key: metrics-http-route
        - name: ADMIN_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ template "jaeger.agent.name" . }}
              key: admin-http-port
```

How to make this works dynamically? If I update configmap it should load/reload configuration and start connecting to updated collector.host . Help is appreciated.
