### ISSUE TITLE
How to speed up consumer action in Jaeger ingester

### ISSUE THREAD

**Issue by judyQD** [jaegertracing/jaeger#2927]
**Describe the bug**
I am using tracegen --> collector -->> kafka -->ingester --> ES. 
And I found that it's kind of slow for ingester to pull spans in Kafka.
![image](https://user-images.githubusercontent.com/40418782/113823716-8fa6a200-97b1-11eb-992a-540539129fc4.png)

Ingester configuration is as below:

```
      es.bulk.actions: 1000,
      es.bulk.flush-interval: 200ms
      es.bulk.size: 5e+06
      es.bulk.workers: 50
      es.create-index-templates: true
      es.index-prefix: "zts_dnt_jaeger"
      es.max-doc-count: 10000
      es.max-span-age: 72h0m0s
      es.num-replicas: 1
      es.num-shards: 5
      es.password: "qE3E&FE#2QslS9sdf&q"
      es.server-urls: "http://127.0.0.1:9200"
      es.sniffer: false
      es.sniffer-tls-enabled: false
      es.tags-as-fields.all: false
      es.tags-as-fields.config-file: ""
      es.tags-as-fields.dot-replacement: "@"
      es.tags-as-fields.include: ""
      es.timeout: 0s
      es.tls.ca: ""
      es.tls.cert: ""
      es.tls.enabled: false
      es.tls.key: ""
      es.tls.server-name: ""
      es.tls.skip-host-verify: false
      es.token-file:
      es.use-aliases: false
      es.username: "admin"
      es.version:
      log-level: info
      metrics-backend: "prometheus"
      metrics-http-route: "/metrics"
      ingester.deadlockInterval: 0s
      ingester.parallelism: 1000
      kafka.consumer.authentication: none
      kafka.consumer.brokers: "127.0.0.1:9092"
      kafka.consumer.client-id: "jaeger-ingester"
      kafka.consumer.encoding: "protobuf"
      kafka.consumer.group-id: "jaeger-ingester"
      kafka.consumer.kerberos.config-file: "/etc/krb5.conf"
      kafka.consumer.kerberos.keytab-file: "/etc/security/kafka.keytab"
      kafka.consumer.kerberos.password:
      kafka.consumer.kerberos.realm:
      kafka.consumer.kerberos.service-name: "kafka"
      kafka.consumer.kerberos.use-keytab: false
      kafka.consumer.kerberos.username:
      kafka.consumer.plaintext.password:
      kafka.consumer.plaintext.username:
      kafka.consumer.protocol-version:
      kafka.consumer.tls.ca: ""
      kafka.consumer.tls.cert: ""
      kafka.consumer.tls.enabled: false
      kafka.consumer.tls.key: ""
      kafka.consumer.tls.server-name: ""
      kafka.consumer.tls.skip-host-verify: ""
```

**Screenshots**
![image](https://user-images.githubusercontent.com/40418782/113823716-8fa6a200-97b1-11eb-992a-540539129fc4.png)
