### ISSUE TITLE
Need documentation on how to use private image repository

### ISSUE THREAD

**Issue by jimpete** [jaegertracing/jaeger#3067]
## Requirement - what kind of business use case are you trying to solve?

As a military installation, I want documentation on how to pull the images from new locations in the Jaeger Custom Resource instance 

## Problem - what in Jaeger blocks you from solving the requirement?

I cant find the place to put the spark, esIndexCleaner, esRollover, and esLookback images.  This seems to work except for those.

```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch-master.observability.svc:9200
  volumeMounts:
  - name: elastic-data
    mountPath: /usr/share/elasticsearch/data
  volumes:
  - name: elastic-data
    emptyDir: {}
  ingester:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-ingester
  agent:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-agent
  collector:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-collector
  query:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-query
  ingress:
    hosts:
      - jaeger.<my cluster>.<my internal domain>
      
# These do not work - need documentation how to specify these      
  spark:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/spark-dependencies
  esIndexCleaner:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-es-index-cleaner
  esRollover:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-es-rollover
  esLookback:
    image: docker-proxy.nexus.<my internal domain>/jaegertracing/jaeger-es-rollover
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Please document the specification of the images in the CRD
