### ISSUE TITLE
Jaeger Operator 1.22.1 generates collector Deployment with now obsolete COLLECTOR_ZIPKIN_HTTP_PORT property

### ISSUE THREAD

**Issue by wabrit** [jaegertracing/jaeger#3077]
**Describe the bug**
Folowing the instructions in the Kubernetes deployment guide for an All-in-One or Production deployment results in a deployment based on the image `jaegertracing/jaeger-operator:1.22.1`.

When run it produces an jaeger collector with the following:

```
spec:
      containers:
      - args:
        ...
        env:
        ...
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        image: jaegertracing/jaeger-collector:1.22.0
```

The `COLLECTOR_ZIPKIN_HTTP_PORT` property no longer works in Jaeger 1.22, which means that any Zipkin-instrumented applications will fail to push their spans to Jaeger.

Manually editing the above deployment to use the correct property `COLLECTOR_ZIPKIN_HOST_PORT` cures the problem, but if the operator is restarted the change is lost and its broken again.

**To Reproduce**
1. Follow the instructions for e.g. production deployment
2. Repoint a zipkin-instrumented app to send its spans to Jeager on port 9411 in the usual way
3. Observe the lack of spans arriving in Jaeger from that app

**Expected behavior**
It should not be necessary to hand-edit the dynamically created collector deployment in order for zipkin-instrumented app spans to arrive in Jaeger.

**Version (please complete the following information):**
 - Jaeger version: 1.22.1
 - Deployment: Kubernetes
