### ISSUE TITLE
`agent.tags` parsing error for Elastic Cloud

### ISSUE THREAD

**Issue by Aaronontheweb** [jaegertracing/jaeger#3351]
**Describe the bug**
While following the instructions for exporting spans from Jaeger Agents to Elastic Cloud https://github.com/elastic/apm/issues/212, I've not been able to get the recommended `agent.tags` format for the given agent to parse correctly using CLI arguments or the `JAEGER_TAGS` environment variable for the client.

```
--reporter.grpc.tls.enabled=true
--reporter.grpc.host-port=$(ELASTIC_APM_URI)
--agent.tags="elastic-apm-auth=Bearer ${ELASTIC_APM_TOKEN}"
```

The agent starts up fine, but I get the following error whenever we attempt to transmit spans over gRPC:

```
{"level":"error","ts":1635462398.3329742,"caller":"grpc/reporter.go:74","msg":"Could not send spans over gRPC","error":"rpc error: code = PermissionDenied desc = unauthorized: anonymous access not permitted for agent
```

This is because the bearer token included in the span tags was not propagated in the correct format - even if I hard code the `ELASTIC_APM_TOKEN` value into the `agent.tags` value.

However, if I make the following call using the Jaeger C# client:

```csharp
var tracer = new Tracer.Builder(typeof(Startup).Assembly.GetName().Name)
                    .WithReporter(new CompositeReporter(remoteReporter, logReporter))
                    .WithSampler(sampler)
                    .WithScopeManager(
                        new ActorScopeManager())
                    .WithTag("elastic-apm-auth", "Bearer <hard coded value>");
```

Then that works fine and my spans arrive in Elastic Cloud no problem.

**To Reproduce**
Create an agent using the following configuration (using Kubernetes in my case):

```yaml
containers:
 - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.27
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
       - name: ELASTIC_APM_URI
          valueFrom:
            secretKeyRef:
              name: elastic-secrets
              key: ELASTIC_APM_URI
        - name: ELASTIC_APM_TOKEN
          valueFrom:
            secretKeyRef:
              name: elastic-secrets
              key: ELASTIC_APM_TOKEN
        args:
          - --reporter.grpc.tls.enabled=true
          - --reporter.grpc.host-port=$(ELASTIC_APM_URI)
          - --agent.tags="elastic-apm-auth=Bearer ${ELASTIC_APM_TOKEN}"
        resources:
          limits:
            memory: 50M
            cpu: 100m
          requests:
            memory: 50M
            cpu: 100m
```

Have a client propagate spans to it while using the `elastic-apm-auth=Bearer ${ELASTIC_APM_TOKEN}` tag - and if connected to Elastic Cloud you'll receive an authorization error. I'm not sure why you will - passing in the tag explicitly via the programmatic client configuration works fine, but not if you do it via environment variables or via the `agent.tags` property.

**Expected behavior**
The content and the format of the  `elastic-apm-auth=Bearer ${ELASTIC_APM_TOKEN}`  tag should be preserved.

**Edit**: fixed my YAML - had the relevant part commented out while I was troubleshooting.
