### ISSUE TITLE
ES rollover lookback: do not throw exception on no indices to remove from alias

### ISSUE THREAD

**Issue by jkandasa** [jaegertracing/jaeger#3368]
**Describe the bug**
ES rollover lookback pod crashes on no indices to remove from alias 

**Expected behavior**
Should print the message and exist as normal

**Version (please complete the following information):**
 - OS: linux, OCP 4.9
 - Jaeger version: 1.26
 - Deployment: OpenShift 4.9

#### Config
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: es-rollover
spec:
  ingress:
    security: none
  strategy: production
  storage:
    esIndexCleaner:
      enabled: false
      schedule: "*/2 * * * *"
      numberOfDays: 0
    esRollover:
      schedule: "*/5 * * * *"
      conditions: '{"max_age":"3m"}'
      readTTL: 1h
    type: elasticsearch
    options:
      es.use-aliases: true
    elasticsearch:
      nodeCount: 1
      storage:
        storageClassName: "standard"
        size: "5G"
      resources:
        requests:
          memory: "1Gi"
          cpu: "510m"
        limits:
          memory: "1Gi"
```

#### error:
```bash
$ oc get pods
NAME                                                        READY   STATUS             RESTARTS       AGE
elasticsearch-cdm-esrolloveresrollover-1-8556865546-mr5jf   2/2     Running            0              22m
es-rollover-collector-755c4c68d8-ft74p                      1/1     Running            0              21m
es-rollover-es-lookback-27263920--1-7mq8j                   0/1     CrashLoopBackOff   5 (107s ago)   5m1s
es-rollover-es-rollover-27263915--1-x9kn2                   0/1     Completed          0              11m
es-rollover-es-rollover-27263920--1-8psrh                   0/1     Completed          0              6m32s
es-rollover-es-rollover-27263925--1-jbhkl                   0/1     Completed          0              92s
es-rollover-es-rollover-create-mapping--1-g292k             0/1     Completed          0              21m
es-rollover-query-77f96f79ff-pc8zj                          2/2     Running            0              21m
```

```
Error: no indices to remove from alias jaeger-span-read
Usage:
  jaeger-es-rollover lookback http://HOSTNAME:PORT [flags]

Flags:
  -h, --help             help for lookback
      --unit string      used with lookback to remove indices from read alias e.g, days, weeks, months, years (default "days")
      --unit-count int   count of UNITs (default 1)

Global Flags:
      --archive                     Handle archive indices
      --es.ilm-policy-name string   The name of the ILM policy to use if ILM is active (default "jaeger-ilm-policy")
      --es.password string          The password required by storage
      --es.tls.ca string            Path to a TLS CA (Certification Authority) file used to verify the remote server(s) (by default will use the system truststore)
      --es.tls.cert string          Path to a TLS Certificate file, used to identify this process to the remote server(s)
      --es.tls.enabled              Enable TLS when talking to the remote server(s)
      --es.tls.key string           Path to a TLS Private Key file, used to identify this process to the remote server(s)
      --es.tls.server-name string   Override the TLS server name we expect in the certificate of the remote server(s)
      --es.tls.skip-host-verify     (insecure) Skip server's certificate chain and host name verification
      --es.use-ilm                  Use ILM to manage jaeger indices
      --es.username string          The username required by storage
      --index-prefix string         Index prefix
      --timeout int                 Number of seconds to wait for master node response (default 120)
```
