### ISSUE TITLE
jaeger-collector does not support username and password to elasticsearch

### ISSUE THREAD

**Issue by bradyma1** [jaegertracing/jaeger#3382]
**Describe the bug**
similar to problem #1327
I am currently authenticating from jeager successfully with certs and tls.to elasticsearch.  I have a  need to set usernames and paswords with roles to in elasticsearch.  This new (username and password and roles ) is currently working with kibana, logstash, and filebeat.  I do not seem to able to get with to work with my docker compose configuration with jeager collector.  jaeger-agent appears to come up but both jeager-collector and jaeger-query are unable to connect. The  following is the error messge - Failed to init storage factory......failed to create primary Elasticsearch client: health check timeout: Head https://127.0.0.1:9200 x509 cannot validate certificate for 172.0.0.1 beause it doesn't contain any IP SANs: No elasticsearch node available
  Here is  the exact configuration  - 
version '3.2'

services:
   jaeger-agent:
   image:  jaegertracing/jaeger-agent:1.22.0
   container_name: jaeger-agent
   hostname: jaaeger-agent
   privileged: true
   environment:
      -  LOG_LEVEL=debug
      - REPORTER_GRPC_HOST_PORT=jaeger-collector:14250
      - REPORTER_GRPC_RETRY_MAX=1000
      - REPORTER_GRPC_TLS_SKIP_HOST_VERIFY=true
      - ES_SERVER_URLS=https://127.0.0.1:9200
      - ES_TLS_CA=/usr/local/share/certs/ca-bundle.pem
      - ES_USERNAME=elastic
      - ES_PASSWORD='test123456'
      - ES_TLS_SKIP_HOST_VERIFY=true
  ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778:
      - "5775:5775/udp"
      - "14271:14271"
  volumes:
     - /usr/local/share/certs:/user/local/share/certs
  depends_on:
     - jaeger-collector

jaeger-collector:
  network_node: host
  image: jaegertracing/jaeger-collector:1.22.0
  container_name: jaeger-collector
  privileged:true
  environment:
     - LOG_LEVEL=debug
     - ES_TAGS_AS_FIELDS_ALL=true
     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
     - SPAN_STORAGE_URLS=https://127.0.0.1:9200
     - ES_TLS_CA=/usr/local/share/ca-bundle.pem
     - ES_USERNAME=elastic
     - ES_PASSWORD='test123456'
    - ES_TLS_SKIP_HOST_VERIFY=true
  ports:
      - "9411:9411"
      - "14250:14250"
      - "14267:14267"
      - "14269:14269"
  volumes:
     -  /usr/local/share/certs:/usr/local/share/certs

jaeger-query:
   network_mode: host
   image: jaegertracing/jaeger-query:1.22.0
   hostname: jaeger-query
   privileged: true
   environment:
      - LOG_LEVEL=debug
      - ES_TAGS_AS_FIELDS_ALL=true
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=https://127.0.0.1:9200
      - ES_TLS_CA=/usr/local/share/certs/ca-bundle.pem
      - ES_USERNAME=elastic
      - ES_PASSWORD='test123456'
      - ES_TLS_SKIP_HOST_VEROFY=true
  ports:
      - "16686:16686"
      - "16687:16687"
  volumes:
      - /usr/local/share/certs:/user/local/share/certs

**To Reproduce**
1. TMPDIR=/usr/local/share/applications/jaeger/tmp /bin/docker-compose -f /usr/local/share/appplications/jaeger/docker-compose.yml up -d
2.
3.

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - OS: [e.g. Linux] centos linux 7.7
 - Jaeger version: [e.g. 1.8] 1.22.0
 - Deployment: [e.g. bare metal, Docker, Kubernetes, ...] docker

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work. docker instance jaeger-collector and jaeger-query do not come  up....jaeger-agent really does not as collector does not  come  up correctly. 

**Additional context**
It is important to note that the ssl worked correctly, I just can't get this to work using username and password with jaeger-collector

**Comment by albertteoh** [comment]
@bradyma1 please format the docker-compose yaml in a code block (with correct indentation) to make it easier to read and for folks to reproduce.

**Comment by bradyma1** [comment]
will do......but this is almost a direct copy from the docker-compose.yml   If you open in edit mode, you will see the dashes as opposed to the  . for each parameter; but tomorrow first thing I will double check and edit/indent each parameter accordingly.  Thanks for your response.

**Comment by bradyma1** [comment]
configuration updated per your request.  Thanks  for your help

**Comment by albertteoh** [comment]
@bradyma1 the yaml provided in the description had some indentation, syntax and general config issues. I made some fixes and this seemed to work for me (I haven't cleaned everything up, prioritised getting it to work):

```
 version: '3.2'

 services:
   jaeger-agent:
     image:  jaegertracing/jaeger-agent:1.22.0
     container_name: jaeger-agent
     hostname: jaaeger-agent
     privileged: true
     environment:
       - LOG_LEVEL=debug
       - REPORTER_GRPC_HOST_PORT=jaeger-collector:14250
       - REPORTER_GRPC_RETRY_MAX=1000
       - REPORTER_GRPC_TLS_SKIP_HOST_VERIFY=true
     ports:
       - "6831:6831/udp"
       - "6832:6832/udp"
       - "5778:5778"
       - "5775:5775/udp"
       - "14271:14271"
     depends_on:
       - jaeger-collector

   jaeger-collector:
     image: jaegertracing/jaeger-collector:1.22.0
     container_name: jaeger-collector
     privileged: true
     environment:
       - LOG_LEVEL=debug
       - ES_TAGS_AS_FIELDS_ALL=true
       - SPAN_STORAGE_TYPE=elasticsearch
       - ES_SERVER_URLS=http://host.docker.internal:9200
       - ES_USERNAME=elastic
       - ES_PASSWORD=password
       - ES_TLS_SKIP_HOST_VERIFY=true
     ports:
       - "9411:9411"
       - "14250:14250"
       - "14267:14267"
       - "14269:14269"

   jaeger-query:
     image: jaegertracing/jaeger-query:1.22.0
     hostname: jaeger-query
     privileged: true
     environment:
       - JAEGER_AGENT_HOST=jaeger-agent
       - JAEGER_AGENT_PORT=6831
       - LOG_LEVEL=debug
       - ES_TAGS_AS_FIELDS_ALL=true
       - SPAN_STORAGE_TYPE=elasticsearch
       - ES_SERVER_URLS=http://host.docker.internal:9200
       - ES_USERNAME=elastic
       - ES_PASSWORD=password
       - ES_TLS_SKIP_HOST_VERIFY=true
     ports:
       - "16686:16686"
       - "16687:16687"
```
