### ISSUE TITLE
All-in-one container crashes and never recover

### ISSUE THREAD

**Issue by monegim** [jaegertracing/jaeger#3402]
**Describe the bug**
After deploying jaegertracing/all-in-on:1.28 image on the Kubernetes and filling the container memory, it is expected the OOM killed container be recovered when it is restarted, but the container could start with the following logs:
```
2021/11/20 06:10:36 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
{"level":"info","ts":1637388636.2258608,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1637388636.2261279,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1637388636.2269125,"caller":"flags/admin.go:104","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1637388636.2270658,"caller":"flags/admin.go:115","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1637388636.2271206,"caller":"flags/admin.go:96","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
badger 2021/11/20 06:10:39 INFO: 112 tables out of 150 opened in 3.012s
badger 2021/11/20 06:10:40 INFO: All 150 tables opened in 3.937s
badger 2021/11/20 06:10:40 INFO: Discard stats nextEmptySlot: 0
badger 2021/11/20 06:10:40 INFO: Set nextTxnTs to 3116910
badger 2021/11/20 06:10:40 INFO: Deleting empty file: /badger/data/000082.vlog
```

**To Reproduce**
1.  Deploy  jaegertracing/all-in-one:1.28
2. Put it under some loads

**Expected behavior**
It should continue working after the memory is filled and container OOM killed.

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.28
 - Deployment: Kubernetes

**Comment by yurishkuro** [comment]
You're not using memory-only version, you're running with Badger which writes to files. Something may be getting corrupted when it OOMs. You need to configure data purging for Badger to be stable.

**Comment by jpkrohling** [comment]
Are you sure it doesn't eventually come up again? I've seen something similar before where badger would take a really long time to recover after a crash.

**Comment by Avers90** [comment]
I have this issue, too. For recover jaeger, I deleted deployment and apply the yaml file again:
`kubectl apply -f istio_jaeger.yaml`

Yaml like this https://raw.githubusercontent.com/istio/istio/release-1.12/samples/addons/jaeger.yaml
But I have changed image to:
`image: "docker.io/jaegertracing/all-in-one:1.28"`
add increased requests for image:
```
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 12Gi
```
But I still have the same problem as described in this topic.

**Comment by Avers90** [comment]
@yurishkuro You said: You need to configure data purging for Badger to be stable.
Can you help me and tell how can I do that for my config?

**Comment by yurishkuro** [comment]
I am not an expert on Badger, but there is a TTL flag we expose: https://www.jaegertracing.io/docs/1.28/cli/#jaeger-all-in-one-badger

**Comment by Avers90** [comment]
@yurishkuro thx. I will try decrease --badger.span-store-ttl from "72h0m0s" to "48h0m0s" adding to yaml BADGER_SPAN_STORE_TTL:
```
    spec:
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.28"
          env:
            - name: BADGER_EPHEMERAL
              value: "false"
            - name: SPAN_STORAGE_TYPE
              value: "badger"
            - name: BADGER_DIRECTORY_VALUE
              value: "/badger/data"
            - name: BADGER_DIRECTORY_KEY
              value: "/badger/key"
            - name: BADGER_SPAN_STORE_TTL
              value: "48h0m0s"
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: MEMORY_MAX_TRACES
              value: "100000"
            - name: QUERY_BASE_PATH
              value: /jaeger
```
