### ISSUE TITLE
esIndexCleaner not working - index-prefix missing in helm chart?

### ISSUE THREAD

**Issue by ebini** [jaegertracing/jaeger#3477]
**Describe the bug**
see https://github.com/jaegertracing/jaeger/issues/3228
the helm chart sets probably something wrong with the prefix or no prefix at all.

I think this has not really been fixed. 

**To Reproduce**
1.  deploy jaeger helm chart with elastic search as storage

(note, i use an "external" ES):
```
storage:
  type: elasticsearch
  elasticsearch:
    port: "8080"
    scheme: "http"
    host: "my-kibana"
    cmdlineParams:
      es.server-urls: "http://my-kibana:8080"
      es.tls.enabled: false
      es.version: "7"
```

2. enable index cleaner:
```
esIndexCleaner:
  enabled: true
  schedule: "4 4 * * *"
  numberOfDays: 1
```

**Expected behavior**
should delete old indexes.
it lists the indexes, but don't delete anything.

get in logs:
`{"level":"info","ts":1641844868.3567104,"caller":"./main.go:99","msg":"No indices to delete"}`

**Version (please complete the following information):**
current helm chart: version: 0.52.0

**Additional context**
workaround: if i set manually the prefix with:

```
esIndexCleaner:
  extraEnv: 
    - name: INDEX_PREFIX
      value: jaeger-my-index
```

Hope this "quick" bug report is sufficient. 
Thanks in advance.
