### ISSUE TITLE
jaeger-agent doesn't write logs to collector for no apparent reason

### ISSUE THREAD

**Issue by albgus** [jaegertracing/jaeger#3528]
I'm trying to setup a tracing system, using sidecars with jaeger-agent to send data to a Grafana Tempo instance.

From the logs below, it appears that the jaeger agent is able to successfully connect to the collector over gRPC, and is also able to receive spans. However, there is no data actually reaching the collector, and there is no errors being logged, either here or on the Tempo side, and there is no `"Span written to the storage by the collector"` being logged as is stated on: https://www.jaegertracing.io/docs/1.29/troubleshooting/#increase-the-logging-in-the-backend-components

```
2022/02/14 17:06:09 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS
{"level":"info","ts":1644858369.8950822,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1644858369.8951235,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1644858369.8952322,"caller":"flags/admin.go:104","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1644858369.8952727,"caller":"flags/admin.go:115","msg":"Starting admin HTTP server","http-addr":":14271"}
{"level":"info","ts":1644858369.8952825,"caller":"flags/admin.go:96","msg":"Admin server started","http.host-port":"[::]:14271","health-status":"unavailable"}
{"level":"info","ts":1644858369.8959668,"caller":"grpc/builder.go:71","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1644858369.8960056,"caller":"channelz/logging.go:50","msg":"[core]original dial target is: \"dev-monitor-tempo.monitor.svc.cluster.local:14250\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.8960443,"caller":"channelz/logging.go:50","msg":"[core]parsed dial target is: {Scheme:dev-monitor-tempo.monitor.svc.cluster.local Authority: Endpoint:14250 URL:{Scheme:dev-monitor-tempo.monitor.svc.cluster.local Opaque:14250 User: Host: Path: RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.896053,"caller":"channelz/logging.go:50","msg":"[core]fallback to scheme \"passthrough\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.8960655,"caller":"channelz/logging.go:50","msg":"[core]parsed dial target is: {Scheme:passthrough Authority: Endpoint:dev-monitor-tempo.monitor.svc.cluster.local:14250 URL:{Scheme:passthrough Opaque: User: Host: Path:/dev-monitor-tempo.monitor.svc.cluster.local:14250 RawPath: ForceQuery:false RawQuery: Fragment: RawFragment:}}","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.896074,"caller":"channelz/logging.go:50","msg":"[core]Channel authority set to \"dev-monitor-tempo.monitor.svc.cluster.local:14250\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.8960888,"caller":"channelz/logging.go:50","msg":"[core]ccResolverWrapper: sending update to cc: {[{dev-monitor-tempo.monitor.svc.cluster.local:14250  <nil> <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.896097,"caller":"channelz/logging.go:50","msg":"[core]ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.8961036,"caller":"channelz/logging.go:50","msg":"[core]Channel switches to new LB policy \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.8961244,"caller":"grpclog/component.go:55","msg":"[balancer]base.baseBalancer: got new ClientConn state: {{[{dev-monitor-tempo.monitor.svc.cluster.local:14250  <nil> <nil> 0 <nil>}] <nil> <nil>} <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.9462626,"caller":"./main.go:85","msg":"Starting agent"}
{"level":"info","ts":1644858369.9463217,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1644858369.9465525,"caller":"channelz/logging.go:50","msg":"[core]Subchannel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.9465759,"caller":"channelz/logging.go:50","msg":"[core]Subchannel picks a new address \"dev-monitor-tempo.monitor.svc.cluster.local:14250\" to connect","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.9470215,"caller":"grpc/builder.go:110","msg":"Checking connection to collector"}
{"level":"info","ts":1644858369.9470634,"caller":"grpc/builder.go:121","msg":"Agent collector connection state change","dialTarget":"dev-monitor-tempo.monitor.svc.cluster.local:14250","status":"IDLE"}
{"level":"info","ts":1644858369.9471204,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1644858369.9471831,"caller":"grpclog/component.go:71","msg":"[balancer]base.baseBalancer: handle SubConn state change: 0xc00025ec50, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.947205,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.9472177,"caller":"grpc/builder.go:121","msg":"Agent collector connection state change","dialTarget":"dev-monitor-tempo.monitor.svc.cluster.local:14250","status":"CONNECTING"}
{"level":"info","ts":1644858369.9565043,"caller":"channelz/logging.go:50","msg":"[core]Subchannel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.956581,"caller":"grpclog/component.go:71","msg":"[balancer]base.baseBalancer: handle SubConn state change: 0xc00025ec50, READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.9566445,"caller":"grpclog/component.go:71","msg":"[roundrobin]roundrobinPicker: Build called with info: {map[0xc00025ec50:{{dev-monitor-tempo.monitor.svc.cluster.local:14250  <nil> <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.9566615,"caller":"channelz/logging.go:50","msg":"[core]Channel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1644858369.956675,"caller":"grpc/builder.go:121","msg":"Agent collector connection state change","dialTarget":"dev-monitor-tempo.monitor.svc.cluster.local:14250","status":"READY"}
{"level":"debug","ts":1644858540.8622842,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":2629}
{"level":"debug","ts":1644858550.8626077,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":5141}
{"level":"debug","ts":1644858550.8657024,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":1813}
```

Is it possible to send a raw request to the collector to see if it's working?

values for ingress-nginx helm chart:
```
        controller:
          kind: Deployment
          replicaCount: 1
          admissionWebhooks:
            enabled: false
          config:
            http2-max-concurrent-streams: "16"
            use-gzip: "true"
            enable-opentracing: "true"
            jaeger-collector-host: 127.0.0.1
            jaeger-collector-port: 6831
          ingressClassResource:
            name: public-nginx
            enabled: true
          extraContainers:
          - name: jaeger-agent
            image: jaegertracing/jaeger-agent:latest
            ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            command:
              - "/go/bin/agent-linux"
              - "--reporter.grpc.host-port=dev-monitor-tempo.monitor.svc.cluster.local:14250"
              - "--log-level=debug"
            resources:
              limits:
                memory: 50M
                cpu: 100m
              requests:
                memory: 50M
                cpu: 100m
```

**Version (please complete the following information):**
 - OS: Linux, containers
 - Jaeger version: 1.31
 - Deployment: Kubernetes
