### ISSUE TITLE
Support OpenSearch 2.x

### ISSUE THREAD

**Issue by kjq** [jaegertracing/jaeger#3808]
### What happened?

When upgrading OpenSearch to the latest version (in minikube or EKS) I get this error creating the index:

` Error 400 (Bad Request): Setting index.mapper.dynamic was removed after version 6.0.0 [type=illegal_argument_exception]","stacktrace":"main.main.func1\n\t./main.go:85\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t./main.go:151\nruntime.main\n\truntime/proc.go:250"}`

Using an older version of OpenSearch v1.5.x does not have this issue.  For both, I am using the Helm charts to deploy (not the operators).

Is there any special configuration that needs to happen for this or can I even use OpenSearch safely?

### Steps to reproduce

1. Install using OpenSearch 2.x - Jaeger collector fails
2. Install using OpenSearch 1.5.x - Jaeger collector also installs

### Expected behavior

OpenSearch 2.x is similar to 1.5.x when using Jaeger Collector

### Relevant log output

Logs from Jaeger Collector while being applied to K8S cluster:

`Error 400 (Bad Request): Setting index.mapper.dynamic was removed after version 6.0.0 [type=illegal_argument_exception]","stacktrace":"main.main.func1\n\t./main.go:85\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t./main.go:151\nruntime.main\n\truntime/proc.go:250"}`

### Jaeger backend version

Jaeger 1.36.0 (latest helm chart)

### Storage backend

OpenSearch 2.x (latest helm chart)

### Configuration
Pretty out-of-the-box ES setup:

```
storage:
  type: elasticsearch
  elasticsearch:
    host: {{ .Values.opensearch.host }}
    port: {{ .Values.opensearch.port }}
    scheme: {{ .Values.opensearch.scheme | default "http" }}
    usePassword: false
    user: {{ .Values.opensearch.user }}
    password: {{ .Values.opensearch.pass }}
```
