### ISSUE TITLE
[Feature]: Publish description and readme to Docker Hub

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#3842]
### Requirement

As a user downloading Jaeger images from Docker Hub, I want to be able to read a description and basic usage in the Docker Hub repositories.

### Problem

Right now most of Jaeger's Docker Hub repositories contain neither description nor the readme.

### Proposal

Use Docker Hub API to push the README files from the respective cmd/*** dirs when publishing Docker images.

Example: https://github.com/peter-evans/dockerhub-description/blob/main/src/dockerhub-helper.ts

**Comment by YashasviChaurasia** [comment]
@yurishkuro i would like to work on this issue.

**Comment by yurishkuro** [comment]
Great, go for it. Don't worry about the descriptions themselves, we first want to set up the process, and then we can improve the readmes.

**Comment by YashasviChaurasia** [comment]
@yurishkuro 
### I have Tested the Workflow and have tested it on my personal repository to upload Readme files on two different docker-hub repos namely "yashasvichaurasia/testing" and "yashasvichaurasia/testlife"

Following are some screenshots:

<img width="1440" alt="Screenshot 2022-08-07 at 1 34 01 AM" src="https://user-images.githubusercontent.com/46622381/183264598-8bc091b0-4e17-4df1-baad-b1c37ba0db44.png">
<img width="1440" alt="Screenshot 2022-08-07 at 1 35 31 AM" src="https://user-images.githubusercontent.com/46622381/183264603-3af84a01-a86b-491c-8bcf-7fc62a285cab.png">
<img width="1440" alt="Screenshot 2022-08-07 at 1 36 39 AM" src="https://user-images.githubusercontent.com/46622381/183264608-4e92a69f-0a4b-41d7-967b-5416cf3a6c2d.png">
<img width="1440" alt="Screenshot 2022-08-07 at 1 42 58 AM" src="https://user-images.githubusercontent.com/46622381/183264723-2d11e9a7-68d6-4f85-92e4-14c19fe81633.png">

**Comment by YashasviChaurasia** [comment]
I have written the jobs in '.yml' in the following template where I have assumed the admin username and password to be in the following repository secrets as we would require admin privileges while accessing docker hub while using this workflow:

```
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: peterevans/dockerhub-description
        readme-filepath: ./path/to/README.md
```
In one .yml file, I have created multiple jobs which will upload Readme's to different docker-hub repositories when a push is triggered on the Github repo.

Kindly evaluate my way of thinking and let me know if I should create a PR if it is correct.
Thank you
