### ISSUE TITLE
How to support plugins

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#422]
We continue to be asked if we can "support X as storage backend" (e.g. #331, #421). Provided that the authors are willing to contribute, maintain, and support such backend implementations, we still have an open question of whether we want to accept those contributions into the main `jaeger` repository. I could be wrong, by my initial reaction is that we should keep them in separate "contrib" style repositories, for the following reasons:
  1. having half a dozen implementations is going to bloat the size of the binary, increase compile / testing time
  1. having them in core repo suggests that they are officially supported, same as Cassandra/ES, but we don't have expertise in all those different storage solutions, and cannot be on the hook to support them

If we do keep them in the contrib repos, however, we need an approach to allow end users to use those implementations without having to rebuild the backend from source.

One such approach is using Go plugins (https://golang.org/pkg/plugin/), for example as done in [Kanali](https://github.com/northwesternmutual/kanali/blob/master/PLUGIN_GUIDE.md). I think it is feasible to package plugins as individual containers and mount them into a shared volume where the main Jaeger binaries can locate and load them.

cc @pavolloffay @black-adder - any thoughts?

*Update 12/28/2017*

An alternative approach mentioned in the comments below is the *sidecar plugin model* (e.g. https://github.com/hashicorp/go-plugin) where the plugin runs as a separate process and the main binary communicates with it via RPC, e.g. gRPC streams. It's worth noting, however, that this approach is still a special case of in-process plugin model, so we need to start there and answer [the questions below](https://github.com/jaegertracing/jaeger/issues/422#issuecomment-353428289). For each type of plugin we can support a built-in "sidecar" variant.

*Update 8/2/2018*

Per https://github.com/jaegertracing/jaeger/issues/422#issuecomment-410129850, I think the following is a reasonable, actionable, and realistic plan. If someone **wants to volunteer**, ping me.

* [ ] define protobuf version of SpanWriter and SpanReader interfaces
* [ ] implement gRPC client and server, where server delegates to the respective storage.SpanReader/Writer interfaces, and client implements them.
* [ ] extend storage factory with two new types, e.g. `h-plugin` (h for harshicorp) and `g-plugin` (plain gRPC). The `h-plugin` should support a cli flag for the name of the plugin executable. The `g-plugin` should support a cli flag for grpc server host:port.
* [ ] implement in-memory storage as `g-plugin` using gRPC client/server defined above
* [ ] implement one of the other storage types (Cassandra or ES) as `h-plugin` as a template.
* [ ] TBD: how to pass configuration to the h-plugins. Because plugins are plain executables, they can use viper just like the main binaries, and the cli flag with the plugin command line might be a long string (or the user can pass params via env vars). We probably should provide a template for main, so that the actual main for a plugin is very short.
* [ ] update documentation with example of building an `h-plugin`.
* [ ] replace Cassandra with in-memory shared service in crossdock integration test.

*Update 9/4/2018*

Someone pointed out that Go's pkg/plugin now supports MacOS and Linux. This removes a significant development hurdle with using the native plugins, and makes it a viable option which is probably simpler to implement than the gRPC-based harshicorp model.

**Comment by jpkrohling** [comment]
I think Kubernetes is also planning on supporting plugins for external storage. I'm not familiar with how it works, but it would perhaps be worth checking if it would make sense for us to follow the same path.

**Comment by yurishkuro** [comment]
I think K8s plugins will be runnable containers, i.e. integration is out of process. A lot of our use cases require in-process integration for performance reasons, e.g. span sanitizers, filters.

**Comment by omeid** [comment]
I believe out of process _integration_ (effectively middleware/brokers) would be practical for storage, of course, for thins like sanitizers, filters, et al. that is a different story.

**Comment by omeid** [comment]
I believe out of process _integration_ (effectively middleware/brokers) would be practical for storage, of course, for thins like sanitizers, filters, et al. that is a different story.

**Comment by frankgreco** [comment]
What I found developing Kanali is that plugins are amazing for allowing users to add their own custom functionality. For example, if people design plugins for Kanali, the only requirement is that they implement a certain interface. One side affect is that the `.so` files aren't small and so while the main program's binary remains small, the Docker image is larger.

I think I agree with @omeid that storage should be out of process. For things like these, I'd propose using gRPC to communicate with out of process integration. For in-process items, such as encrypting tag values, +1 for golang plugins.

**Comment by yurishkuro** [comment]
I've been thinking this past week about how to support plugins in Jaeger. Some considerations:

  * the plugins themselves must be configurable, e.g. Cassandra storage has a bunch of parameters
    * configuring via env variables is the easiest
    * configuring via cmd line arguments (as we do now) is desired (see #608)
  * there must be different types of plugins, e.g. storage vs. span adjusters
  * there should be an easy story of deploying plugins without rebuilding docker images
    * the easiest way seems to be to point the main binary to a directory that stores plugins in sub-directories. The main binary will iterate and load all of them. Each plugin could be self-describing, e.g. by implementing one of the supported plugin interfaces like StoragePlugin, AdjusterPlugin, etc.
    * I don't have a good strategy yet how plugins can be loaded from other docker images, open to suggestions.

**Comment by frankgreco** [comment]
Addressing your last point, when `kanali@2.0.0` is released, I think i'm going to do the following to load plugin. With this approach, the `kanali` pod does not have to be changed when new plugins are required or changed.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kanali
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: kanali
    spec:
      serviceAccountName: kanali
      containers:
      - name: kanali
        image: northwesternmutual/kanali
        command: ["/kanali", "start"]
        volumeMounts:
        - name: plugins
          mountPath: /plugins
          readOnly: true
      initContainers:
      - name: kanali-plugin-apikey
        image: fbgrecojr/kanali-plugin-apikey:local
        imagePullPolicy: IfNotPresent
        command: ["cp", "/apiKey_v2.0.0-rc.1.so", "/plugins/"]
        volumeMounts:
        - name: plugins
          mountPath: /plugins
      volumes:
      - name: plugins
        emptyDir: {}
```

Addressing your first point, making these plugins configurable is tricky. ENV variables will work but I haven't found a solution for dynamically changing the cli interface. The problems lies in the fact that a golang plugin's init function is called when they are opened. This of course would happened after the init functions for the code doing the opening is executed.
