### ISSUE TITLE
[Feature]: spm additional query parameter required for prometheus

### ISSUE THREAD

**Issue by rbaumgar** [jaegertracing/jaeger#4221]
### Requirement

I am using a global prometheus for spm where I need to add a specific query parameter to get data.
Currently no parameter is available to define an additional query parameter.
I only found --query.base-path which does not fit.

### Problem

spm sends only e.g. "/api/v1/query?query=up", but I need to send "/api/v1/query?query=up&mykey=myvalue"
otherwise I don't get any data.

### Proposal

please provide another parameter, eg. --query.additional-parameter.

**Comment by hkailantzis** [comment]
That would be great, as in my case we're using Thanos, and query parameter is a hard requirement for us (like the namespace), and can't alter it this requirement. For the Bearer token I use the ```---prometheus.token-file cli flag```, which is basically a secret token generated by an appopriate SA (for all-in-one), and I'm mounting is using this:

```
extraSecretMounts:
    - name: prometheus-token
      mountPath: /tls
      secretName: jaeger-all-in-one-token
      readOnly: true
```
this plus RoleBinding of ClusterRole type:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jaeger
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: <ClusterRoleName>
subjects:
- kind: ServiceAccount
  name: jaeger-all-in-one
  namespace: default
  ```
but I'm getting an error which I can't make anything out of it, so I'm assuming is because of the missing required namespace parameter..., but not 100% sure...

```
msg":"HTTP handler, Internal Server Error","error":"failed executing metrics query: bad_response: readObjectStart: expect { or n, but found B, error found in #1 byte of ...|Bad Request|..., bigger context ...|Bad Request. The request or configuration is malfor|..."
```

cc @rbaumgar
