### ISSUE TITLE
[Bug]: NoData for Latency and ErrorRate in Monitoring tab with Jaeger 1.46 and Opentelemetry SpanMetrics Connector

### ISSUE THREAD

**Issue by Tyrion85** [jaegertracing/jaeger#4502]
### What happened?

This [issue](https://github.com/jaegertracing/jaeger/pull/4452) added support for SpanMetrics connector (since SpanMetrics Processor is [deprecated](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/README.md))

However, I'm not seeing latency and error rate in Jaeger's `Monitoring` tab - only Request rate is populated, and a "No data yet!" notification is displayed in UI.

Relevant metrics are written to Prometheus by OpenTelemetry Collector, as shown in the screenshots below. Jaeger metrics `jaeger_query_requests_total{operation="get_latencies",result="ok"}` and similar suggest everything is okay. There is also no error visible in Query logs.

Jaeger version 1.46.0, installed via helm chart (not a all-in-one)

### Steps to reproduce

1. Install Jaeger via helm chart, image version 1.46.0
2. Setup OpenTelemetry collector with config [from upstream](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector#using-spanmetrics-with-prometheus-components)
3. Connect Jaeger with Prometheus (in my case, Thanos, but it doesn't matter)
4. Inspect that Latency and Error Rate are missing

### Expected behavior

Expected Latency and Error Rate to work, as related metrics are available in Prometheus

### Screenshot

<img width="1917" alt="Screenshot 2023-06-05 at 15 53 53" src="https://github.com/jaegertracing/jaeger/assets/1699305/c0253791-82fe-495d-b8d9-4fac543250bc">
<img width="1916" alt="Screenshot 2023-06-05 at 15 49 23" src="https://github.com/jaegertracing/jaeger/assets/1699305/18930e0a-a60a-4334-8521-a4894e7d4132">
<img width="1881" alt="Screenshot 2023-06-05 at 15 50 49" src="https://github.com/jaegertracing/jaeger/assets/1699305/fcc22fed-3805-4edd-b5c0-5eb9c96c7eeb">
<img width="1897" alt="Screenshot 2023-06-05 at 15 53 07" src="https://github.com/jaegertracing/jaeger/assets/1699305/7c9e2775-12a5-4dc8-9baa-5e8673d50558">
<img width="1259" alt="Screenshot 2023-06-05 at 15 49 39" src="https://github.com/jaegertracing/jaeger/assets/1699305/6d919f97-8a21-4d64-8cc2-9bfa529945a2">

### Additional context

Relevant OpenTelemetry Collector configuration:

```
receivers:
      otlp:
        protocols:
          grpc:
          http:
          ....
      zipkin:
      opencensus:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_compact:
          thrift_binary:
    connectors:
      spanmetrics:
    processors:
      batch:
      span/to_attributes:
        ...
    extensions:
      health_check:
    exporters:
      jaeger:
        ....
      otlp/quickwit:
        ....
      prometheusremotewrite:
        endpoint: http://prometheus-operated.monitoring:9090/api/v1/write
        target_info:
          enabled: true
    service:
      extensions: [ health_check ]
      pipelines:
        traces:
          receivers: [ otlp,opencensus,zipkin,jaeger ]
          processors: [ batch,span/to_attributes ]
          exporters: [ jaeger,otlp/quickwit,spanmetrics ]
        metrics:
          receivers: [ spanmetrics ]
          exporters: [ prometheusremotewrite ]
```

Relevant Jaeger config (helm chart):
```
....
extraEnv:
    - name: GRPC_STORAGE_SERVER
      value: quickwit-searcher:7281
    - name: METRICS_STORAGE_TYPE
      value: prometheus
    - name: PROMETHEUS_SERVER_URL
      value: http://thanos-query-frontend.monitoring:9090
```

### Jaeger backend version

v1.46.0

### Stogage backend

GRPC_STORAGE_SERVER (Quickwit)

### Deployment model

Kubernetes, helm chart
