### ISSUE TITLE
[cu-release] Release artifacts can be uploaded to the wrong release / tag

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#4814]
When ci-release workflow is triggered manually, the BRANCH is is being set to `main` and the upload release action creates a release & tag called `main`:
```
Run svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df
  with:
    file: {deploy/*.tar.gz,deploy/*.zip,deploy/*.sha[2](https://github.com/jaegertracing/jaeger/actions/runs/6438219891/job/17484442468#step:14:2)56sum.txt,deploy/*.asc}
    file_glob: true
    overwrite: true
    tag: refs/heads/main
    repo_token: ***
  env:
    BRANCH: main
```

We probably need to fix `action/setup-branch` to run `make echo-version` if the branch is determined to be `main`, since the GH variables do not reflect the release tag in that case.
