### ISSUE TITLE
[jaeger-v2] Deployment options

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5221]
This project was proposed but not selected as one of [CNCF Google Summer of Code projects](https://github.com/cncf/mentoring/blob/main/programs/summerofcode/2024.md#jaeger).

## Background
We are working towards [Jaeger v2](https://github.com/jaegertracing/jaeger/issues/4843) that is re-architected to be a custom distribution of the [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector). There are multiple tracks towards that milestone, one of them is to address the deployment process for the end users.

There are existing solutions for deploying jaeger-v1 and OTEL Collector:
  * https://github.com/jaegertracing/jaeger-operator
  * https://github.com/jaegertracing/helm-charts

The main issue is that they manage jaeger-v1 deployment, which:
  * consists of multiple different binaries, and
  * uses CLI flags / env vars for configuration. 

In Jaeger-v2 we are dealing with a single binary that is configurable to fit different deployment modes using config files. So the existing operators/charts won't work for v2, we need to modify them.

There is also an OTEL Operator that manages OTEL Collector, which is conceptually much closer to jaeger-v2. However, Jaeger operator/chart also manage storage backends, so OTEL Operator is not sufficient out of the box.
  * https://github.com/open-telemetry/opentelemetry-operator

## Objectives
* Analyze existing solutions, such as Kubernetes Operators for Jaeger-v1 and OpenTelemetry Collector; and Helm charts
* Propose a strategy for how to support deployment options for Jaeger-v2, get alignment with maintainers;
* Implement and document the new deployment options.

## Expected Outcome:
* Support deploying Jaeger v2 via Kubernetes Operator, Helm chart, and brew.
* Documentation on the website.

## Recommended Skills
Go, Kubernetes, scripting, CI/CD, understanding of Kubernetes Operator concepts.

## Mentors:
* Yuri Shkuro (@yurishkuro, [github@ysh.us](mailto:github@ysh.us)) - primary
* Jonah Kowall (@jkowall, [jkowall@kowall.net](mailto:jkowall@kowall.net))

Use CNCF Slack to reach maintainers (see https://www.jaegertracing.io/get-in-touch/)

## References
  * Jaeger v2 binary entry point https://github.com/jaegertracing/jaeger/blob/ef4791ec7b0761f7a6f9ac3cace54a2039483d8e/cmd/jaeger/main.go#L17
  * [Jaeger v2 parent issue](https://github.com/jaegertracing/jaeger/issues/4843), including design doc
  * https://www.jaegertracing.io/mentorship-for-mentees/

**Comment by varshith257** [comment]
@yurishkuro I would like to discuss about it

**Comment by Swastik-Swarup-Dash** [comment]
Hey@yurishkuro i would like to work on the issue need some resources to get a brief idea about the project and come with a solution reagarding the issue

**Comment by haanhvu** [comment]
> @yurishkuro i would like to work on the issue need some resources to get a brief idea about the project and come with a solution reagarding the issue

There are already project brief and resources in the issue description. Please check those.

If you need further details, you may look further into the deployment options of otel collector on kubernetes. For example, this one explains it well (the author is maintainer of both jaeger and otel): https://github.com/jpkrohling/opentelemetry-collector-deployment-patterns/tree/main/pattern-3-kubernetes

**Comment by Swastik-Swarup-Dash** [comment]
Thanks for the valuable information @haanhvu it surely helped me a lot about the Isuue

**Comment by pavolloffay** [comment]
I got working V2 with memory store with the OTEL operator:
```
kubectl apply -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: jaeger
spec:
  image: jaegertracing/jaeger:latest
  ports:
  - name: jaeger
    port: 16686
  config: |
    extensions:
      jaeger_query:
        trace_storage: memstore

      jaeger_storage:
        memory:
          memstore:
            max_traces: 100000

    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      jaeger_storage_exporter:
        trace_storage: memstore

    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]    
          exporters: [jaeger_storage_exporter]
EOF
```

The elasticsearch will be more complicated as it requires index cleaner and rollover which run as cronjobs in jaeger v1. However, this functionality could be implemented in the V2 as a separate extension or be part of the storage exporter e.g.

```yaml
extensions:
  jaeger_storage:
    elasticsearch:
      index_cleaner:
        num_days: ....

   jaeger_elasticearch_index_cleeaner:
     num_days: ...
```

Alternatively we could let users configure https://opensearch.org/docs/latest/im-plugin/ism/index/ directly for rollover and index cleaning functionality and later maybe build it into the storage. 

Cassandra will require schema creation job at startup which could be as well implemented in Jaeger as an extension.
