### ISSUE TITLE
[Bug]: Error Creating Dir: \"/badger/key\" error: mkdir /badger/key: permission denied

### ISSUE THREAD

**Issue by genfemme** [jaegertracing/jaeger#5430]
### What happened?

The pod "jaegar-jaeger-all-in-one-0" is not getting created. The error details - 
"Error Creating Dir: \"/badger/key\" error: mkdir /badger/key: permission denied"

### Steps to reproduce

I have used helm to install it with this chart - 
 https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts
version = 0.1.12

To resolve the permission issues, I added the code provided in this issue chat - https://github.com/jaegertracing/jaeger/issues/4906 in the values.yaml file as per below - 

```
`query:
        initContainers:
          name: init-jaeger
          image: jaegertracing/all-in-one:latest
          command: ["/bin/sh", "-c"]
          args: ["mkdir -p /badger/data && touch /badger/data/.initialized && chown -R 10001:10001 /badger/data"]
          volumeMounts:
            - name: jaeger-badger-data
              mountPath: /badger
          securityContext:
            fsGroup: 10001
      volumes:
        - name: jaeger-badger-data
          emptyDir: {}`
```

### Expected behavior

No error in the pod and sts of "jaegar-jaeger-all-in-one"

### Relevant log output

```shell
{"level":"fatal","ts":1715104044.9270027,"caller":"all-in-one/main.go:114","msg":"Failed to init storage factory","error":"Error Creating Dir: \"/badger/key\" error: mkdir /badger/key: permission denied","stacktrace":"main.main.func1\n\tgithub.com/jaegertracing/jaeger/cmd/all-in-one/main.go:114\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tgithub.com/jaegertracing/jaeger/cmd/all-in-one/main.go:249\nruntime.main\n\truntime/proc.go:271"}
```

### Deployment model

On EKS cluster using helm
