### ISSUE TITLE
[jaeger v2] Observability and Healthchecks

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#5633]
Part of https://github.com/jaegertracing/jaeger/issues/5240

(1) Currently jaeger-v2 components are initialized without observability clients. We need to instantiate appropriate logging, tracing, and metrics clients and pass them to the components. The existing code uses internal metrics API, which needs to be bridged to OTEL metrics to minimize code changes. 

(2) Jaeger-v1 components can report their readiness using an internal health check API that is connected to the healthcheck endpoint on the admin port. We need to implement similar capability in Jaeger-v2.

Expected Outcome: Achieve parity in observability of jaeger-v2 compared to jaeger-v1

**Comment by yurishkuro** [comment]
@Wise-Wizard fyi https://github.com/open-telemetry/opentelemetry-collector/pull/10443/files. I don't know if it's immediately useful for us.

**Comment by Wise-Wizard** [comment]
> @Wise-Wizard fyi https://github.com/open-telemetry/opentelemetry-collector/pull/10443/files. I don't know if it's immediately useful for us.

Yes, went through this. Metrics can now be configured using a yaml file. 
Are you suggesting that I should now put my focus on creating the unified telemetry container?

**Comment by mahadzaryab1** [comment]
@yurishkuro what's the status of this ticket? anything I can help with here?

**Comment by yurishkuro** [comment]
I think it's still open, we need to revisit what was and wasn't done for each component.

**Comment by FaisalBudiono** [comment]
From the [Migration Guide](https://www.jaegertracing.io/docs/2.3/migration/), it said the healthcheck endpoint was moved from
```
localhost:14269
```
to:
```
http://localhost:13133/status
```

But when I try to hit that API, it always give me a connection refused error. Anyone experience this?

**Comment by yurishkuro** [comment]
```
$ go run ./cmd/jaeger

$ curl http://localhost:13133/status
{"start_time":"2025-02-19T18:25:45.2243-05:00","healthy":true,"status":"StatusOK","status_time":"2025-02-19T18:25:45.232012-05:00"}%
```
works fine. Check your connectivity / exposed ports.

**Comment by FaisalBudiono** [comment]
It turns out. there are something wrong with my configuration.

docker-compose.yml
```yml
name: "docker-tools"

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:2.3.0
    environment:
      JAEGER_PROPAGATION: w3c
    ports:
      - 16686:16686
      - 13133:13133
    networks:
      - docker-tools-network


networks:
  docker-tools-network:
    name: docker-tools-network
    driver: bridge
```

When I run this, the `http://localhost:13133` is accessible. But when I change the configuration with:

docker-compose.yml
```yml
name: "docker-tools"

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:2.3.0
    environment:
      JAEGER_PROPAGATION: w3c
    command: ["--config", "/etc/jaeger/config.yml"]
    volumes:
      - "./jaeger/config-spm.yml:/etc/jaeger/config.yml"
    ports:
      - 16686:16686
      - 13133:13133
    networks:
      - docker-tools-network

networks:
  docker-tools-network:
    name: docker-tools-network
    driver: bridge
```

./jaeger/config-spm.yml
```yml
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    logs:
      level: DEBUG

extensions:
  healthcheckv2:
    use_v2: true
    component_health:
      include_permanent_errors: false
      include_recoverable_errors: true
      recovery_duration: 5m
    http:
      endpoint: "localhost:13133"
      status:
        enabled: true
        path: "/health/status"
      config:
        enabled: true
        path: "/health/config"
  jaeger_query:
    storage:
      traces: badger_storage
  jaeger_storage:
    backends:
      badger_storage:
        badger:
          directories:
            keys: "/tmp/jaeger/"
            values: "/tmp/jaeger/"
          ephemeral: false

connectors:
  spanmetrics:

receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: badger_storage
```

The `http://localhost:13133` is not accessible anymore. Is there something wrong with my jaeger config?
