### ISSUE TITLE
[Bug]: Query prometheus exporter target to show in /monitor in Jaeger UI

### ISSUE THREAD

**Issue by AfrouzMashayekhi** [jaegertracing/jaeger#6290]
### What happened?

I have multiple jaegers in different environment, and I want to use prometheus for metric storage backend. but when I use one prometheus for all the jaegers in the /monitor tab of jeager UI I have the same metrics for all the jaeger. This caused by the implementation of prometheus config, you can not seperate prometheus targets in the jeager metric_storage_backend to use specified target config.
https://github.com/jaegertracing/jaeger/blob/d1a8ecec687eeb69b0dec62e458b97651127dabe/pkg/prometheus/config/config.go#L14

```
    metric_backends:
      some_metrics_storage:
        prometheus:
          endpoint: http://prometheus:9090
          normalize_calls: true
          normalize_duration: true
```

### Steps to reproduce

1. have two jaeger with different traces 
2. scrape metrics of two jaeger in one prometheus
3. config jaeger to use the same prometheus backend
4. Two same application but in two different environment
5.  in the /monitor tab of both jaeger it will show same graph even one of the jaegers didn't receive any traces from application 

### Expected behavior

the second jaeger don't show metrics from other jaegers when we have the same prometheus backend

### Relevant log output

```shell

```

### Jaeger backend version

v2.0.0

### Stogage backend

Cassandra, Prometheus

### Deployment configs

```shell
metric_backends:
      some_metrics_storage:
        prometheus:
          endpoint: http://prometheus:9090
          normalize_calls: true
          normalize_duration: true
```
