### ISSUE TITLE
Log the ports that jaegerreceiver listens to

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#6412]
The implementation for this issue is actually in the [OTEL/contrib/jaegerreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/jaegerreceiver) module. By convention Jaeger internal extensions try to log which ports / endpoints they are listening when creating the servers, e.g.:

* `Serving metrics	{"address": "localhost:8888", "metrics level": "Detailed"}`
* `Query server started	{"kind": "extension", "name": "jaeger_query", "http_addr": "[::]:16686", "grpc_addr": "[::]:16685"}`
* `Starting GRPC server	{"kind": "extension", "name": "jaeger_query", "port": 16685, "addr": ":16685"}`
* `Starting HTTP server	{"kind": "extension", "name": "jaeger_query", "port": 16686, "addr": ":16686"}`

(side note: the log from Query server should be split into two lines)

However, the `jaegerreceiver` that we're importing from OTEL/contrib is not logging any of the ports / endpoints, even though in all-in-one configuratiob we enable all four:
```yaml
      grpc:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:14250"
      thrift_http:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:14268"
      thrift_binary:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:6832"
      thrift_compact:
        endpoint: "${env:JAEGER_LISTEN_HOST:-localhost}:6831"
```

The goal is to make changes upstream to log a similar "Server started" log for each port that jaegerreceiver is listening to. For the reference of how it's done we can look at [OTLP receiver](https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver) that does log its endpoints:

* `Starting GRPC server	{"kind": "receiver", "name": "otlp", "data_type": "traces", "endpoint": "localhost:4317"}`
* `Starting HTTP server	{"kind": "receiver", "name": "otlp", "data_type": "traces", "endpoint": "localhost:4318"}`
