### ISSUE TITLE
panic: invalid Go type when GetTrace by grpc api_v2

### ISSUE THREAD

**Issue by jiekun** [jaegertracing/jaeger#6716]
### What happened?

This issue is actually dup to https://github.com/jaegertracing/jaeger/issues/3662 as it's not verified and solved.

When Jaeger send request to `GetTrace` gRPC API, the application will panic with the following:
```
panic: invalid Go type model.TraceID for field jaeger.api_v2.Span.trace_id
```

It seems the data Jaeger sent to gRPC server does not match the defined type.

I also tried suggested way:

> remove gogo annotations from proto file

removing all gogo annotations in `storage.proto` but it's not working. The generated `pb.go` file here:

<details>

[storage.pb.change_ext_to_go.txt](https://github.com/user-attachments/files/18764806/storage.pb.change_ext_to_go.txt)

</details>

### Steps to reproduce

The architecture for my demo app be like:
```
Hot R.O.D (docker)-> Jaeger(docker) -> My gRPC Storage (which implemented `storage.proto`)
```

And the docker compose I used:

<details>

```yaml
version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.60.0
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - SPAN_STORAGE_TYPE=grpc
      - GRPC_STORAGE_SERVER=127.0.0.1:17271
    network_mode: "host"
  hotrod:
    image: dockerproxy.net/jaegertracing/example-hotrod:latest
    # To run the latest trunk build, find the tag at Docker Hub and use the line below
    # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
    #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
    ports:
      - "8080:8080"
    command: ["all"]
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
    network_mode: "host"
```

</details>

### Expected behavior

GetTrace API works correctly.

### Relevant log output

```shell

```

### Jaeger backend version

tested with v1.60.0 / v1.66.0

### Stogage backend

self-build gRPC backend implementing `storage.proto`

### Deployment configs

```shell

```
