### ISSUE TITLE
[Bug]: Why does the _ of the original indicator in Prometheus become .

### ISSUE THREAD

**Issue by zqyangchn** [jaegertracing/jaeger#6751]
### What happened?

jaeger 2.2.0
curl -s http://10.110.6.124:8888/metrics | grep rpc_server_responses_per_rpc_count
rpc_server_responses_per_rpc_count{rpc_grpc_status_code="0",rpc_method="Export",rpc_service="opentelemetry.proto.collector.trace.v1.TraceService",rpc_system="grpc",service_instance_id="238ffcc7-86ce-45e8-bb33-6706a28fe680",service_name="jaeger",service_version="v2.2.0"} 753

prometheus 3.2.0 query {__name__=~".*rpc.*"}
rpc_server_responses_per_rpc_count{app_kubernetes_io_instance="jaeger-collector", app_kubernetes_io_name="jaeger-collector", instance="10.110.6.124:8888", job="jaeger", kubernetes_namespace="observability", kubernetes_pod_name="jaeger-collector-567994747-7pbmf", rpc_grpc_status_code="0", rpc_method="Export", rpc_service="opentelemetry.proto.collector.trace.v1.TraceService", rpc_system="grpc", service_instance_id="238ffcc7-86ce-45e8-bb33-6706a28fe680", service_name="jaeger", service_version="v2.2.0"}

Version 2.2.0 is normal

jaeger 2.3.0
curl -s http://10.110.6.238:8888/metrics | grep rpc_server_responses_per_rpc_count
rpc_server_responses_per_rpc_count{otel_scope_name="go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc",otel_scope_version="0.59.0",rpc_grpc_status_code="0",rpc_method="Export",rpc_service="opentelemetry.proto.collector.trace.v1.TraceService",rpc_system="grpc"} 144

prometheus 3.2.0 query {__name__=~".*rpc.*"}
{"rpc.server.responses_per_rpc_count", app_kubernetes_io_instance="jaeger-collector", app_kubernetes_io_name="jaeger-collector", instance="10.110.6.238:8888", job="jaeger", kubernetes_namespace="observability", kubernetes_pod_name="jaeger-collector-6fd47fc7fd-gd6hn", otel_scope_name="go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc", otel_scope_version="0.59.0", "rpc.grpc.status_code"="0", "rpc.method"="Export", "rpc.service"="opentelemetry.proto.collector.trace.v1.TraceService", "rpc.system"="grpc"}

Version 2.3.0, Why does the _ of the original indicator in Prometheus become .

### Steps to reproduce
```yaml
jaeger config 
    service:
      extensions: [jaeger_storage, healthcheckv2]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [jaeger_storage_exporter]
      telemetry:
        resource:
          service.name: jaeger
        metrics:
          level: detailed
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: ${env:JAEGER_LISTEN_HOST:-localhost}
                    port: {{ .Values.jaegerCollector.otlpMetricsPort }}
        logs:
          level: info
```
promtheus config
```yaml
    - job_name: jaeger
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_jaeger_scrape
      - action: labeldrop
        regex: __meta_kubernetes_pod_label_(pod_template_hash)
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_jaeger_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_jaeger_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
```

### Expected behavior

Like version 2.2.0, Prometheus scrapes the metric name rpc_server_responses_per_rpc_count

### Relevant log output

```shell

```

### Jaeger backend version

2.3.0

### Deployment configs

```shell

```
