### ISSUE TITLE
[Bug]: prometheus_alerts.yml for jaeger 2.X

### ISSUE THREAD

**Issue by yogesh119905** [jaegertracing/jaeger#6820]
### What happened?

As I am going to implement prometheus rule for jaeger 2.x.x with reference of old prometheus.rule. here is attached link https://github.com/jaegertracing/jaeger/blob/main/monitoring/jaeger-mixin/prometheus_alerts.yml, but most of the metrics names are changes as per jaeger 2.x.x. Is there any prometheus alerts rules avaliable for jaeger version 2.x.x

### Steps to reproduce

1. Environment: Use Jaeger 2.3.0 with OpenTelemetry 
2.  using curl http://127.0.0.1:8888/metrics
3.  on prometheus server, we have added in location /etc/prometheus/rules/jaeger.rules.yml  but it is not working .
4.  root@virtplatform:~# cat /etc/prometheus/rules/jaeger.rules.yml
```
groups:
- name: jaeger_alerts
  rules:
    - alert: PromHttpMetricErrs
      annotations:
        message: |
           {{ $labels.job }} {{ $labels.instance }} is experiencing {{ printf "%.2f" $value }}% HTTP errors.
      expr: 100 * sum(rate(promhttp_metric_handler_errors_total[1m])) by (instance, job ) / sum(rate(http_server_duration_milliseconds_sum[1m])) by (instance, job)> 1
      for: 15m
      labels:
        severity: warning

    - alert: OtelReceiverRefusedSpans
      annotations:
        message: |
          service {{ $labels.job }} {{ $labels.instance }} is dropping {{ printf "%.2f" $value }}% spans.
      expr: 100 * sum(rate(otelcol_receiver_refused_spans_total[1m])) by (instance, job) / sum(rate(jaeger_reporter_spans[1m])) by (instance, job)> 1
      for: 15m
      labels:
        severity: warning
```

### Expected behavior

It is should be expected like below sample.

![Image](https://github.com/user-attachments/assets/ac5dbf91-5e05-48d8-b24d-5a61d90c2713)

### Relevant log output

```shell

```

### Jaeger backend version

v2.3.0

### Deployment configs

```shell

```
