### ISSUE TITLE
[Bug]: Connection refused

### ISSUE THREAD

**Issue by nefilim** [jaegertracing/jaeger#7205]
### What happened?

Running jaeger:2.6.0 in a container with the attached configuration (virtually identical to [config-badger.yaml](https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/config-badger.yaml)), note that the ports for GRPC & HTTP OLTP receivers were changed (to 4319 & 4320) clashing with otel-collector hosted on the same docker network). Some internal process is still trying to connect to 4317?

The logs are filling with these errors:

```
jaeger-1  | 2025-06-05T02:27:24.621Z	warn	grpc@v1.72.0/clientconn.go:1405	[core] [Channel #1 SubChannel #8]grpc: addrConn.createTransport failed to connect to {Addr: "[::1]:4317", ServerName: "localhost:4317", BalancerAttributes: {"<%!p(pickfirstleaf.managedByPickfirstKeyType={})>": "<%!p(bool=true)>" }}. Err: connection error: desc = "transport: Error while dialing: dial tcp [::1]:4317: connect: connection refused"	{"grpc_log": true}
jaeger-1  | 2025-06-05T02:27:45.267Z	warn	grpc@v1.72.0/clientconn.go:1405	[core] [Channel #1 SubChannel #7]grpc: addrConn.createTransport failed to connect to {Addr: "127.0.0.1:4317", ServerName: "localhost:4317", BalancerAttributes: {"<%!p(pickfirstleaf.managedByPickfirstKeyType={})>": "<%!p(bool=true)>" }}. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused"	{"grpc_log": true}
```

less frequently I also see in similar vein:

```
jaeger-1  | 2025/06/04 21:02:27 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:4317: connect: connection refused"
jaeger-1  | 2025/06/04 21:02:42 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:4317: connect: connection refused"
jaeger-1  | 2025/06/04 21:03:32 traces export: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:4317: connect: connection refused"
```

Any idea what might be causing this?

Configuration

```
service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888 # TODO setup prom job?
    logs:
      level: info
    # TODO Initialize telemetry tracer once OTEL released new feature.
    # https://github.com/open-telemetry/opentelemetry-collector/issues/10663

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_query:
    storage:
      traces: some_store
      traces_archive: another_store
    ui:
      config_file: /etc/jaeger/config-ui.json

  jaeger_storage:
    backends:
      some_store:
        badger:
          directories:
            keys: "/tmp/jaeger/"
            values: "/tmp/jaeger/"
          ephemeral: false
      another_store:
        badger:
          directories:
            keys: "/tmp/jaeger_archive/"
            values: "/tmp/jaeger_archive/"
          ephemeral: false

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4320
      http:
        endpoint: 0.0.0.0:4319

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: some_store
```

### Steps to reproduce

Start the 2.6.0 container with the attached configuration and observe the logs

### Expected behavior

The logs to be error free

### Relevant log output

```shell

```

### Deployment configs

```shell

```
