### ISSUE TITLE
[Feature]: Elasticsearch backend support document routing

### ISSUE THREAD

**Issue by Frapschen** [jaegertracing/jaeger#7224]
## Use Case Summary
I have a use case where I want to route and store span data into different Elasticsearch indices based on trace resource attributes or span attributes (e.g., Kubernetes cluster name and namespace). This is similar to the approach used by the [OpenTelemetry Collector Elasticsearch Exporter's routing feature](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter#elasticsearch-document-routing).

For example, I define an index template like:
```
jaeger-span-${k8s.cluster.name}-${k8s.namespace.name}-YYYY-MM-DD
```
Which would generate concrete index names such as:

- jaeger-span-cluster-1-namespace-1-2025-06-13
- jaeger-span-cluster-1-namespace-2-2025-06-13

This allows us to apply different ILM (Index Lifecycle Management) policies based on the index pattern. For instance:

- Spans from cluster-1/namespace-1 should be retained for 7 days
- Spans from cluster-1/namespace-2 should be retained for 3 days

## Key Benefits
- Fine-grained lifecycle management: Different retention and rollover strategies per cluster/namespace.
- Better organization of data: Indices are logically grouped by source environment.
- Simplified querying and monitoring: Easy to search within specific clusters/namespaces.

### Problem

-

### Proposal

I propose adding a new configuration parameter: `index_suffix_template`.

I believe using a suffix will not break the existing template-matching index pattern, making this change more acceptable.

This field supports `Go template syntax`, allowing users to dynamically construct Elasticsearch index names using values from:

- Trace resource attributes
- Span attributes

> Note: Trace resource attributes take precedence over span attributes.

Configuration Example:
```
jaeger_storage:
  backends:
    storage/elasticsearch:
      elasticsearch:
        create_mappings: false
        use_aliases: false
        use_ilm: false
        indices:
          index_prefix: "insight"
          index_suffix_template: "${k8s.cluster.name}-${k8s.namespace.name}"
          spans:
            date_layout: "2006-01-02"
            rollover_frequency: "day"
            shards: 3
            replicas: 1
```
With the above configuration, the final index name will be constructed as follows:

`<index_prefix>-jaeger-span-<dynamic-suffix>-<date>`

For example:

`insight-jaeger-span-cluster-1-namespace-1-2025-06-13`

Behavior for Missing Attributes

If a referenced attribute (e.g. ${k8s.cluster.name}) is not found in either resource attributes or span attributes, it will be replaced with an empty string. For example:

`insight-jaeger-span--namespace-1-2025-06-13`

> You can optionally add a default value: `{or .value "Default"}`

### Open questions

Any advice is welcome, and if the community accepts this proposal, I would like to implement it.
