### ISSUE TITLE
[META] How to support breaking changes prior to 2.0.0

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger#811]
We have a couple of "breaking" changes in the pipeline https://github.com/jaegertracing/jaeger/pull/793 and https://github.com/jaegertracing/jaeger/pull/776

The former requires a c* schema update and the latter requires users to setup their metrics anew.

I feel hesitant landing them in master in case we have bug fixes that we want to release. What do people think about having a branch for 2.0.0 and doing the unenviable job of keeping master and 2.0.0 in sync? 

@jpkrohling @pavolloffay @objectiser @yurishkuro @vprithvi @tiffon @isaachier

**Comment by objectiser** [comment]
Why not do a final release, e.g. 1.4.2 or 1.5.0 whichever is more appropriate, and then all further work on master will be for 2.0.0.

If there are any bug fixes required to the 1.x version, we create a 1.x branch from the last release and only apply the fixes.

**Comment by benley** [comment]
Regarding the metrics naming changes, here is a partial set of prometheus metrics relabel rules to transform 1.3 / 1.4 metrics into the new naming scheme:

```yaml
- action: replace
  regex: jaeger_collector:(?:.+:)?[^:]+_by_svc:([^:]+)
  replacement: $1
  source_labels: ["__name__"]
  target_label: service
- action: replace
  regex: (jaeger_collector:(?:.+:)?[^:]+_by_svc):[^:]+
  replacement: $1
  source_labels: ["__name__"]
  target_label: __name__
- action: replace
  regex: jaeger_collector:([^:]+):((?:debug_)?(?:spans|traces)(?:_recd|_rejected|_saved)?(?:_by_svc)?)
  replacement: $1
  source_labels: ["__name__"]
  target_label: format
- action: replace
  regex: jaeger_collector:([^:]+):((?:debug_)?(?:spans|traces)(?:_recd|_rejected|_saved)?(?:_by_svc)?)
  replacement: jaeger_collector:$2
  source_labels: ["__name__"]
  target_label: __name__
- regex: jaeger_collector:([^:]+)
  replacement: jaeger_collector_$1
  source_labels: ["__name__"]
  target_label: __name__
```

This doesn't touch the :cassandra:.* metrics, just the core jaeger ones.  I haven't touched jaeger-agent or jaeger-query yet, but those are equally doable if anyone would find it useful.
