### ISSUE TITLE
Refactor Agent configuration

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger#927]
## Requirement - what kind of business use case are you trying to solve?

Enable gRPC communications between agent and collector (main issue #773).

## Problem - what in Jaeger blocks you from solving the requirement?

The agent configuration `app.Builder` directly embeds TChannel-based reporter configuration `app.reporter.tchannel.Builder`, rather than making it pluggable like `--processor.{format}.***` configurations. This makes the following flags into top-level options, even though they may not necessarily make sense to non-TChannel reporters:
```
--collector.host-port
--discovery.conn-check-timeout
--discovery.min-peers
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Create a nested hierarchy of reporters, e.g. to support the following config:
```yaml
reporters:
    - kind: tchannel
      # tchannel-specific parameters, e.g.
      collector:
        hostPort: ...
      discovery:
        minPeers: 10
    - kind: grps
      # grpc-specific parameters
```

## Any open questions to address

This will be a breaking change since the command line will be affected. We could potentially keep support for the old three options as "deprecated".
