### ISSUE TITLE
Kubernetes Operator and changes to the Helm chart

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger#928]
## Requirement - what kind of business use case are you trying to solve?

Historically, it's been hard to provide a Helm chart for Jaeger with support for the all-in-one image. Using an Operator, the deployment is done via code (Go, usually), making it possible to have complex deployment scenarios described in a simple "Custom Resource". For instance, these could be examples of such resources:

```yaml
apiVersion: jaegertracing.io/v1alpha1
kind: Jaeger
deployment: all-in-one
storage: memory
```
```yaml
apiVersion: jaegertracing.io/v1alpha1
kind: Jaeger
deployment: all-in-one
storage: cassandra
```
```yaml
apiVersion: jaegertracing.io/v1alpha1
kind: Jaeger
deployment: production
storage: elasticsearch
```

A Helm chart would still be provided, to install the operator (custom resource definition) and to load the YAMLs like the ones above (custom resource). 

This issue is about:

- [ ] Creating the operator under `jaegertracing/jaeger-operator`
- [ ] Changing the current Helm chart to use the new operator

cc @dvonthenen, @mikelorant, @pavelnikolov
