### ISSUE TITLE
jaeger-collector: Failed to init storage factory

### ISSUE THREAD

**Issue by sergeyklay** [jaegertracing/jaeger#931]
## Requirement - what kind of business use case are you trying to solve?

Is there any way to run jaeger-collector with Elasticsearch? Could you please provide a real and worked example with Collector and Elasticsearch versions?
```
docker run \
  --interactive \
  --name jaeger-collector \
  --rm=true \
  -e SPAN_STORAGE_TYPE=elasticsearch \
  -e ES_SERVER_URLS=http:/172.17.0.1:9200 \
  jaegertracing/jaeger-collector:1.5.0 \
  /go/bin/collector-linux \
      --es.server-urls=http:/172.17.0.1:9200 \
      --es.num-shards=1 \
      --es.num-replicas=0 \
      --log-level=error
```

```
{"level":"fatal","ts":1531408374.6548738,"caller":"collector/main.go:100","msg":"Failed to init storage factory","error":"health check timeout: no Elasticsearch node available","errorVerbose":"no Elasticsearch node available\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.init\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:84\ngithub.com/jaegertracing/jaeger/pkg/es.init\n\t<autogenerated>:1\ngithub.com/jaegertracing/jaeger/plugin/storage/es.init\n\t<autogenerated>:1\ngithub.com/jaegertracing/jaeger/plugin/storage.init\n\t<autogenerated>:1\ngithub.com/jaegertracing/jaeger/cmd/env.init\n\t<autogenerated>:1\nmain.init\n\t<autogenerated>:1\nruntime.main\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:186\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361\nhealth check timeout\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*Client).startupHealthcheck\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:1067\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.NewClient\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:240\ngithub.com/jaegertracing/jaeger/pkg/es/config.(*Configuration).NewClient\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/es/config/config.go:60\ngithub.com/jaegertracing/jaeger/plugin/storage/es.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/factory.go:65\ngithub.com/jaegertracing/jaeger/plugin/storage.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/factory.go:83\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:99\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:190\nruntime.main\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:198\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/asm_amd64.s:2361","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:100\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:698\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:783\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:736\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:190\nruntime.main\n\t/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/proc.go:198"}
```

Of course I tried latest collector image, and all Elasticsearch 5.x and 6.x series.
I tried ssh tunel to the real Elasticsearch, separated docker image with Elasticsearch, with login/password, without login password, with various configuration params - no luck. I read all existent in internet examples, even Chinese forums. Some (not all) of Elasticsearch which I tried:

```
{
  "_nodes" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "cluster_name" : "dev-elastic-log",
  "nodes" : {
    "Q0n-Hl5ZQZiwwYw3BczaVA" : {
      "name" : "ip-172-31-29-179.ec2.internal",
      "transport_address" : "172.31.29.179:9300",
      "host" : "172.31.29.179",
      "ip" : "172.31.29.179",
      "version" : "5.2.0",
      "build_hash" : "24e05b9",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[::]:9200"
        ],
        "publish_address" : "172.17.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    },
    "0wlVVzSARperS0uq6d-YLQ" : {
      "name" : "ip-172-31-58-46.ec2.internal",
      "transport_address" : "172.31.58.46:9300",
      "host" : "172.31.58.46",
      "ip" : "172.31.58.46",
      "version" : "5.2.0",
      "build_hash" : "24e05b9",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "[::]:9200"
        ],
        "publish_address" : "172.17.0.1:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

```
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "docker-cluster",
  "nodes" : {
    "S14jI0XOSDWCmgPcVyjoBA" : {
      "name" : "S14jI0X",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "5.6.2",
      "build_hash" : "57e20f3",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "attributes" : {
        "ml.max_open_jobs" : "10",
        "ml.enabled" : "true"
      },
      "http" : {
        "bound_address" : [
          "0.0.0.0:9200"
        ],
        "publish_address" : "172.18.0.2:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

**Comment by sergeyklay** [comment]
@jpkrohling, @yurishkuro I'm sorry for such annoying ping. Could you please take a look.

**Comment by yurishkuro** [comment]
> --name jaeger-collector \

if you're running ES in Docker as well, e.g. `--name elastic`, you need to make it visible to the collector via `--link elastic`.

You can also try running raw binaries from https://github.com/jaegertracing/jaeger/releases, which makes networking easier on the local host.

**Comment by sergeyklay** [comment]
As documentation says:
> **Warning:** The `--link` flag is a legacy feature of Docker. It may eventually be removed.

**Comment by sergeyklay** [comment]
Anyway this does not works. Here is my docker-compose file:
```yaml
---
version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    hostname: es-loadbalancer
    container_name: elasticsearch
    networks:
      - elastic-jaeger
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    environment:
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    hostname: jaeger-collector
    container_name: collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    networks:
     - elastic-jaeger
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http://es-loadbalancer:9200",
      "--es.username=elastic",
      "--es.password=changeme",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=error"
    ]
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  elastic-jaeger:
    driver: bridge
```


[Here is logs ](https://github.com/jaegertracing/jaeger/files/2190376/docker-compose.log).

**Comment by sergeyklay** [comment]
Yay! I managed this after 12 hours!
JFYI user _must_ start elasticsearch first and wait few seconds. For example using `docker-compose up -d elasticsearch`. This step is required to satisfy health check. Then you can run the rest containers using `docker-compose up -d`.

Here is my docker-compose.yml:
```yml
---
version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    networks:
      - elastic-jaeger
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    restart: on-failure
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    networks:
      - elastic-jaeger
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--log-level=error"
    ]
    depends_on:
      - elasticsearch

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    hostname: jaeger-agent
    command: ["--collector.host-port=jaeger-collector:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    networks:
      - elastic-jaeger
    networks:
      - elastic-jaeger
    restart: on-failure
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    depends_on:
      - jaeger-collector

  jaeger-query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - elastic-jaeger
    restart: on-failure
    command: [
      "--es.server-urls=http://elasticsearch:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug",
      "--query.static-files=/go/jaeger-ui/"
    ]
    depends_on:
      - jaeger-agent

volumes:
  esdata:
    driver: local

networks:
  elastic-jaeger:
    driver: bridge
```

But there is still some Query issue: "Cannot load index.html: Cannot open index.html: open /go/jaeger-ui/index.html: no such file or directory". 

[Here is logs](https://github.com/jaegertracing/jaeger/files/2190547/docker-compose.txt).

Should I fix my docker-compose or is it Query issue?
