### ISSUE TITLE
How can I mount a json file in all-in-one Image in kubernetes?

### ISSUE THREAD

**Issue by Yisaer** [jaegertracing/jaeger#970]
Hi, I'm using istio 1.0 and jaeger. I need to set jaeger using sampling strategies by `--sampling.strategies-file` option.
i deploy an `configmap` with a json file and  i mount this `configmap` in my deployment `istio-tracing.yml` and it start failed by finding `config.json`.
i want to know how can i mount a json file so that the container can start with  `--sampling.strategies-file` option in kubernetes.

Here are my `configMap` and `deployment`

```

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio-tracing
  namespace: istio-system
data:
  config.json: |-
    {
      "service_strategies": [
        {
          "service": "istio-mixer",
          "type": "probabilistic",
          "param": 0
        },
        {
          "service": "istio-policy",
          "type": "probabilistic",
          "param": 0
        },
        {
            "service": "istio-telemetry",
            "type": "probabilistic",
            "param": 0
        }
      ],
      "default_strategy": {
        "type": "probabilistic",
        "param": 1
      }
    }   

```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-tracing
  namespace: istio-system
  labels:
    app: istio-tracing
    chart: tracing-0.1.0
    release: istio
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: istio-tracing
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.5"
          imagePullPolicy: IfNotPresent
          args:
            - '--sampling.strategies-file=/etc/conf/config.json'
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/conf
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: MEMORY_MAX_TRACES
            value: "50000"
          livenessProbe:
            httpGet:
              path: /
              port: 16686
          readinessProbe:
            httpGet:
              path: /
              port: 16686
          resources:
            requests:
              cpu: 10m
            
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x

```
